### ISSUE TITLE
Some about dialog text not translatable

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/joist#227] opened 2015-03-16 18:02 UTC
Was just going through https://github.com/phetsims/phet-info/blob/master/code_review_checklist.md for Molecule Shapes and saw the following:

![molecule-shapes-about-dialog](https://cloud.githubusercontent.com/assets/480878/6672783/4cfd7d8e-cbd4-11e4-92cf-258645188174.png)

**Comment by jonathanolson** [comment] 2015-03-16 18:03
In code:
```js
new Text( 'version ' + version, { font: new PhetFont( 20 ) } ),
```

**Comment by pixelzoom** [comment] 2015-03-16 22:40
From PhetAboutDialog.java:

```
 // Copyright notice, not translated so no one messes with it, and so that we can easily change the date.
    private static final String COPYRIGHT_HTML_FRAGMENT =
            "<b>PhET Interactive Simulations</b><br>" +
            "Copyright &copy; 2004-2015 University of Colorado.<br>" +
            "<a href=" + PhetCommonConstants.PHET_LICENSE_URL + ">Some rights reserved.</a><br>" +
            "Visit " + HTMLUtils.getPhetHomeHref();
```

So that would leave the "version" string, which should be pretty easily addressed. Recommended to use a pattern, like:

> "versionPattern": "version {0}"

**Comment by pixelzoom** [comment] 2015-03-25 00:09
I handled i18n of the version string.

@ariel-phet Do we want "PhET Interactive Simulations" and the copyright to be translatable? They were not in the Java/Flash sims, with the following comment in the Java code:

> // Copyright notice, not translated so no one messes with it, and so that we can easily change the date.

**Comment by ariel-phet** [comment] 2015-03-25 01:09
I think we want to leave both of those string not translatable

**Comment by pixelzoom** [comment] 2015-03-25 03:34
About dialog is now fully translatable. Closing.

**Comment by ariel-phet** [comment] 2015-03-25 03:39
@pixelzoom - when you say "fully translatable" I assume you mean besides the strings we do not want translatable? Sorry, just wanted to clarify your last comment.

**Comment by pixelzoom** [comment] 2015-03-25 03:44
Correct - By "fully translatable" I mean that all text that should be translatable is now translatable.

**Comment by pixelzoom** [comment] 2015-03-25 03:45
"PhET Interactive Simulations" and "Copyright © 2004-2015 University of Colorado" are not translatable, by design.

**Closed by pixelzoom** 2015-03-25 03:45 UTC
Labels: bug
