### ISSUE TITLE
Firefox: Nav bar doesn't reach the bottom of the screen

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/joist#759] opened 2021-10-22 20:36 UTC
**Test device**
Dell
**Operating System**
Win 11
**Browser**
Firefox
**Problem description**
For https://github.com/phetsims/qa/issues/721, but it seems like it is a more general issue, so feel free to move.
The nav bar does not reach the bottom of the screen. This leaves a band of color.

**Visuals**
<img width="806" alt="navdoesntreach" src="https://user-images.githubusercontent.com/41024075/138519571-0ef28e39-ff3f-4caf-9dee-9447f224646e.png">

Troubleshooting information:

<details>

!!!!! DO NOT EDIT !!!!!
Name: ‪Balloons and Static Electricity‬
URL: https://phet-dev.colorado.edu/html/balloons-and-static-electricity/1.5.0-rc.2/phet/balloons-and-static-electricity_all_phet.html
Version: 1.5.0-rc.2 2021-10-11 21:55:48 UTC
Features missing: touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:93.0) Gecko/20100101 Firefox/93.0
Language: en-US
Window: 1280x667
Pixel Ratio: 1.5/1
WebGL: WebGL 1.0
GLSL: WebGL GLSL ES 1.0
Vendor: Mozilla (ANGLE (Intel(R) HD Graphics Direct3D11 vs_5_0 ps_5_0))
Vertex: attribs: 16 varying: 30 uniform: 4096
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 32767x32767
OES_texture_float: true
Dependencies JSON: {}

</details>

**Comment by samreid** [comment] 2021-11-02 03:49
I don't see this symptom on Mac/Chrome or Mac/Safari or Mac/Firefox.  Ideas to try when back to a windows computer:

* Is `height` fractional in this code?
```js
    // @public - Action that indicates when the sim resized.  This Action is implemented so it can be automatically played back.
    this.resizeAction = new Action( ( width, height ) => {
      assert && assert( width > 0 && height > 0, 'sim should have a nonzero area' );

      // Gracefully support bad dimensions, see https://github.com/phetsims/joist/issues/472
      if ( width === 0 || height === 0 ) {
        return;
      }
```

* Would adding some extra pixels vertically cover up the problem? 
* Should we apply clipping to the play area?

Also tagging @jonathanolson in case he can recommend something before I investigate.

**Comment by samreid** [comment] 2021-11-18 04:16
I tested this on Windows 11 ARM running on Mac Parallels, and could not reproduce the problem.

**Comment by samreid** [comment] 2021-11-21 19:43
I determined that the navigation bar height was non-integer, and it seemed to help a little bit to `Math.ceil` it.  However, the play area still showed through beneath the navigation bar at some resolutions.  I tried shifting the navigation bar down by 1px (in addition to the Math.ceil) and could not see any problems.  I don't feel great about this solution because I thought it would disturb the layout too much.  But I really couldn't tell the difference in testing.  I would also like to say this problem doesn't seem very severe and we may prefer not to apply a workaround. @jonathanolson can you please recommend how to proceed?

<details>

```diff

Index: js/Sim.js
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/js/Sim.js b/js/Sim.js
--- a/js/Sim.js	(revision b4a15f62b37ee55f145b05b25975f03cfd3c923e)
+++ b/js/Sim.js	(date 1637523623361)
@@ -189,9 +189,9 @@
       const scale = Math.min( width / HomeScreenView.LAYOUT_BOUNDS.width, height / HomeScreenView.LAYOUT_BOUNDS.height );
 
       // 40 px high on iPad Mobile Safari
-      const navBarHeight = scale * NavigationBar.NAVIGATION_BAR_SIZE.height;
+      const navBarHeight = Math.ceil( scale * NavigationBar.NAVIGATION_BAR_SIZE.height );
       this.navigationBar.layout( scale, width, navBarHeight );
-      this.navigationBar.y = height - navBarHeight;
+      this.navigationBar.y = height - navBarHeight + 1;
       this.display.setSize( new Dimension2( width, height ) );
       const screenHeight = height - this.navigationBar.height;
 

```

</details>

**Comment by jonathanolson** [comment] 2024-07-24 17:11
I'm curious if this is still an issue. I could not reproduce on Win10 + Firefox (don't have Win11).

It looks like we are providing background-color black on the entire page, however the Display has a different background color set.

It may be possible to have the navbar extend below as a workaround if this is still an issue.

@KatieWoe or @samreid, are you able to reproduce still, with the latest Firefox?

**Comment by KatieWoe** [comment] 2024-07-24 17:40
I still see this on Win 11 Firefox (Checked on Projectile Data Lab on the Website)

**Comment by jonathanolson** [comment] 2024-07-30 17:10
@samreid I'm curious if it is just a SVG issue, and we could extend the navbar below its actual bounds (which is not great in general) if we don't want to disturb layout.

Alternatively, does it adjust the layout if we expand beyond those bounds for this? (Or optionally flag it for Firefox only?)

**Comment by jonathanolson** [comment] 2024-07-30 17:11
I don't have Win11, so I can't reproduce unfortunately, sorry!

**Comment by samreid** [comment] 2024-07-30 19:11
Based on the comments above, it seems this is a rare problem (only affects win11 firefox) which is non-disruptive (will not make for a less effective learning tool), and that we are hesitant to disrupt the layout via a workaround. Therefore, it seems reasonable to close this issue as will-not-fix.

**Closed** 2024-07-30 19:28 UTC
