### ISSUE TITLE
Changing iPad orientations and reloading causes display errors

### ISSUE THREAD

**Issue by BryceAG** [phetsims/joist#448] opened 2017-10-20 21:56 UTC
With iPad iOS 10 and 11 (but not 9) if you go back a page, change the orientation, and go forward to the sim again it will not update the orientation.
![ezgif com-crop](https://user-images.githubusercontent.com/15327201/31843029-28a0ce48-b5ae-11e7-915d-1b9cb109510e.gif)
Additionally, the interactive area for objects is not where the displayed object is.
![ezgif com-video-to-gif 1](https://user-images.githubusercontent.com/15327201/31843065-4fbf9ce8-b5ae-11e7-8f2e-072ddcfc4728.gif)
closing and reopening safari, fully reloading the webpage, or changing the orientation ~4 times while the screen is still loaded will all fix the problem. Many websites, such as wikipedia, do not show this problem and update the orientation when reloading.

found while testing phetsims/QA#55

assigning to @ariel-phet to prioritize please

**Comment by ariel-phet** [comment] 2017-10-24 17:45
@BryceAG @phet-steele can you let me know if this happens with other simulations, or just with CCK? Since in Joist, I am assuming all sims?

**Comment by BryceAG** [comment] 2017-10-24 17:53
I haven't checked all of the sims, but confirmed that it happens with pendulum lab and projectile motion. I think it's safe to assume it happens for all of them.

**Comment by ariel-phet** [comment] 2017-10-24 18:00
@BryceAG thanks. Good to know.

**Comment by ariel-phet** [comment] 2017-10-24 18:05
@samreid I think this would be worth some investigation **after** CCK 1.0 is out the door. I am not too concerned by the issue, but we do see lots of organic examples of our sims used in both orientations.

I might also mark this for a quick discussion in dev meeting. For instance, on our iPad app the orientation is locked to landscape (which is what we design our sims for anyhow), and we have yet to see a complaint about that constraint. It seems a simple solution would be to always lock our sims to landscape mode for tablet style devices.

**Comment by pixelzoom** [comment] 2017-10-26 16:25
@ariel-phet suggested:
> It seems a simple solution would be to always lock our sims to landscape mode for tablet style devices.

I may not know what I'm talking about here... But since sims run in the browser, wouldn't this involve locking the browser to landscape mode?  And if so, isn't that a bit rude, since it assumes the browser is being used solely to run PhET sims?

**Comment by pixelzoom** [comment] 2017-10-26 18:09
10/26/2017 dev meeting:
JO: You can't lock the browser, but you can force the context to be locked. Would still be potentially buggy. 
AP: For @samreid to investigate after CCK:DC is published.

**Comment by samreid** [comment] 2017-10-26 18:10
@jonathanolson pointed out that the root problem is that the bounds are wrong.  We should investigate this.  We will not look into rotating the view, just looking into why the bounds are wrong.

**Comment by samreid** [comment] 2017-11-11 02:40
This StackOverflow suggests we are seeing the effects of the back-forward cache, https://stackoverflow.com/questions/8788802/prevent-safari-loading-from-cache-when-back-button-is-clicked

It seems we can detect when this happens and either (a) update the bounds or (b) refresh the entire sim.  The latter seems more likely to address other corner cases that might crop up.  The former seems more like a minimally invasive change but might have unexpected side effects.

**Comment by samreid** [comment] 2017-11-11 02:43
On the other hand, I'm wondering if we might see `onpageshow event.persisted` in other contexts such as in our apps.

**Comment by samreid** [comment] 2017-11-11 02:45
Also, iOS "Reading Mode" is another context where this could have expected caching behavior.

**Comment by samreid** [comment] 2017-11-11 16:41
My iPad3 is stuck on iOS 9.3.5, I'll try to work on this on Thursday.

**Comment by samreid** [comment] 2017-11-16 16:52
I'll have to move this to Thurdsay Dec 7 or 14.

**Comment by samreid** [comment] 2018-01-25 18:31
I'm not seeing the same problem on iPhone running iOS 11, perhaps it is reloading the whole page and hence getting the size right.

**Comment by samreid** [comment] 2018-01-25 18:47
@oliver-phet and I cannot reproduce the problem on the iOS 10.3.3 iPad mini.  The page gets reloaded each time.

We'll test the air 11.2 next.

**Comment by samreid** [comment] 2018-01-25 18:51
@oliver-phet and I reproduced the problem on the full size iPad air.  It seemed to be caching pages.  We hypothesize that the iPad mini and iPhone have a different memory profile and were not caching the pages.

**Comment by samreid** [comment] 2018-01-25 18:56
Now that I can reproduce the problem, I'll try to catch usage of the back/forward cache using 

```js
window.onpageshow = function(event) {
    if (event.persisted) {
        // TODO: relayout()
    }
};
```

**Comment by samreid** [comment] 2018-01-25 19:08
I went with:

```js
    window.onpageshow = function(event) {
      self.topLayer.addChild( new Text('onpageshow',{centerX:100,centerY:130}) );
      if (event.persisted) {
        self.resizeToWindow();
        self.topLayer.addChild( new Text('persisted',{centerX:100,centerY:160}) );
      }
    };
```

And it is showing `persisted` but not resizing to the window.  This suggests that the window.innerWidth/window.innerHeight are not updated after using the back/forward cache.

**Comment by samreid** [comment] 2018-01-25 19:14
I noticed other problems with the page loaded from cache, such as this which happened when rotating it back to the original orientation:

![image](https://user-images.githubusercontent.com/679486/35407474-4f0db6ba-01c9-11e8-8e25-6e0087760ead.png)

Hence I think we should investigate the reload solution proposed by https://stackoverflow.com/questions/8788802/prevent-safari-loading-from-cache-when-back-button-is-clicked

**Comment by samreid** [comment] 2018-01-25 19:28
Committed above and correctly reloads the page 10/10 times on Pauling (running 10.3.3).  Here is a dev version published with the proposed fix, for testing:
https://www.colorado.edu/physics/phet/dev/html/friction/1.5.0-dev.2/phet/friction_en_phet.html

**Comment by phet-steele** [comment] 2018-01-31 21:29
@samreid before I ask what I'm going to ask, I should say I have not yet tested the above link. So:

If I were to play devil's advocate, I'd have to ask, "How does this affect the PhET App on iOS?". It's been desirable that when exiting the app and returning to it, that the sim remain as it were and NOT refresh. Note I'm not talking about exiting the sim within the app, I mean literally pressing the home button, visiting some other app, then coming back to the PhET App.

I have no way to test your proposed fix in the app, so I can only speculate. Would your fix cause the sim to reload when the app is returned to? I don't fully understand when "pageshow" events occur.

**Comment by phet-steele** [comment] 2018-01-31 21:41
I suppose, if I were to draw conclusions with what I see in Mobile Safari proper, the sim does not reload when I leave the browser and return. This means it would probably be the same thing in the app?

**Comment by samreid** [comment] 2018-01-31 23:11
Based on discussion in https://stackoverflow.com/questions/8788802/prevent-safari-loading-from-cache-when-back-button-is-clicked I think the back-forward cache would not be used for the individual sim WebViews.

**Comment by ariel-phet** [comment] 2018-01-31 23:42
@mattpen do you know the answer to @samreid question?

**Comment by jjohnson5253** [comment] 2018-02-01 03:51
A new instance of a WebView is created every time the user opens a sim.  Whenever the user exits a sim (hits done button) the WebView is deleted and freed from memory.

So no, the same WebView is not reused for different sims.  

The WebViews do store a back-forward list.

**Comment by jjohnson5253** [comment] 2018-02-01 04:38
Currently, on the iOS app, when switching from portrait to landscape or vice versa, the same issue occurs where the sim does not resize to fit the screen.  @samreid Would your proposed fix remove this bug as well?

**Comment by samreid** [comment] 2018-02-01 17:34
Perhaps the WKWebView needs to be resized by the app?

**Comment by jjohnson5253** [comment] 2018-02-01 17:37
Well, the WKWebView resizes correctly, and when opening other sites (non phet) the site resizes correctly.  So it must have something to do with the simulation website code.

**Comment by samreid** [comment] 2018-02-02 00:30
> Well, the WKWebView resizes correctly, and when opening other sites (non phet) the site resizes correctly. So it must have something to do with the simulation website code.

We are following up with the iOS app bug in https://github.com/phetsims/phet-ios-app/issues/296

**Comment by phet-steele** [comment] 2018-02-05 17:21
@samreid the link in https://github.com/phetsims/joist/issues/448#issuecomment-360573580 is working acceptably. Back to you to decide how to move forward.

**Comment by samreid** [comment] 2018-02-05 17:24
Thanks, this is committed to joist master, and new deploys will pick it up.  We'll continue with the app fixes in https://github.com/phetsims/phet-ios-app/issues/296, closing.

**Closed by samreid** 2018-02-05 17:24 UTC
Labels: type:bug
