### ISSUE TITLE
Legends of Learning page freezes

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/joist#540] opened 2018-11-27 22:35 UTC
For https://github.com/phetsims/QA/issues/221.  When LoL has paused the sim, try and drag objects around, especially across the "paused" dialog.  The dialog may become highlighted.  When this occurs the LoL page freezes and must be refreshed.  I have only seen this on Edge.

**Comment by arouinfar** [comment] 2018-11-28 22:39
@KatieWoe can you take a screen capture of this issue?

It's not clear if this is a PhET bug or LoL bug, but Edge is such a low-use platform that I don't think this this would be considered a publication-blocking issue.

@mbarlow12 is the responsible dev for `coulombs-law`, but now that this issue is in joist, I'm going to unassign him. Not sure what the next step would be, so tagging for developer meeting.

**Comment by KatieWoe** [comment] 2018-11-28 23:05
https://drive.google.com/file/d/17HEKCEevUCwZ8PKrHejVKP8MYdpXkpTI/view?usp=sharing

**Comment by arouinfar** [comment] 2018-12-06 00:44
@mbarlow12 issues can now be transferred from one repo to another, so this issue now lives in joist. (Thanks @KatieWoe!)

This is not a sim-specific issue, and it's somewhat of an edge case, so I don't think it would be publication blocking.

**Comment by mbarlow12** [comment] 2018-12-06 02:52
Thank @arouinfar (facepalm)—it's been a long day :) If I'd just looked at the address bar...

**Comment by jessegreenberg** [comment] 2018-12-06 17:48
I am not able to reproduce this in Windows 10 Microsoft Edge 42.17134.1.0 with this link: https://phet-dev.colorado.edu/html/coulombs-law/1.0.0-rc.5/phet/coulombs-law_en_phet.html?legendsOfLearning

**Comment by jessegreenberg** [comment] 2018-12-06 19:06
I ran this through the test harness in Edge and could not produce the bug with the above steps:
<details><summary>Test HTML</summary>

```html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <title>title</title>
  </head>
  <body>
   <p>Hello Legends of Learning!</p>
  </body>

  <script type="text/javascript">
    window.parent.postMessage( { message: 'init' }, '*' );
  </script>
</html>
```
</details>

This indicates that it is not a LoL issue.

**Comment by KatieWoe** [comment] 2019-01-03 17:53
Found in https://github.com/phetsims/QA/issues/247

**Comment by jbphet** [comment] 2019-01-08 18:56
@ariel-phet - This issue was discussed today during the sound design meeting with respect to the RC that is in progress for Resistance in a Wire.  No one felt that this issue should block the publication of RIAW, but I thought we should check in with you.  Do you concur?

**Comment by ariel-phet** [comment] 2019-01-09 22:41
@jbphet I concur, this should not block publication of RIAW

**Comment by jbphet** [comment] 2019-01-11 18:47
We've decided that this isn't a blocking issue for publication of sims.  I don't have much experience with the LoL harness, and I don't know how important it is to resolve issues like this, so I'm not sure what should happen with this issue at this point.  I guess I'll assign it to @ariel-phet to prioritize and assign, or maybe just close.  Mentioning @samreid in case he has any input, since I believe he has been the main contact point with LoL.

**Comment by arouinfar** [comment] 2019-01-11 19:04
In the LoL environment, the teacher has the option to pause the activity for all students, most likely for a quick announcement or class discussion. When a teacher pauses the activity, this is what the students would see:

![image](https://user-images.githubusercontent.com/8419308/51054024-a93bed80-1598-11e9-9d5f-7dc8d7e438d9.png)

This is what the teacher would see:
![image](https://user-images.githubusercontent.com/8419308/51054071-cec8f700-1598-11e9-86e5-5718e059b094.png)

I don't think it would actually be possible for this bug to occur in the classroom, because the student doesn't have access to the sim while the harness is paused.

**Comment by ariel-phet** [comment] 2019-01-24 05:00
@KatieWoe considering this only happens on Edge, and considering @arouinfar comments above, I think we can ignore this issue.

Marking as `wontfix` and assigning back to you. Feel free to close and let the QA team know.

**Closed** 2019-01-24 15:54 UTC
Labels: type:bug, type:wontfix
