### ISSUE TITLE
"Adapted from" text doesn't appear on the home screen

### ISSUE THREAD

**Issue by samreid** [phetsims/joist#247] opened 2015-06-04 04:53 UTC
I thought I already commented somewhere about this but couldn't find it again.  When using the "Adapted from" branding, the black on black text doesn't appear on the home screen, but "adapted from" does appear on sim screens in the navbar.  It should also appear on the home screen, and should be tested for sims with black/white navbars.

**Comment by jbphet** [comment] 2015-06-25 18:37
Duplicate of #239, closing.

**Closed by jbphet** 2015-06-25 18:37 UTC
