### ISSUE TITLE
Add sound and keyboard icons to the home screen

### ISSUE THREAD

**Issue by jbphet** [phetsims/joist#503] opened 2018-07-20 23:14 UTC
In the 7/19/2018 design meeting it was decided that the sound and keyboard icons, which we've been working on adding to the nav bar, should also appear on the home screen.

**Comment by chrisklus** [comment] 2018-07-23 20:58
@jbphet and I decided to first implement this in the same way that the PhET button was added to the home screen (and kept in the same position as on the nav bar), but it seems like the PhET button was done this way because it was the only element needed on the home screen. See https://github.com/phetsims/joist/issues/304

It seems like a better way to do this might be to have the nav bar on the home screen so there is only one instance of the the PhET button and a11y buttons, as @samreid suggested here https://github.com/phetsims/joist/issues/304#issuecomment-155172161

@samreid could you add your thoughts on this?

**Comment by samreid** [comment] 2018-07-24 03:19
@chrisklus thanks for pointing out this issue.  I'm not sure the best way to address it, but I agree it is problematic to create two PhetButtons (one for HomeScreen and one for NavigationBar).  And it will be equally awkward to do the same thing for the a11y button strip.

What if we always show the navigation bar (even on the home screen), but on the home screen, its color matches the home screen background color, and the navigation bar title and screen buttons are invisible?  Or if there are artifacts at the navigation bar edge, the navigation bar fill could be blank.  This seems like a nontrivial change, but sounds promising for the long run.  Then we will only need code that instantiates the PhetButton and a11y button strip in one place and the layout will automatically match between home screen and sim screens.

If we like this plan, I'm not sure who should implement it or when.  Perhaps run it past @ariel-phet if it sounds good to you.

**Comment by chrisklus** [comment] 2018-07-24 16:57
@samreid thanks for your suggestions, that sounds like a good plan to me. I'm interested in making this change but would like to be able to ask you questions while doing so. @ariel-phet could you comment on the priority of this? Note that the first way i mentioned above has been implemented and is functional.

**Comment by ariel-phet** [comment] 2018-07-25 06:03
@chrisklus @samreid what you suggest above seems like the right way to do things instead of having copies of buttons and such. Certainly the sim title and other buttons should not show up.

I would be somewhat inclined to do this work on a branch since it is a nontrivial change, and then take a look at the proposed solution at dev meeting. This is the kind of thing the devs like CM might be good to have weigh in on so we can do a bit of "future proofing" in the implementation.

**Comment by samreid** [comment] 2018-07-25 12:43
Sound great.  @chrisklus when we create a branch, we have a policy to create a issue titled "branch: {{branchname}}" in the corresponding repo, so it is clear what the branch is for.  The issue should cross-link to this one so we have a paper trail.  Feel free to go for it and ask me questions here or in slack, or we can meet over zoom if our times match up, or I'll be able to schedule meetings around Tuesday July 31.

**Comment by chrisklus** [comment] 2018-07-25 15:40
@samreid thanks for getting me started, I'll create the branch sometime today and get going.

**Comment by chrisklus** [comment] 2018-07-26 21:42
Nav bar on the home screen has been implemented and appears to be working. I've tested on multi screen sims and single screen sims with black backgrounds and non-black backgrounds. @samreid could you look this over at your convenience?

One part I'm not crazy about is in `NavigationBar.js`:
```js
// update the state of whether the home screen is showing or not
showHomeScreenProperty.link( function( showHomeScreen ) {
  self.showHomeScreen = showHomeScreen;
  self.titleTextNode.setVisible( !showHomeScreen );
  if ( buttons ) {
    buttons.setVisible( !showHomeScreen );
  }

  // if the background of the sim doesn't change after the home screen, then the nav bar still needs to 
  // be updated
  self.navigationBarFill.value = self.showHomeScreen ? 'black' : sim.lookAndFeel.navigationBarFillProperty.value;
  self.navigationBarTextFill.value = self.showHomeScreen ? 'white' : sim.lookAndFeel.navigationBarTextFillProperty.value;
} );

sim.lookAndFeel.navigationBarFillProperty.link( function( navigationBarFill ) {
  self.navigationBarFill.value = self.showHomeScreen ? 'black' : navigationBarFill;
} );

sim.lookAndFeel.navigationBarTextFillProperty.link( function( navigationBarTextFill ) {
  self.navigationBarTextFill.value = self.showHomeScreen ? 'white' : navigationBarTextFill;
} );
```

On most multi-screen sims, the screen backgrounds are not black, so the `sim.lookAndFeel` links are triggered once when the sim loads, and again when one of the screens is clicked because the background color changes. But on a multi-screen sim where the screen's background doesn't change after navigating to one of the screens (like Rutherford scattering), the `sim.lookAndFeel` links aren't triggered, but the nav bar still needs to switch from black to white, so the two statements in the end of `showHomeScreenProperty.link` are needed. The consequence of this is that in every other multi-screen sim that has non-black screens, `self.navigationBarFill` and `self.navigationBarTextFill` are falsely updated when `showHomeScreenProperty` is set to false, and then immediately fixed when the `sim.lookAndFeel` links are triggered since the background color changes. Not sure if this is bad, but it seems a little funky.

**Comment by samreid** [comment] 2018-07-26 22:57
@chrisklus the changes looks great--I especially like all the code you were able to eliminate in 088058b6dd9b526384d87c9857107304a30ba155

I made two follow-up commits to simplify the logic in the part you described above.  I tested in Beer's Law Lab and Gravity & Orbits.  I haven't tested with projector mode or other color profiles.

Can you review and test my follow-up commits?

**Comment by chrisklus** [comment] 2018-07-27 17:17
@samreid ooh using the nav bar visibility is really slick. The issue is that `this.navigationBarFillProperty` is not updating when the home screen is showing (it should be the opposite of `sim.lookAndFeel.navigationBarTextFillProperty` in that case), so the a11y buttons are not showing up on the home screen. @jbphet thought of a fix that was much nicer than my original commit. On a side note, I also realized that `PhetButton` was not actually using its navigationBarTextFillProperty, so that eliminated the need for `this.navigationBarTextFillProperty` in `NavigationBar`. I've tested with Tambo, Blackbody Spectrum, Gravity & Orbits, and John Travoltage. @samreid can you review?

**Comment by samreid** [comment] 2018-07-27 18:17
I pulled the changes, made sure I have the right joist branch and tested Gravity and Orbits.  The homescreen looks right, but screen 1 looks like this:

![image](https://user-images.githubusercontent.com/679486/43339566-e9d4aa3e-9196-11e8-996a-e1359f3f417f.png)

Note the missing screen buttons and title from the navigation bar.  Am I testing this incorrectly, or is there an unpushed commit?

**Comment by chrisklus** [comment] 2018-07-27 20:44
@samreid my apologies, i wasn't careful when removing the original link to 'showHomeScreenProperty` and must've just been looking at the PhET button corner while testing. Fixed and retested on the same four sims.

**Comment by samreid** [comment] 2018-07-28 03:05
@chrisklus a reminder to please reassign issues after commenting, when appropriate.  I'll self-assign for now to continue review.  Thanks for the fix!

**Comment by chrisklus** [comment] 2018-07-30 15:39
@samreid you bet, thanks for the reminder.

**Comment by samreid** [comment] 2018-07-30 20:14
I'm going to merge master to this branch to make comparison and future merge easier.

**Comment by samreid** [comment] 2018-07-30 20:30
@chrisklus the rest of the changes look great, will you please coordinate with @jonathanolson regarding `Property(null)`?  I assigned https://github.com/phetsims/scenery/issues/839 to @jonathanolson.  Once that is addressed, this branch can be merged to master and deleted, and https://github.com/phetsims/joist/issues/506 can be closed, and this issue can be closed.  Also, at that point, please notify dev-public about these joist changes (brief summary) to let everyone know to keep an eye out for issues during testing once we publish another dev or rc from master.

**Comment by samreid** [comment] 2018-07-31 16:19
@jonathanolson addressed the change in the scenery issue, removing hold so @chrisklus can continue.  Please use `null` instead of `'black'` for the navigation bar fill `navigationBarFillProperty`, test again, then proceed with the steps in the preceding comment.

**Comment by samreid** [comment] 2018-07-31 16:26
How does transparent differ from null?  When would you use one over the other?

**Comment by chrisklus** [comment] 2018-07-31 17:08
Thank you @samreid @jonathanolson. @samreid I'm attempting to make the change but think I am missing something because still getting the same assertion as you: `Assertion failed: Invalid fill type` when attempting to use `return showHomeScreen ? null : simNavigationBarFill;`. My scenery repo is up to date.

**Comment by jonathanolson** [comment] 2018-07-31 17:13
Ahh sorry, I'll have that fixed up soon.

**Comment by jonathanolson** [comment] 2018-07-31 17:15
Ok, I believe I fixed the issue in master, can you pull? Sorry.

**Comment by chrisklus** [comment] 2018-07-31 17:17
@jonathanolson no worries at all, looks good.

**Comment by chrisklus** [comment] 2018-07-31 23:31
In the state where the home screen is showing, I set the nav bar fill to be the same as the home screen background color. Ready for review.

**Comment by samreid** [comment] 2018-07-31 23:39
Looks great, thanks!  I just added one comment.  Back to you to merge to master and do other steps noted in https://github.com/phetsims/joist/issues/503#issuecomment-408999701.  If there are merge conflicts, let me know if you want me to tag along.

**Comment by samreid** [comment] 2018-08-01 00:29
Looks great, thanks!  Next step is to notify the slack dev-public group as described in https://github.com/phetsims/joist/issues/503#issuecomment-408999701, then close this issue.  Nice work @chrisklus.

**Comment by chrisklus** [comment] 2018-08-01 00:45
@samreid thanks for all of your help and reviews! I have notified dev-public. Closing.

**Closed by chrisklus** 2018-08-01 00:45 UTC
Labels: dev:enhancement, priority:3-medium, status:ready-for-review
