### ISSUE TITLE
Screenshots have significantly impaired quality 

### ISSUE THREAD

**Issue by loganbraywork** [phetsims/joist#664] opened 2020-09-23 00:54 UTC
<b>Test Device</b>

Windows 10 Laptop

<b>Operating System</b>

Windows 10 2004

<b>Browser</b>

Chrome 85.0.4183.102

<b>Problem Description</b>

For https://github.com/phetsims/QA/issues/551

Screenshots made in the screenshot wrapper show lower quality for the play area (seen best in the quality of the rabbits) than original sim. 

<b>Visuals</b>

![2020-09-22NSScreenshotwrapper1](https://user-images.githubusercontent.com/54685448/93952004-06dc8300-fd05-11ea-884e-0dbb93490f4e.PNG)
![2020-09-22NSScreenshotwrapper2](https://user-images.githubusercontent.com/54685448/93952006-09d77380-fd05-11ea-8107-e38eda4ae707.PNG)

**Comment by jonathanolson** [comment] 2020-09-23 22:18
I believe the cause of this is likely to be that we're not mipmapping Sprites when rendered in Canvas. Additionally, I'd need to check about mipmapping handling with the normal Image Canvas renderer, or if there are ways to draw in higher quality.

**Comment by jonathanolson** [comment] 2020-09-23 22:30
It looks like the normal Image degraded appearance may be able to be improved by experimenting with the exact bias and verifying that we're handling hi-dpi screens nicely (it checks window.devicePixelRatio instead of the Scenery-wide backing-scale ratio).

The Sprites degradation is definitely from lack of mipmapping. This can be fixed by factoring out the mipmap code from Image into a more general place (since they both need to handle HTML images and Canvases).

@ariel-phet, I'd be curious what priority this should be (sounds like it could be a general improvement for screenshots, but ALSO will affect the NS Canvas fallback).

**Comment by ariel-phet** [comment] 2020-09-24 00:16
@jonathanolson can you clarify --

- when you say "will affect the NS Canvas fallback" will it improve that fallback or make it problematic (less performant, etc)
- do any of our supported platforms no longer support webgl? Or are we still worried about devices where webgl is not available on the GPU?

**Comment by jonathanolson** [comment] 2020-09-24 00:23
> when you say "will affect the NS Canvas fallback" will it improve that fallback or make it problematic (less performant, etc)

The changes would only introduce a probably-imperceptible startup performance cost, then it would be crisper/cleaner at probably not a perceptible performance cost.

> do any of our supported platforms no longer support webgl? Or are we still worried about devices where webgl is not available on the GPU?

I believe all supported platforms support WebGL. There could be those blacklisted devices where it wouldn't use WebGL, no clue on how often that would occur.

**Comment by ariel-phet** [comment] 2020-09-24 16:26
Putting at medium priority for the moment

@jonathanolson please work on this issue and elevate priority once Collision Lab is ready for its next dev test.

**Comment by jonathanolson** [comment] 2020-09-29 20:09
Some of this may be browser-specific. I'm noticing that I may be able to improve general quality by adjusting the mipmap bias for Canvas (since it seems to have worse handling than SVG for downscaling).

**Comment by jonathanolson** [comment] 2020-10-06 21:11
@loganbraywork can you retest?

There are a few parts of this that I've done:

1. Normally mipmapped images should display on Canvas better (will help screenshots or `?rootRenderer=canvas`)
2. Sprites (used in NS) will now mipmap in Canvas (when `mipmap:true` is passed in to the SpriteImage)
3. The screenshot generation will try to now match the high-dpi displays when taken (so on retina devices, it will quadruple the amount of pixels). This will affect the appearance primarily when viewing the screenshot on the same device.

So I'd note also whether the device has a high-dpi screen, as it's critical to know about when discussing screenshots.

@ariel-phet this will also require code review, and touches a lot of critical code.

**Comment by ariel-phet** [comment] 2020-10-07 00:26
@jonathanolson can you assign to @pixelzoom to review *after* it has been tested. If all looks good from testing, just go ahead and reassign it to him for review.

@pixelzoom although reviewing this work won't be a rush, it does potentially affect NS so probably to do sooner than later while things are fresh in your mind.

**Comment by KatieWoe** [comment] 2020-10-08 19:30
It looked ok on Mac 10.15 Chrome. When I checked Win 10 Chrome the image looked better but the screenshot was very, very large for some reason. Over twice the size of the sim it seemed.

**Comment by loganbraywork** [comment] 2020-10-08 21:02
The sim screenshots look better on Win 10 Chrome and I have the same issue katie has with them being slightly larger. The thumbnails for the two screens are both still lower quality it seems. On Win 10 Firefox it was the same.

**Comment by jonathanolson** [comment] 2020-10-15 18:55
Is it possible to get both a screenshot of the browser (including some of the browser interface, so I can verify scale) AND a screenshot generated by the browser? Also that "debug info" usually used for bug reports would be helpful.

**Comment by ariel-phet** [comment] 2020-10-22 04:33
Debug info:

Name: ‪Natural Selection‬
URL: https://phet.colorado.edu/sims/html/natural-selection/latest/natural-selection_en.html
Version: 1.1.1 2020-09-08 16:25:37 UTC
Features missing: applicationcache, generatedcontent, applicationcache, touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.75 Safari/537.36
Language: en-US
Window: 2394x1206
Pixel Ratio: 1.6041666269302368/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 4095
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 32767x32767
OES_texture_float: true
Dependencies JSON: {}

Screenshot using a snipping tool:
![NS screenshot with snipping tool](https://user-images.githubusercontent.com/4051174/96824982-5e960900-13ed-11eb-8619-c1be3daf63f1.PNG)

PhET screenshot
![Natural Selection screenshot (2)](https://user-images.githubusercontent.com/4051174/96825027-72da0600-13ed-11eb-857b-167279d22a2f.png)

**Comment by pixelzoom** [comment] 2020-10-30 15:42
@ariel-phet please clarify:

* Does this issue block https://github.com/phetsims/natural-selection/issues/251, the dev test for NS?

* Should the priority of this issue be increased?  I'm trying to reconcile how an issue can be "blocks publication" with "medium priority".

**Comment by ariel-phet** [comment] 2020-10-31 01:46
Not blocking

**Comment by zepumph** [comment] 2021-07-19 15:15
I'm going through this issue as part of https://github.com/phetsims/joist/issues/703, it looks like we have stalled out because @jonathanolson is waiting on @loganbraywork to supply info asked for in https://github.com/phetsims/joist/issues/664#issuecomment-709527174. Over to @loganbraywork with a ping.

**Comment by samreid** [comment] 2022-03-19 00:31
Using master, I get mac/chrome screenshots that look like this (zooming in on the ball):

<img width="266" alt="image" src="https://user-images.githubusercontent.com/679486/159099451-912660ca-7720-4d48-adca-3c7c60be5fb3.png">

This patch increases the backing scale before rendering:

```diff
Index: js/ScreenshotGenerator.js
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/js/ScreenshotGenerator.js b/js/ScreenshotGenerator.js
--- a/js/ScreenshotGenerator.js	(revision 1709c355d5bb4ffa7f29b284237498efc00f0b0e)
+++ b/js/ScreenshotGenerator.js	(date 1647649760087)
@@ -30,7 +30,7 @@
     const canvas = document.createElement( 'canvas' );
     const context = canvas.getContext( '2d' );
 
-    const backingScale = Utils.backingScale( context );
+    const backingScale = 10;
     canvas.width = sim.display.width * backingScale;
     canvas.height = sim.display.height * backingScale;
 
```

The screenshot from mac/chrome looks like this:

<img width="265" alt="image" src="https://user-images.githubusercontent.com/679486/159099504-fae326ff-b844-4298-b495-85b6229ee526.png">

Screenshots look equally great on firefox.  @jonathanolson can we just increase the backing scale like this?

**Comment by samreid** [comment] 2022-03-19 00:50
Everyone except firefox implements https://devdocs.io/dom/canvasrenderingcontext2d/imagesmoothingquality `ctx.imageSmoothingQuality = "low" || "medium" || "high"`, maybe we should enable that.

**Comment by samreid** [comment] 2022-03-19 00:50
Experimental patch with manual resampling:

<details>

```diff

Index: js/ScreenshotGenerator.js
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/js/ScreenshotGenerator.js b/js/ScreenshotGenerator.js
--- a/js/ScreenshotGenerator.js	(revision 1709c355d5bb4ffa7f29b284237498efc00f0b0e)
+++ b/js/ScreenshotGenerator.js	(date 1647650652827)
@@ -30,19 +30,30 @@
     const canvas = document.createElement( 'canvas' );
     const context = canvas.getContext( '2d' );
 
-    const backingScale = Utils.backingScale( context );
-    canvas.width = sim.display.width * backingScale;
-    canvas.height = sim.display.height * backingScale;
+    const INTERMEDIATE_BACKING_SCALE = 10;
+    canvas.width = sim.display.width * INTERMEDIATE_BACKING_SCALE;
+    canvas.height = sim.display.height * INTERMEDIATE_BACKING_SCALE;
 
-    context.scale( backingScale, backingScale );
+    context.scale( INTERMEDIATE_BACKING_SCALE, INTERMEDIATE_BACKING_SCALE );
     context.fillStyle = sim.display.domElement.style.backgroundColor;
     context.fillRect( 0, 0, canvas.width, canvas.height );
     const wrapper = new CanvasContextWrapper( canvas, context );
 
-    sim.rootNode.renderToCanvasSubtree( wrapper, Matrix3.scaling( backingScale ) );
+    sim.rootNode.renderToCanvasSubtree( wrapper, Matrix3.scaling( INTERMEDIATE_BACKING_SCALE ) );
+
+    // set up our Canvas with the correct background color
+    const canvas2 = document.createElement( 'canvas' );
+    const context2 = canvas2.getContext( '2d' );
+
+    const backingScale = Utils.backingScale( context2 );
+    canvas2.width = sim.display.width * backingScale;
+    canvas2.height = sim.display.height * backingScale;
+
+    context2.scale( backingScale / INTERMEDIATE_BACKING_SCALE, backingScale / INTERMEDIATE_BACKING_SCALE );
+    context2.drawImage( canvas, 0, 0 );
 
     // get the data URL in PNG format
-    return canvas.toDataURL( mimeType );
+    return canvas2.toDataURL( mimeType );
   }
 }
 

```

</details>

**Comment by pixelzoom** [comment] 2022-03-19 00:57
@arouinfar FYI, since we need a new screenshot for Geometric Optics in https://github.com/phetsims/geometric-optics/issues/369.

**Comment by samreid** [comment] 2022-03-19 15:31
This version samples at 2x and downsamples to be the right final dimension and size in MB.  It looks much crisper.  I want to test with 4x and improve the intermediate canvas dimensions before being done though:

<details>

```diff
Index: js/ScreenshotGenerator.js
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/js/ScreenshotGenerator.js b/js/ScreenshotGenerator.js
--- a/js/ScreenshotGenerator.js	(revision 1709c355d5bb4ffa7f29b284237498efc00f0b0e)
+++ b/js/ScreenshotGenerator.js	(date 1647703758047)
@@ -14,23 +14,13 @@
 
 class ScreenshotGenerator {
 
-  /**
-   * Given a sim, generate a screenshot as a data url
-   * @param {Sim} sim
-   * @param {string} [mimeType] - String for the image mimeType, defaults to 'image/png'
-   * @returns {string} dataURL
-   * @public
-   */
-  static generateScreenshot( sim, mimeType ) {
-
-    // Default to PNG
-    mimeType = mimeType || 'image/png';
+  static generateScreenshotAtIncreasedResolution( sim ) {
 
     // set up our Canvas with the correct background color
     const canvas = document.createElement( 'canvas' );
     const context = canvas.getContext( '2d' );
 
-    const backingScale = Utils.backingScale( context );
+    const backingScale = Utils.backingScale( context ) * 2;
     canvas.width = sim.display.width * backingScale;
     canvas.height = sim.display.height * backingScale;
 
@@ -40,9 +30,37 @@
     const wrapper = new CanvasContextWrapper( canvas, context );
 
     sim.rootNode.renderToCanvasSubtree( wrapper, Matrix3.scaling( backingScale ) );
+    return canvas;
+  }
+
+  static renderAtScale( sim, raster, scale ) {
+    const canvas = document.createElement( 'canvas' );
+    const context = canvas.getContext( '2d' );
+
+    const backingScale = Utils.backingScale( context );
+
+    // TODO: just use the raster's dimensions
+    canvas.width = sim.display.width * backingScale;
+    canvas.height = sim.display.height * backingScale;
+
+    context.scale( scale, scale );
+    context.drawImage( raster, 0, 0 );
+    return canvas;
+  }
+
+  // Default to PNG
+  static generateScreenshot( sim, mimeType = 'image/png' ) {
+
+
+    const highResolutionCanvas = ScreenshotGenerator.generateScreenshotAtIncreasedResolution( sim, 2 );
+    const desiredResolutionCanvas = ScreenshotGenerator.renderAtScale( sim, highResolutionCanvas, 0.5 );
+
+    // const highResolutionCanvas = ScreenshotGenerator.generateScreenshotAtIncreasedResolution( sim, 4 );
+    // const a = ScreenshotGenerator.renderAtScale( sim, highResolutionCanvas, 0.5 );
+    // const desiredResolutionCanvas = ScreenshotGenerator.renderAtScale( sim, a, 0.5 );
 
     // get the data URL in PNG format
-    return canvas.toDataURL( mimeType );
+    return desiredResolutionCanvas.toDataURL( mimeType );
   }
 }
 

```

</details>

**Comment by samreid** [comment] 2022-03-19 15:44
This version has a better subsampling and supports 4x.  I thought it was better in chrome, but it doesn't seem better in firefox or safari:

<details>

```diff
Index: js/ScreenshotGenerator.js
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/js/ScreenshotGenerator.js b/js/ScreenshotGenerator.js
--- a/js/ScreenshotGenerator.js	(revision 1709c355d5bb4ffa7f29b284237498efc00f0b0e)
+++ b/js/ScreenshotGenerator.js	(date 1647704570359)
@@ -14,23 +14,13 @@
 
 class ScreenshotGenerator {
 
-  /**
-   * Given a sim, generate a screenshot as a data url
-   * @param {Sim} sim
-   * @param {string} [mimeType] - String for the image mimeType, defaults to 'image/png'
-   * @returns {string} dataURL
-   * @public
-   */
-  static generateScreenshot( sim, mimeType ) {
-
-    // Default to PNG
-    mimeType = mimeType || 'image/png';
+  static generateScreenshotAtIncreasedResolution( sim, scale ) {
 
     // set up our Canvas with the correct background color
     const canvas = document.createElement( 'canvas' );
     const context = canvas.getContext( '2d' );
 
-    const backingScale = Utils.backingScale( context );
+    const backingScale = Utils.backingScale( context ) * scale;
     canvas.width = sim.display.width * backingScale;
     canvas.height = sim.display.height * backingScale;
 
@@ -40,9 +30,34 @@
     const wrapper = new CanvasContextWrapper( canvas, context );
 
     sim.rootNode.renderToCanvasSubtree( wrapper, Matrix3.scaling( backingScale ) );
+    return canvas;
+  }
+
+  static renderAtScale( raster, scale ) {
+    const canvas = document.createElement( 'canvas' );
+    const context = canvas.getContext( '2d' );
+
+    canvas.width = raster.width * scale;
+    canvas.height = raster.height * scale;
+
+    context.scale( scale, scale );
+    context.drawImage( raster, 0, 0 );
+    return canvas;
+  }
+
+  // Default to PNG
+  static generateScreenshot( sim, mimeType = 'image/png' ) {
+    // const desiredResolutionCanvas = ScreenshotGenerator.generateScreenshotAtIncreasedResolution( sim, 1 );
+
+    // const highResolutionCanvas = ScreenshotGenerator.generateScreenshotAtIncreasedResolution( sim, 2 );
+    // const desiredResolutionCanvas = ScreenshotGenerator.renderAtScale( highResolutionCanvas, 1 / 2 );
+    //
+    const highResolutionCanvas = ScreenshotGenerator.generateScreenshotAtIncreasedResolution( sim, 4 );
+    const a = ScreenshotGenerator.renderAtScale( highResolutionCanvas, 1 / 2 );
+    const desiredResolutionCanvas = ScreenshotGenerator.renderAtScale( a, 1 / 2 );
 
     // get the data URL in PNG format
-    return canvas.toDataURL( mimeType );
+    return desiredResolutionCanvas.toDataURL( mimeType );
   }
 }
 
```

</details>

I'm at a good point to reach out for help.

**Comment by samreid** [comment] 2022-03-19 15:47
Testing the same algorithm in Mac/Chrome for natural selection.  On the left is the default algorithm.  On the right is 2x * 1/2 resolution:

<img width="438" alt="image" src="https://user-images.githubusercontent.com/679486/159128101-ea9b2c2b-5c3c-4ec9-8116-e4a510dfcc8b.png">

Both final images have the same dimensions and roughly same # MB.

**Comment by samreid** [comment] 2022-03-19 17:55
This is mac/chrome 1, 2/2 and 4/2/2

<img width="823" alt="image" src="https://user-images.githubusercontent.com/679486/159132369-48815526-897b-4a5a-9b6a-81b88b8be4cb.png">

This is mac/firefox 1, 2/2 and 4/2/2

<img width="851" alt="image" src="https://user-images.githubusercontent.com/679486/159132515-6df145f9-b796-496c-895f-4bc256a08b6c.png">

This is mac/safari 1, 2/2 and 4/2/2

<img width="664" alt="image" src="https://user-images.githubusercontent.com/679486/159132761-dc1e9606-2236-4bee-a571-feab2e2dc0e0.png">

I do not know why the ground disappeared on mac/safari 4/2/2.

**Comment by samreid** [comment] 2022-08-03 04:29
I'm ready to check in with @jonathanolson and @pixelzoom about this issue.  Should we follow one of the proposed subsampling algorithms?

**Comment by pixelzoom** [comment] 2022-08-04 15:17
I don't have an opinion. Screenshots are outside my wheelhouse.

**Comment by jessegreenberg** [comment] 2022-08-11 17:55
During dev meeting 8/11/22

KP: Would the proposed changes in https://github.com/phetsims/joist/issues/664#issuecomment-1073053535 have a performance impact?
JO: Yes it might. I think we have done something like this in the past and we chose speed over quality. I think Safari + Canvas was the slowest platform/case for screenshots.
KP: How was this noticed?
SR: Noticed by a QA tester, others have voiced the poor quality.
SR: I did not notice degradation of performance.
KP: After changing, run it by QA to determine if it is fast enough.

Related to issues: https://github.com/phetsims/scenery/issues/1424 and https://github.com/phetsims/scenery/issues/1139.

SR will proceed with one of the 2/2 solutions in https://github.com/phetsims/joist/issues/664#issuecomment-1073053535 and then follow up with QA after the change.

**Comment by samreid** [comment] 2022-08-27 04:09
The missing grass above led me to try the *2 /2 strategy.  However, testing on latest Chrome and Safari the image quality was already great before making any code changes.  Perhaps they updated the browser for this.  But I still saw an advantage in Firefox:

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/679486/187013729-8ea34b24-bd2d-42cd-a1a2-e5d31bc5ff54.png">

**Comment by samreid** [comment] 2022-08-27 04:13
For QA Testing, please use the PhET Menu "Screenshot" button to capture images on several combinations of the following:

* Different sims, including some upcoming releases like gravity-and-orbits
* Different browsers, including Safari, Firefox, Chrome, Edge?
* Different devices, including Mac, Win, iPad, Chromebook

We are checking to make sure the image resolution is acceptable, please see above for examples.

**Comment by KatieWoe** [comment] 2022-08-29 21:17
- [ ] Tester = , Platform = , Time = 
- [ ] Tester = , Platform = , Time = 
- [ ] Tester = , Platform = , Time =

**Comment by pixelzoom** [comment] 2022-08-30 18:33
Note that this issue is causing problems in gas-properties, see https://github.com/phetsims/gas-properties/issues/200.

**Comment by Nancy-Salpepi** [comment] 2022-08-30 19:19
Center and Variability on Master is still missing the ground when taking a screenshot with MacOS 12.5.1 and Safari 15.6.1
![Center and Variability screenshot-2](https://user-images.githubusercontent.com/87318828/187511762-7adb321a-fefb-4930-9100-e1dea51ef1f4.png)

**Comment by pixelzoom** [comment] 2022-08-30 19:21
You might check Natural Selection too.  It uses scenery Sprites and WebGl, like the particles in Gas Properties.

**Comment by Nancy-Salpepi** [comment] 2022-08-30 19:31
The opposite of what is seen with diffusion/gases is happening in molecule shapes. The molecule in the screenshot is much smaller than in the sim (mac +safari)

The sim:

<img width="1321" alt="Screen Shot 2022-08-30 at 3 29 17 PM" src="https://user-images.githubusercontent.com/87318828/187526397-55f2a663-001c-4423-86b3-122abdf968f5.png">

The screenshot:
<img width="1363" alt="Screen Shot 2022-08-30 at 3 26 20 PM" src="https://user-images.githubusercontent.com/87318828/187526422-73f852eb-fac8-4b56-95dc-2d826cfda94b.png">

**Comment by Nancy-Salpepi** [comment] 2022-08-31 14:36
Natural Selection looks good to me on master with Mac + safari/chrome
![Natural Selection screenshot-10](https://user-images.githubusercontent.com/87318828/187704623-d9ec3aaf-88ca-40f2-912b-78f497148a64.png)

**Comment by Nancy-Salpepi** [comment] 2022-08-31 15:32
Screenshots for density with mac + safari/chrome are similar to what I was seeing with molecule shapes. 
![Density screenshot (1)](https://user-images.githubusercontent.com/87318828/187718502-ad73a88e-63c2-42b1-9881-0d96b1e77608.png)

**Comment by KatieWoe** [comment] 2022-08-31 16:58
I think we can call QA here. Some of the issues we've seen may also apply to other sims, but in random sampling we didn't see excessive blurriness and speed of taking screenshots was good.

**Comment by KatieWoe** [comment] 2022-08-31 19:17
While https://github.com/phetsims/gas-properties/issues/200 is fixed, the related issues here do not seem to be.

**Comment by samreid** [comment] 2022-09-01 01:02
This patch appears to fix both Molecule Shapes and Density.  But I didn't want to commit because I had to remove the backingScale from molecule shapes.  Density seemed fine to keep it.  @jonathanolson I'm at a good point for your feedback:

```diff

Index: main/mobius/js/ThreeIsometricNode.ts
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/main/mobius/js/ThreeIsometricNode.ts b/main/mobius/js/ThreeIsometricNode.ts
--- a/main/mobius/js/ThreeIsometricNode.ts	(revision c605e8e889c0671f23e86f349f91ba5df7ee3f4e)
+++ b/main/mobius/js/ThreeIsometricNode.ts	(date 1661992146506)
@@ -87,9 +87,11 @@
       this.domNode.invalidateDOM();
 
       // support Scenery/Joist 0.2 screenshot (takes extra work to output)
-      this.domNode.renderToCanvasSelf = wrapper => {
+      this.domNode.renderToCanvasSelf = ( wrapper, matrix ) => {
         const context = wrapper.context;
-        const canvas = this.stage.renderToCanvas( MobiusQueryParameters.mobiusCanvasSupersampling, Utils.backingScale( context ) );
+
+        assert && assert( matrix.getScaleVector().x === matrix.getScaleVector().y, `x scale (${matrix.getScaleVector().x}) must equal y scale(${matrix.getScaleVector().y})` );
+        const canvas = this.stage.renderToCanvas( MobiusQueryParameters.mobiusCanvasSupersampling, Utils.backingScale( context ) * matrix.getScaleVector().x );
 
         context.save();
 
Index: main/molecule-shapes/js/common/view/MoleculeShapesScreenView.js
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/main/molecule-shapes/js/common/view/MoleculeShapesScreenView.js b/main/molecule-shapes/js/common/view/MoleculeShapesScreenView.js
--- a/main/molecule-shapes/js/common/view/MoleculeShapesScreenView.js	(revision b06154b1ecc0511f36cd241dee38ba826b0c8357)
+++ b/main/molecule-shapes/js/common/view/MoleculeShapesScreenView.js	(date 1661994064741)
@@ -101,10 +101,11 @@
     this.moleculeNode.invalidateDOM();
 
     // support Scenery/Joist 0.2 screenshot (takes extra work to output)
-    this.moleculeNode.renderToCanvasSelf = wrapper => {
+    this.moleculeNode.renderToCanvasSelf = ( wrapper, matrix ) => {
       let canvas = null;
 
-      const backingScale = Utils.backingScale( wrapper.context );
+      assert && assert( matrix.getScaleVector().x === matrix.getScaleVector().y, `x scale (${matrix.getScaleVector().x}) must equal y scale(${matrix.getScaleVector().y})` );
+      const backingScale = matrix.getScaleVector().x;
 
       const effectiveWidth = Math.ceil( backingScale * this.screenWidth );
       const effectiveHeight = Math.ceil( backingScale * this.screenHeight );
@@ -211,9 +212,9 @@
           draggedParticleCount++;
         }
 
-        // We don't want to rotate while we are dragging any particles
-        // Additionally, don't rotate if we're zoomed into the sim - the pan/zoom listener will interrupt the rotation
-        // to start a pan, but not until there is a little bit of pointer movement. If we are zoomed in at all
+          // We don't want to rotate while we are dragging any particles
+          // Additionally, don't rotate if we're zoomed into the sim - the pan/zoom listener will interrupt the rotation
+          // to start a pan, but not until there is a little bit of pointer movement. If we are zoomed in at all
         // we don't want to allow movement that will soon just get interrupted.
         else if ( draggedParticleCount === 0 && animatedPanZoomSingleton.listener.matrixProperty.value.equalsEpsilon( Matrix3.IDENTITY, 1e-7 ) ) {
           // we rotate the entire molecule with this pointer

```

**Comment by jonathanolson** [comment] 2022-09-01 18:43
I'm git-bisecting, because I'm curious about what broke this.

**Comment by samreid** [comment] 2022-09-01 19:26
Yes, that commit was added to upscale 2x and downscale 0.5 the sim to improve the resolution.  But it seemed the WebGL layers weren't respecting that matrix scale.

**Comment by jonathanolson** [comment] 2022-09-01 21:17
Patched three.js-using code above to respect the needed scale. Can you verify?

**Comment by samreid** [comment] 2022-09-01 21:52
Molecule Shapes and Density look great, thanks!  As far as I know the last problem is the missing ground in Center and Variability: https://github.com/phetsims/joist/issues/664#issuecomment-1232068018

I'll look at that next.

**Comment by samreid** [comment] 2022-09-01 22:07
I was able to replicate the problem on safari. I observed that the gradient had 1.0 for two of the color stops. I believe these were incompatible. By adjusting one, I got the desired behavior. I do not believe this to be a pervasive problem, because we have not seen it reported before. If it happens again, we can make a common code issue to make sure the color stops are all at different values.  @Nancy-Salpepi and/or @KatieWoe can you please spot check the troubled sims? Close if all is well.

**Comment by Nancy-Salpepi** [comment] 2022-09-02 12:03
Things look good on mac + safari/chrome. @KatieWoe did you want to take a look at Windows before closing?

**Comment by KatieWoe** [comment] 2022-09-02 21:20
Looks ok on Win 11 chrome

**Closed by KatieWoe** 2022-09-02 21:20 UTC
Labels: type:bug, priority:3-medium, status:ready-for-review
