### ISSUE TITLE
Inconsistencies of "screens" query parameter

### ISSUE THREAD

**Issue by kathy-phet** [phetsims/joist#399] opened 2017-01-23 23:16 UTC
Amanda and I were discussing today how we should let people know more about the screens query parameter. It's a powerful feature for teachers. 

However, as I was writing up this feature for a potential partner, I also realized that we now have inconsistencies in the published simulations. 

States of matter uses "?screens=1,2" 
Function Builder uses "?screens=1.2" 

Seems problematic if we want to advertise this feature since it fails if you use 1.2 instead of 1,2 and vis versa, and that we will want to get all of the published simulations onto the same paradigm at some point. Why was it changed? I didn't follow there.

**Comment by jonathanolson** [comment] 2017-01-23 23:21
IIRC, it was changed because we originally thought commas weren't allowed (so periods were used), but it turned out commas were actually ok.

**Comment by kathy-phet** [comment] 2017-01-23 23:22
Is there a benefit to commas over periods?

**Comment by ariel-phet** [comment] 2017-01-24 00:34
@kathy-phet commas seem more semantically correct "1.2" looks more like a version number, whereas comma delimited screen numbers look more, well...comma delimited 🥇

**Comment by ariel-phet** [comment] 2017-01-24 00:41
@kathy-phet this also might be able to be dealt with via a maintainence releases, if you feel that is warranted, please mark it for dev meeting

**Comment by kathy-phet** [comment] 2017-01-24 02:35
Ok, but if I understand it means republishing all HTML sims to make it consistent across them? I don't know how much testing that would involve or if it can use shas and not require testing.

Sent from my iPhone

On Jan 23, 2017, at 5:34 PM, Ariel Paul <notifications@github.com<mailto:notifications@github.com>> wrote:


@kathy-phet<https://github.com/kathy-phet> commas seem more semantically correct "1.2" looks more like a version number, whereas comma delimited screen numbers look more, well...comma delimited ?

-

**Comment by ariel-phet** [comment] 2017-01-24 03:28
@kathy-phet a maintenance release involves shas and a patch, minimal testing. Not sure if that is possible in this instance or not. Will mark it for dev meeting.

**Comment by samreid** [comment] 2017-01-24 06:53
The commit that changed from dots to commas is 7ed7e850872f95c36926c9888c6ef6cff77ceec2 from November 14, 2016.  Any simulation published from master since then likely requires the commas.

Comma seems the preferable delimiter to me (more readable and easier to explain), but we should discuss whether we should add support for both for backward compatibility (and possibly deprecate dots).  Making maintenance releases for the small number of sims published since Nov 14 would probably be easier than creating maintenance releases for every sim published before Nov 14.

**Comment by samreid** [comment] 2017-01-24 06:54
I'm also wondering if some apache-side magic (URL rewriting) could help here.

**Comment by kathy-phet** [comment] 2017-01-24 12:34
I don't see the apache side helping on downloaded sims.
Kathy

Sent from my iPhone

On Jan 23, 2017, at 11:54 PM, Sam Reid <notifications@github.com<mailto:notifications@github.com>> wrote:


I'm also wondering if some apache-side magic (URL rewriting) could help here.

-

**Comment by jonathanolson** [comment] 2017-01-24 22:35
> Making maintenance releases for the small number of sims published since Nov 14 would probably be easier than creating maintenance releases for every sim published before Nov 14.

Is that because of the amount of variations of changes for different sims, based on QueryStringMachine-related changes?

> I'm also wondering if some apache-side magic (URL rewriting) could help here.

I'd rather do maintenance releases rather than not let sim HTML be cache-able in Varnish so we can conditionally redirect on sim startup.

**Comment by samreid** [comment] 2017-01-26 17:22
We would like to investigate doing a maintenance release to get old sims to use commas.

**Comment by samreid** [comment] 2017-01-26 17:22
I'll investigate this.

**Comment by samreid** [comment] 2017-01-26 17:23
@ariel-phet also said it would be good for @samreid to take the maintenance release process for a test drive.

**Comment by samreid** [comment] 2017-01-26 17:25
@kathy-phet recommends exhaustive cross-platform testing before we do any maintenance releases.  @samreid will create a tasks issue and assign to @ariel-phet.

**Comment by samreid** [comment] 2017-01-26 18:14
I will hold off on investigating patching until testing in the aforementioned issue is complete.

**Comment by jonathanolson** [comment] 2017-01-26 18:24
Having me available for the maintenance releases would be helpful.

I also committed an npm prune before the npm update steps for the maintenance release process. It doesn't tend to be updated when other tools are updated, so there's a chance of other out-of-date things.

**Comment by kathy-phet** [comment] 2017-01-26 20:02
Just looking into this a bit to see if there are still concerns out there about commas. Generally in all that I saw the recommendation was to avoid commas. They use these kinds of arguments: 
1) Users can be wary of URLs with commas because the are not common
2) Autolinking can fail/terminate at a comma (I assume this means like when I make a pdf with a URL or send and email with a URL that is text, the auto generated link would fail to capture the information after the comma). 

Any reflections on the discussions that can be found on the web boards now?

**Comment by samreid** [comment] 2017-01-27 16:44
It looks like the spec is here:
https://tools.ietf.org/html/rfc3986#section-3.3

query       = *( pchar / "/" / "?" )

where
 pchar         = unreserved / pct-encoded / sub-delims / ":" / "@"

and 

      sub-delims  = "!" / "$" / "&" / "'" / "(" / ")"  / "*" / "+" / "," / ";" / "="

Hence the comma is allowed in the query part of the path.

**Comment by samreid** [comment] 2017-01-27 16:44
Other information I found in my search:

http://stackoverflow.com/questions/198606/can-i-use-commas-in-a-url

Commas are allowed in the filename part of a URL, but are reserved characters in the domain*, as far as I know. [...] 

2.2. Reserved Characters

Many URI include components consisting of or delimited by, certain special characters. These characters are called "reserved", since their usage within the URI component is limited to their reserved purpose. If the data for a URI component would conflict with the reserved purpose, then the conflicting data must be escaped before forming the URI.

 reserved    = ";" | "/" | "?" | ":" | "@" | "&" | "=" | "+" | "$" | ","
The "reserved" syntax class above refers to those characters that are allowed within a URI, but which may not be allowed within a particular component of the generic URI syntax

https://www.searchenginenews.com/sample/content/are-you-using-commas-in-your-urls-heres-what-you-need-to-know

Commas are considered to be "reserved" characters for HTML, which include dollar signs, ampersands, pluses, semicolons, etc. These reserved characters can be used in creating URLs but they need to be encoded. 

http://stackoverflow.com/questions/14663813/using-commas-in-urls-can-break-the-url-sometimes

> Aside from dot-segments in hierarchical paths, a path segment is considered opaque by the generic syntax. URI producing applications often use the reserved characters allowed in a segment to delimit scheme-specific or dereference-handler-specific subcomponents. For example, the semicolon (";") and equals ("=") reserved characters are often used to delimit parameters and parameter values applicable to that segment. The comma (",") reserved character is often used for similar purposes. For example, one URI producer might use a segment such as "name;v=1.1" to indicate a reference to version 1.1 of "name", whereas another might use a segment such as "name,1.1" to indicate the same.

So, if you don’t intend to use the comma for the function it has as reserved character, you may want to percent-encode it with %2C. Users copying such an URL from their browser’s address bar would paste it in the encoded form, so it should work almost everywhere.

However, especially because it’s a reserved character, the unencoded form should work, too.

**Comment by samreid** [comment] 2017-01-27 16:45
@jonathanolson can you please review https://github.com/phetsims/joist/issues/399#issuecomment-275711962 and let me know your thoughts?

**Comment by samreid** [comment] 2017-01-27 17:41
I also noticed we have been using commas in the phetioExpressions query parameter for quite some time.  See https://github.com/phetsims/circuit-construction-kit-black-box-study/issues/37#issuecomment-275725822

**Comment by jonathanolson** [comment] 2017-01-27 18:05
> @jonathanolson can you please review #399 (comment) and #399 (comment) and let me know your thoughts?

Spec definitely says commas are allowed.

> Users can be wary of URLs with commas because the are not common

Possibly, however the usual case would be links with no query parameter?

> Autolinking can fail/terminate at a comma (I assume this means like when I make a pdf with a URL or send and email with a URL that is text, the auto generated link would fail to capture the information after the comma).

This only seems to be happening for when the comma is the last character in the URL, and it also happens when a period is the last character in a URL. I checked Skype, Gmail, and a few others.

Additionally, it's still possible to encode the comma and have the url work (e.g. `screens=1%2C2` is equivalent to `screens=1,2`).

So my personal preference would still be to use the comma as a separator (easier to remember, it's meant for that purpose), unless people dislike it.

**Comment by samreid** [comment] 2017-01-27 20:00
OK it seems we should proceed with cross-platform testing before performing a huge maintenance release, to confirm that this feature works on our supported platforms (that is, making sure our browsers are implementing the spec properly).

**Comment by ariel-phet** [comment] 2017-02-03 20:39
Testing confirmed in https://github.com/phetsims/tasks/issues/771

@samreid perhaps we should wait until @jonathanolson is back local before discussing the maintenance release.

**Comment by samreid** [comment] 2017-02-03 20:40
Sounds good, I'll put it on hold until then.

**Comment by samreid** [comment] 2017-02-16 17:49
@kathy-phet would like to confirm that it won't mess up in emails or PDFs

**Comment by samreid** [comment] 2017-02-16 18:03
Renders fine in Word and Word=>PDF:

![image](https://cloud.githubusercontent.com/assets/679486/23033834/cfe118fa-f436-11e6-838d-8e1f73723d8b.png)

The link takes me to:
https://phet.colorado.edu/sims/html/states-of-matter/latest/states-of-

Link from Word is OK though.

**Comment by samreid** [comment] 2017-02-16 18:08
In landscape, the line break is gone: and the link works OK

![image](https://cloud.githubusercontent.com/assets/679486/23034205/46010116-f438-11e6-9204-9f59acc8ff83.png)

@kathy-phet how old of versions of word/PDF/email do you want us to test?

**Comment by samreid** [comment] 2017-02-17 04:45
@pixelzoom reported that commas in his email client worked properly (not sure what email client he was using).

**Comment by pixelzoom** [comment] 2017-02-17 19:08
> @pixelzoom reported that commas in his email client worked properly (not sure what email client he was using).

Mail client on Mac OS X 10.11.6.  Sample URL was:
http://www.colorado.edu/physics/phet/dev/html/unit-rates/1.0.0-dev.56/unit-rates_en.html?screens=3,2,1

**Comment by samreid** [comment] 2017-02-22 15:05
I emailed:

Kathy,

On Thursday you requested that we check out other programs (like Word and email clients) to see how they deal with commas in URL query parameters.  See https://github.com/phetsims/joist/issues/399#issuecomment-280405334 and the following comments.  Modern Word and Mail (on Mac) did the right thing.  Do you recommend more testing?  How far back do you want us to test?

Jonathan is back and we may be able to work on maintenance releases for this in the near future after we complete testing.

Best Regards,
Sam

**Comment by samreid** [comment] 2017-02-24 04:15
At today's meeting @ariel-phet said there is no rush on getting this done quickly.

**Comment by samreid** [comment] 2017-03-16 18:38
It seems we only need to make maintenance releases for sims with 3 or more screens.  Sims with 1 screen do not need this query parameter.  Sims with 2 screens don't need a comma or decimal (if we disallow teachers being able to reorder the screens).  Here are the published sims with >3 screens:
- [ ] arithmetic
- [ ] balancing-act
- [ ] bending-light
- [ ] build-an-atom
- [ ] energy-skate-park-basics
- [ ] forces-and-motion-basics
- [ ] function-builder
- [ ] graphing-lines
- [ ] hookes-law
- [x] make-a-ten (may be new enough to already have commas)
- [ ] ph-scale
- [ ] reactants-products-and-leftovers
- [x] states-of-matter (done)
- [x] states-of-matter-basics (done)

Before investing in a maintenance release rollout, I would like to find out how important it is that teachers can select multiple screens.  For instance, even for the sims above that use decimals, you can still use ?screens=2 and it will correctly show screen 2.

**Comment by pixelzoom** [comment] 2017-03-16 18:57
I suspect that graphing-lines may see a new release branch soon after (or at the same time as) graphing-slope-intercept is published.  This is because some significant  graphing-lines have been addressed while implementing graphing-slope-intercept.

**Comment by pixelzoom** [comment] 2017-03-16 18:57
I suspect that graphing-lines may see a new release branch soon after (or at the same time as) graphing-slope-intercept is published.  This is because some significant  graphing-lines issues have been addressed while implementing graphing-slope-intercept.  But maybe that doesn't matter if you're planning to do a batch patch.

**Comment by samreid** [comment] 2017-03-16 20:01
Here's a comma delimited list of the sims:

> arithmetic,balancing-act,bending-light,build-an-atom,energy-skate-park-basics,forces-and-motion-basics,function-builder,graphing-lines,
hookes-law,ph-scale,reactants-products-and-leftovers

**Comment by samreid** [comment] 2017-03-16 20:10
Here are the joist shas, note they are not too similar:

---------------------
Map for joist

4564645c55c6ce85ccd69de3d17530787ab31bb4
  arithmetic
b72dcd00628c7ab8b59a607e6a4158f6a450ccdc
  balancing-act
ab5582ab6c8d87abb8bcdf947ef8144eb96ea7b6
  bending-light
ecd8d968e09ee1be00a444a261a01d1b391422e2
  build-an-atom
1fad8aae4b45f4afa242dc41d1da96900a622f84
  energy-skate-park-basics
b513b5ee1164a47d5baad7abd29591c7fadbe899
  forces-and-motion-basics
94bc734c61a9569d975cb8c4c15d213d95dffd37
  function-builder
41d6e1368449d1a7ba3e0ea77f654e91381c5037
  graphing-lines
e3dbcf2f9e63c01c7777f54f04b250896c9320a3
  hookes-law
6fb1b4812a4c1fbc07731dc6ed70423003442464
  ph-scale
153ba264a759089e7eff2dd56fb386df7b4188e9
  reactants-products-and-leftovers

>> Stored SHA groups in .maintenance.json

**Comment by jonathanolson** [comment] 2017-04-06 08:40
These should be patched in the maintenance release referenced at https://github.com/phetsims/joist/issues/399.

**Comment by samreid** [comment] 2017-08-03 04:13
@jonathanolson this looks great, I tested through the list above and confirmed that the sims on phet.colorado.edu support ?screens=2,3.  I'll email @kathy-phet

**Comment by samreid** [comment] 2017-08-03 04:15
I emailed @kathy-phet 

Kathy,

Jonathan rolled out maintenance releases for our sims so now the sims on phet.colorado.edu should all support the screens query parameter with commas. Full details are in https://github.com/phetsims/joist/issues/399

Best Regards,
Sam

**Closed by samreid** 2017-08-03 04:15 UTC
Labels: priority:3-medium, type:question

**Comment by kathy-phet** [comment] 2017-08-03 04:27
I was aware of this maintenance release. 

One small thing I have seen -- although I don't think it warrents additional releases -- is that for a 2 screen sim, you still need to use the "." to rearrange the order of the screens: 
https://phet.colorado.edu/sims/html/molecule-shapes-basics/latest/molecule-shapes-basics_en.html?screens=2.1

I assume this was because only sims with 3 screens or more were updated. But I think we got the bulk of the use cases - so I don't think we should deal with this limitation.

**Comment by samreid** [comment] 2017-08-03 16:18
> One small thing I have seen -- although I don't think it warrents additional releases -- is that for a 2 screen sim, you still need to use the "." to rearrange the order of the screens: 
https://phet.colorado.edu/sims/html/molecule-shapes-basics/latest/molecule-shapes-basics_en.html?screens=2.1

> I assume this was because only sims with 3 screens or more were updated. But I think we got the bulk of the use cases - so I don't think we should deal with this limitation. 

Understood. I reproduced the problem you described and confirmed that reordering with commas works in master, so this will be OK for new publications.
