### ISSUE TITLE
Preferences Dialog - Contents for localization

### ISSUE THREAD

**Issue by arouinfar** [phetsims/joist#814] opened 2022-06-02 22:33 UTC
Energy Skate Park will be republished with different character sets which should be selectable from the Preferences dialog. 

General Tab flow:

* Query parameter customizations (such as `altAccelerationUnits` or `schematicStandard`)
* Language ComboBox
* Culture and Region ComboBox (United States of America, Africa, Africa - Conservative) with default skater headshot
* Access & Inclusion blurb

Self-assigning work on some mockups.

**Comment by arouinfar** [comment] 2022-06-07 19:08
I've mocked up the General tab with sections for sim-specific settings and localization. I think the contents pop a bit more when there is some separation between the user controls and the blurb, so I've added a thin separating line between them. Perhaps this can be built into the dialog whenever the General tab contains more than just the blurb.

For ESP, the Culture and Region options would include: United States of America, Africa, and Africa - Conservative with the appropriate skater1Headshot. (For now, there are only 2 skater sets since the artwork is still in progress.)

@jessegreenberg can you work on implementing this? The general flow matches our previous discussion, and the pixel-polishing will likely be related to the specific strings rather than major organizational changes. 

<img width="620" alt="image" src="https://user-images.githubusercontent.com/8419308/172461174-821aaa1e-20f0-47b2-a36a-62b28487cbaa.png">

<img width="617" alt="image" src="https://user-images.githubusercontent.com/8419308/172461213-dfb93e4f-92cf-4ed5-ba31-d9b2ace648b0.png">

**Comment by jessegreenberg** [comment] 2022-06-23 02:10
This layout was added in the above commits @arouinfar.

I need to come back to the typing of CharacterSetComboBox, I have a temporary `unknown`.  This also created many phet-io problems that I could not resolve before getting to a commit point. Ill come back to both of these things.

**Comment by jessegreenberg** [comment] 2022-06-23 20:03
From design meeting 6/23/22:

- Localization label should be "Localization Settings"
- The "Language" ComboBox should only be present in the "all" version of the sim. We are not sure if this feature will be included for the localization work in ESP. To be discussed during quarterly goals meeting.
- "Culture and Region" should be read as "Region and Culture"
- We may want to remove the "inclusive features" intro content or make it shorter somehow when there are no inclusive features in preferences. To be discussed.

**Comment by jessegreenberg** [comment] 2022-06-29 16:54
Labels have been updated and the "Language" ComboBox has been removed. Back to @arouinfar for next steps including the last item in https://github.com/phetsims/joist/issues/814#issuecomment-1164817376.

**Comment by arouinfar** [comment] 2022-07-08 21:27
> Labels have been updated and the "Language" ComboBox has been removed. Back to @arouinfar for next steps including the last item in [#814 (comment)](https://github.com/phetsims/joist/issues/814#issuecomment-1164817376).

Thanks @jessegreenberg. The dialog looks good in master. 

>  We may want to remove the "inclusive features" intro content or make it shorter somehow when there are no inclusive features in preferences. To be discussed.

I think it makes the most sense to eliminate this content entirely when the only tab in the Preferences dialog is General. There aren't any other tabs or inclusive features tied to the dialog, so the blurb isn't relevant. Let's consult with the team at the next design meeting.

**Comment by zepumph** [comment] 2022-07-26 22:30
What do we think about moving the Localization section to its own tab? I think it would flow a lot better, keeping the general tab for simulation-specific (content-wise) preferences. I foresee this a staple part of our preferences, and I worry about tacking it onto the general tab. It seems especially important to have its own tab if it would have default controls that apply to all sims in the future (like a list of supported languages to dynamically change). From limited talking with JG, it may not be too hard to move this over. What do we think?

**Comment by jessegreenberg** [comment] 2022-07-26 22:33
I agree with @zepumph thoughts on organization of the dialog and it would not be difficult to change to this in the implementation. @arouinfar let us know what you think!

**Comment by arouinfar** [comment] 2022-07-27 22:33
@jessegreenberg @zepumph a Localization tab sounds great to me!

**Comment by samreid** [comment] 2022-08-10 05:00
> I think it makes the most sense to eliminate this content entirely when the only tab in the Preferences dialog is General.

Since this issue overlaps with https://github.com/phetsims/joist/issues/744, I'll commit a proposed implementation for review.   The naive implementation looks like this:

<img width="355" alt="image" src="https://user-images.githubusercontent.com/679486/183819248-da1c177b-432b-42b4-921e-060fee5186d1.png">

Design problems with this:
* It visually parses like there are essentially 3 "titles".
* It is odd to highlight "General" when there are no other choices
* Preferences, General and "Simulation Specific Settings" look like alphabet soup because they have varying font weights and sizes.
* Center alignment doesn't seem like a great fit for this case

**Comment by jessegreenberg** [comment] 2022-08-11 00:57
Brainstorming some other layout ideas before design meeting tomorrow:

The section could be left aligned in a layout container like this
<details>

![image](https://user-images.githubusercontent.com/6396244/184047119-1dcc3c03-ac5d-4098-9d75-da9a7ccb9928.png)

</details>

Maybe we get rid of the tab:

<details>

![image](https://user-images.githubusercontent.com/6396244/184047386-bfb1558e-909c-4786-aa6d-b51252b7fbce.png)

</details>

No tab and separator:

<details>

![image](https://user-images.githubusercontent.com/6396244/184047449-0008d369-8588-4e3b-88d3-4b8f550ae9c3.png)

</details>

**Comment by emily-phet** [comment] 2022-08-11 04:58
Sorry - I'm curious to learn more about this issue tomorrow in status. I'm assuming the example here is just a stand-in for a general case. For the specific example given, I just wanted to note the following - "projector mode" would be a visual change appropriate for a visual tab rather than the general tab.

**Comment by arouinfar** [comment] 2022-08-12 20:04
Meeting notes from the 8/11/2022 design meeting with EM, TS, AR, JG, MK, SR, KP, AP:

1. We want to add a "Localization" tab to house locale controls and other regional settings (e.g. character sets).
   * Based on today's PhET-iO discussion with @samreid @zepumph @jonathanolson about supporting `locale`, this functionality has become a priority.
3. The General tab should only contain truly simulation-specific features, so the "Simulation-specific Settings" heading is unnecessary. (@samreid removed it in the above commit.)
4. The blurb that appears under "General" was not designed only for sims that feature Inclusive Features, so it should not be optional. (@samreid already addressed this in the commit above.) However, we should make the wording a bit more general and remove "the tabs in".
5. Projector Mode belongs in the "Visual" tab. Currently `colorProfile` only supports `default` and `projector` but it may one day include a high-contrast or inverted mode. For now, we can continue to use a binary control to enable Projector Mode. The team liked the idea of doing something similar to the "Interactive Highlights" control:
![image](https://user-images.githubusercontent.com/8419308/184431115-d5e6fe03-6779-4d76-bebf-30f88cde70b8.png)

TODOS
- [ ] Create "Localization" tab and include a locale control. (Only appears in the _all file.)
![image](https://user-images.githubusercontent.com/8419308/184432488-50c1ad26-deea-4e67-bf84-895216de5b01.png)
- [ ] Remove "the tabs in" from the General tab blurb.
- [ ] Move Projector Mode to the "Visual" tab and mimic design of "Interactive Highlights" control. 
  * Title: Projector Mode
  * Help Text: Increase color contrast for better visibility in classrooms. 

There are several devs who have been a part of the Preferences/locale discussions, so co-assigning @jessegreenberg @zepumph @samreid @jonathanolson.

**Comment by jessegreenberg** [comment] 2022-08-12 20:39
The front-end changes listed here seem like they are in my wheelhouse, Ill start working on the checkboxes listed above now.

**Comment by jessegreenberg** [comment] 2022-08-12 22:46
A first pass for the Projector Mode toggle switch was added above. I have working copy changes for the new "Localization" tab that I will come back to next.

**Comment by samreid** [comment] 2022-08-12 23:33
I'm not sure what parts to work on, so I'll self-unassign.  Please add me back as needed.

**Comment by jessegreenberg** [comment] 2022-08-15 20:01
Several TODOs were added in the above commits, Ill keep cleaning up. But this is ready for a review, @arouinfar can you please review the changes and comment on next steps for this issue?

A new "Localization" tab has been added and controls were moved into that tab. You can see them in energy-skate-park/energy-skate-park-basics now.  Once reviewed we can remove the "Language" control until it is ready to integrate with https://github.com/phetsims/chipper/issues/1302.  An entry point for "Projector Mode" has been added to PreferencesConfiguration and it shows up in the "Visual" tab. You can see this in gravity-and-orbits.

**Comment by jessegreenberg** [comment] 2022-08-15 21:28
I think that cleanup is sufficient until further design feedback.

**Comment by arouinfar** [comment] 2022-08-15 21:56
Thanks @jessegreenberg, looks good in master. I've pasted in screenshots of the dialogs for easier review at this week's design meeting.

<img width="932" alt="image" src="https://user-images.githubusercontent.com/8419308/184724862-dca4983f-369d-42af-87e1-a84e71e6e182.png">
<img width="923" alt="image" src="https://user-images.githubusercontent.com/8419308/184724682-d122e762-7fcb-4296-9281-ca5e75037727.png">
<img width="929" alt="image" src="https://user-images.githubusercontent.com/8419308/184724764-d1a969ec-a592-4aa7-9d1b-a38ad3b702f1.png">

**Comment by jessegreenberg** [comment] 2022-08-18 15:54
There was some discussion on slack where we identified next steps and identified how to hook up language switching into the preferences dialog. It should be straight forward through the new `localeProperty`.

So we need to decide the best UI to control language from within the dialog. In @jonathanolson prototype there is a popup that shows each language. Mouse over and press selects a new language.

<details><summary>Navigation bar popup</summary>

![image](https://user-images.githubusercontent.com/6396244/185430649-c978636d-b03a-4267-9e30-582688f76d1e.png)

</details>

@kathy-phet / @arouinfar suggested a scrollable ComboBox for this, although ComboBox currently does not support scrolling. That likely would not be a trivial change.

Id like to try a nested dialog from within Preferences to see if that works. A prototype of this is added in the above commits. There would be a button in the "Localization" tab that opens a new dialog:

<details><summary>Language button</summary>

![image](https://user-images.githubusercontent.com/6396244/185431258-170fedad-4777-440f-a007-e04ef152c904.png)

</details>

And the Dialog could look something like one of the following:

<details><summary>Clickable Text</summary>

![image](https://user-images.githubusercontent.com/6396244/185431542-c5be73e1-c984-40f9-953f-2dcb3436f98c.png)

</details>

<details><summary>TextPushButtons (same width)</summary>

![image](https://user-images.githubusercontent.com/6396244/185435296-696e4627-9dbd-4b70-882a-33f69a02581f.png)

</details>

<details><summary>Sticky toggle buttons(same width)</summary>

![image](https://user-images.githubusercontent.com/6396244/185438771-6ba8202f-6287-4502-b270-958ad9e96497.png)

</details>

<details><summary>Sticky toggle button increasing number of rows</summary>

![image](https://user-images.githubusercontent.com/6396244/185439871-be60918e-c5a2-4295-94a5-0d7f1d26516e.png)

</details>

**Comment by samreid** [comment] 2022-08-18 18:40
Patch from demo:

<details>

```diff

Index: main/joist/js/preferences/PreferencesModel.ts
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/main/joist/js/preferences/PreferencesModel.ts b/main/joist/js/preferences/PreferencesModel.ts
--- a/main/joist/js/preferences/PreferencesModel.ts	(revision 7b0f9a422cf1f9fe191c4451bc0b8633d2cfd9e3)
+++ b/main/joist/js/preferences/PreferencesModel.ts	(date 1660847056284)
@@ -20,6 +20,7 @@
 import PickRequired from '../../../phet-core/js/types/PickRequired.js';
 import optionize, { EmptySelfOptions } from '../../../phet-core/js/optionize.js';
 import localizationManager from './localizationManager.js';
+import localeProperty from '../localeProperty.js';
 
 export type GeneralModel = Required<GeneralPreferencesOptions>;
 
@@ -200,7 +201,8 @@
 
   public supportsLocalizationPreferences(): boolean {
     return this.localizationModel.supportsLanguageSwitching ||
-           this.localizationModel.regionAndCultureDescriptors.length > 0;
+           this.localizationModel.regionAndCultureDescriptors.length > 0 ||
+           !!( localeProperty.validValues && localeProperty.validValues.length > 0 );
   }
 }
 
Index: main/joist/js/preferences/LocalizationPreferencesPanel.ts
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/main/joist/js/preferences/LocalizationPreferencesPanel.ts b/main/joist/js/preferences/LocalizationPreferencesPanel.ts
--- a/main/joist/js/preferences/LocalizationPreferencesPanel.ts	(revision 7b0f9a422cf1f9fe191c4451bc0b8633d2cfd9e3)
+++ b/main/joist/js/preferences/LocalizationPreferencesPanel.ts	(date 1660847442049)
@@ -10,12 +10,16 @@
  * @author Jesse Greenberg (PhET Interactive Simulations)
  */
 
-import { Node, VBox } from '../../../scenery/js/imports.js';
+import { FireListener, GridBox, Node, Text, VBox } from '../../../scenery/js/imports.js';
 import joist from '../joist.js';
 import { LocalizationModel } from './PreferencesModel.js';
-import LanguageComboBox from './LanguageComboBox.js';
+import localeInfoModule from '../../../chipper/js/data/localeInfoModule.js';
 import PreferencesPanelSection from './PreferencesPanelSection.js';
 import RegionAndCultureComboBox from './RegionAndCultureComboBox.js';
+import localeProperty from '../localeProperty.js';
+import Tandem from '../../../tandem/js/Tandem.js';
+import PhetFont from '../../../scenery-phet/js/PhetFont.js';
+import Panel from '../../../sun/js/Panel.js';
 
 class LocalizationPreferencesPanel extends Node {
   public constructor( localizationModel: LocalizationModel ) {
@@ -26,17 +30,38 @@
     } );
 
     if ( localizationModel.supportsLanguageSwitching ) {
-      contentNode.addChild( new LanguageComboBox(
-        localizationModel.languageProperty,
 
-        // TODO: Where will this information live and come from, see https://github.com/phetsims/joist/issues/814
-        [
-          {
-            locale: 'en',
-            localeLabel: 'English'
-          }
-        ]
-      ) );
+      const localePopup = new Panel( new GridBox( {
+        xMargin: 10,
+        yMargin: 3,
+        xAlign: 'left',
+        autoRows: 15,
+        scale: 0.6,
+        children: localeProperty.validValues!.map( locale => {
+          // @ts-ignore
+          return new Text( localeInfoModule[ locale ].localizedName, {
+            font: new PhetFont( 14 ),
+            cursor: 'pointer',
+            inputListeners: [
+              new FireListener( {
+                fire: () => {
+                  localeProperty.set( locale );
+                },
+                tandem: Tandem.OPT_OUT
+              } ),
+              {
+                move: sceneryEvent => {
+                  if ( sceneryEvent.pointer.isDown ) {
+                    localeProperty.value = locale;
+                  }
+                }
+              }
+            ]
+          } );
+        } )
+      } ) );
+
+      contentNode.addChild( localePopup );
     }
 
     if ( localizationModel.regionAndCultureDescriptors.length > 0 ) {
Index: main/joist/js/NavigationBar.ts
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/main/joist/js/NavigationBar.ts b/main/joist/js/NavigationBar.ts
--- a/main/joist/js/NavigationBar.ts	(revision 7b0f9a422cf1f9fe191c4451bc0b8633d2cfd9e3)
+++ b/main/joist/js/NavigationBar.ts	(date 1660846951815)
@@ -134,61 +134,61 @@
     this.barContents.addChild( phetButton );
 
     // TODO: Remove as part of https://github.com/phetsims/chipper/issues/1302 work
-    if ( localeProperty.validValues!.length > 1 ) {
-      this.localeNode = new Path( globeAmericasSolidShape, {
-        scale: 0.04,
-        fill: new DerivedProperty( [ this.navigationBarFillProperty ], color => {
-          return color.equals( Color.BLACK ) ? 'white' : 'black';
-        } ),
-        inputListeners: [
-          new FireListener( {
-            fire: () => {
-              localePopup.visible = !localePopup.visible;
-            },
-            tandem: Tandem.OPT_OUT
-          } )
-        ],
-        cursor: 'pointer'
-      } );
-      this.localeNode.mouseArea = this.localeNode.localBounds.dilated( 5 );
-      this.localeNode.touchArea = this.localeNode.localBounds.dilated( 5 );
-
-      const localePopup = new Panel( new GridBox( {
-        xMargin: 10,
-        yMargin: 3,
-        xAlign: 'left',
-        autoRows: 15,
-        children: localeProperty.validValues!.map( locale => {
-          // @ts-ignore
-          return new Text( localeInfoModule[ locale ].localizedName, {
-            font: new PhetFont( 14 ),
-            cursor: 'pointer',
-            inputListeners: [
-              new FireListener( {
-                fire: () => {
-                  localeProperty.value = locale;
-                  localePopup.visible = false;
-                },
-                tandem: Tandem.OPT_OUT
-              } ),
-              {
-                move: () => {
-                  localeProperty.value = locale;
-                }
-              }
-
-            ]
-          } );
-        } )
-      } ), {
-        visible: false
-      } );
-      sim.topLayer.addChild( localePopup );
-
-      ManualConstraint.create( sim.rootNode, [ this.localeNode, localePopup ], ( localeNodeProxy, popupProxy ) => {
-        popupProxy.rightBottom = localeNodeProxy.rightTop;
-      } );
-    }
+    // if ( localeProperty.validValues!.length > 1 ) {
+    //   this.localeNode = new Path( globeAmericasSolidShape, {
+    //     scale: 0.04,
+    //     fill: new DerivedProperty( [ this.navigationBarFillProperty ], color => {
+    //       return color.equals( Color.BLACK ) ? 'white' : 'black';
+    //     } ),
+    //     inputListeners: [
+    //       new FireListener( {
+    //         fire: () => {
+    //           localePopup.visible = !localePopup.visible;
+    //         },
+    //         tandem: Tandem.OPT_OUT
+    //       } )
+    //     ],
+    //     cursor: 'pointer'
+    //   } );
+    //   this.localeNode.mouseArea = this.localeNode.localBounds.dilated( 5 );
+    //   this.localeNode.touchArea = this.localeNode.localBounds.dilated( 5 );
+    //
+    //   const localePopup = new Panel( new GridBox( {
+    //     xMargin: 10,
+    //     yMargin: 3,
+    //     xAlign: 'left',
+    //     autoRows: 15,
+    //     children: localeProperty.validValues!.map( locale => {
+    //       // @ts-ignore
+    //       return new Text( localeInfoModule[ locale ].localizedName, {
+    //         font: new PhetFont( 14 ),
+    //         cursor: 'pointer',
+    //         inputListeners: [
+    //           new FireListener( {
+    //             fire: () => {
+    //               localeProperty.value = locale;
+    //               localePopup.visible = false;
+    //             },
+    //             tandem: Tandem.OPT_OUT
+    //           } ),
+    //           {
+    //             move: () => {
+    //               localeProperty.value = locale;
+    //             }
+    //           }
+    //
+    //         ]
+    //       } );
+    //     } )
+    //   } ), {
+    //     visible: false
+    //   } );
+    //   sim.topLayer.addChild( localePopup );
+    //
+    //   ManualConstraint.create( sim.rootNode, [ this.localeNode, localePopup ], ( localeNodeProxy, popupProxy ) => {
+    //     popupProxy.rightBottom = localeNodeProxy.rightTop;
+    //   } );
+    // }
 
     // a11y HBox, button fills determined by state of navigationBarFillProperty
     this.a11yButtonsHBox = new A11yButtonsHBox(
Index: main/joist/js/preferences/PreferencesConfiguration.ts
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/main/joist/js/preferences/PreferencesConfiguration.ts b/main/joist/js/preferences/PreferencesConfiguration.ts
--- a/main/joist/js/preferences/PreferencesConfiguration.ts	(revision 7b0f9a422cf1f9fe191c4451bc0b8633d2cfd9e3)
+++ b/main/joist/js/preferences/PreferencesConfiguration.ts	(date 1660847175645)
@@ -14,6 +14,7 @@
 import SpeechSynthesisAnnouncer from '../../../utterance-queue/js/SpeechSynthesisAnnouncer.js';
 import joist from '../joist.js';
 import { RegionAndCultureDescriptor } from './localizationManager.js';
+import localeProperty from '../localeProperty.js';
 
 export type GeneralPreferencesOptions = {
 
@@ -120,7 +121,7 @@
         supportsGestureControl: phetFeatures.supportsGestureControl
       },
       localizationOptions: {
-        supportsLanguageSwitching: false,
+        supportsLanguageSwitching: !!( localeProperty.validValues && localeProperty.validValues.length > 1 ),
         regionAndCultureDescriptors: []
       }
     }, providedOptions );
Index: main/sun/js/Dialog.ts
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/main/sun/js/Dialog.ts b/main/sun/js/Dialog.ts
--- a/main/sun/js/Dialog.ts	(revision e07b7b1ddbcc36c5fe227e542bc0f629364799e7)
+++ b/main/sun/js/Dialog.ts	(date 1660847569595)
@@ -18,7 +18,7 @@
 import StrictOmit from '../../phet-core/js/types/StrictOmit.js';
 import StringUtils from '../../phetcommon/js/util/StringUtils.js';
 import CloseButton from '../../scenery-phet/js/buttons/CloseButton.js';
-import { AlignBox, FocusManager, FullScreen, HBox, KeyboardUtils, Node, PDOMPeer, PDOMUtils, SceneryEvent, TColor, VBox } from '../../scenery/js/imports.js';
+import { AlignBox, Color, FocusManager, FullScreen, HBox, KeyboardUtils, Node, PDOMPeer, PDOMUtils, SceneryEvent, TColor, VBox } from '../../scenery/js/imports.js';
 import TSoundPlayer from '../../tambo/js/TSoundPlayer.js';
 import generalCloseSoundPlayer from '../../tambo/js/shared-sound-players/generalCloseSoundPlayer.js';
 import generalOpenSoundPlayer from '../../tambo/js/shared-sound-players/generalOpenSoundPlayer.js';
@@ -192,6 +192,7 @@
       // PanelOptions
       cornerRadius: 10, // {number} radius of the dialog's corners
       resize: true, // {boolean} whether to resize if content's size changes
+      // fill: new Color( 255, 255, 255, 0.5 ), // {string|Color}
       fill: 'white', // {string|Color}
       stroke: 'black', // {string|Color}
       backgroundPickable: true,


```

</details>

**Comment by jessegreenberg** [comment] 2022-08-18 19:15
The above commit is a demo of displaying with a carousel.

![image](https://user-images.githubusercontent.com/6396244/185474507-ef35b6fa-0a15-4b34-a6bb-b798b6fb2af5.png)

**Comment by jessegreenberg** [comment] 2022-08-18 19:18
Ill start on the items in https://github.com/phetsims/joist/issues/814#issuecomment-1219814475 but may need help for dynamic layout and the layout issue.

**Comment by jessegreenberg** [comment] 2022-08-18 23:08
I added the icon to the "Localization" tab and put in the layout we decided to try in design meeting today.

I am not familiar with dynamic layout yet, @jonathanolson would you mind continuing with the remaining items? Or if it would be best to pair that is great too.

> We observed that the second Chinese translation had a bounds or layout problem--lots of extra whitespace

I am not sure what is going on here but it is accompanied by a maximum call stack exceeded error
> Node.ts:2753 Uncaught RangeError: Maximum call stack size exceeded
    at Text.onTransformChange (Node.ts:2753:28)
    at TinyEmitter.emit (TinyEmitter.ts:95:9)
    at Transform3.invalidate (Transform3.js? [sm]:102:24)
    at Transform3.prependTranslation (Transform3.js? [sm]:140:10)
    at Text.prependTranslation (Node.ts:2692:21)
    at Text.translate (Node.ts:2345:14)
    at Text.setCenterX (Node.ts:2984:12)
    at set centerX [as centerX] (Node.ts:2994:10)
    at AlignBoxConstraint.updateProperty (AlignBox.ts:639:7)
    at AlignBoxConstraint.layout (AlignBox.ts:681:14)

Reproducible in gravity-and-orbits when selecting language Telugu in dialog.

**Comment by arouinfar** [comment] 2022-08-19 21:04
@jessegreenberg when the General Tab is empty, can we get rid of the divider above the blurb?

Here's what it currently looks like in master (RaP):
<img width="421" alt="image" src="https://user-images.githubusercontent.com/8419308/185706860-53046d9b-0676-4ab7-b850-c174d1ee9088.png">

Compare that to the published behavior in JT:
<img width="854" alt="image" src="https://user-images.githubusercontent.com/8419308/185706902-01cceb5a-7713-48a1-b6fb-9858c7a7b93e.png">

**Comment by jessegreenberg** [comment] 2022-08-19 21:18
There is some code in RAP putting empty content into the general tab in some cases, it think that is a sim specific issue. JT and GAO master look like the second screenshot you showed.

**Comment by jessegreenberg** [comment] 2022-08-19 22:29
After discussion with @zepumph who recommended these enhancements, I added a few more things
 - maxWidth safety net for when there are too many languages so that the Panel scales down instead of the whole dialog.
 - Highlights that show selected locale and a highlight for mouse interaction
 - Basic keyboard navigation

**Comment by jonathanolson** [comment] 2022-08-23 03:19
I made some updates above for dynamic strings and dynamic layout (and fixed a GAO issue that was showing up here).

@jessegreenberg could we possibly collaborate on the rest? I'm not sure how to get everything to show up, and I think it would be beneficial to work through some dynamic layout things together.

**Comment by samreid** [comment] 2022-08-25 22:21
From today's meeting:

@jonathanolson met with @jessegreenberg and discussed the questions above. @jonathanolson said @jessegreenberg is aware how to support dynamically sized things in the future, and that Gravity and Orbits things are sizing correctly at the moment.

**Comment by zepumph** [comment] 2022-08-25 22:31
Also, we said this was good enough for the current PhET-iO batch release. This issue is remaining open because in the future we will want a better UI for choosing a locale.

**Comment by jessegreenberg** [comment] 2022-09-02 19:26
This was still assigned to me for dynamic layout changes for Preferences in https://github.com/phetsims/joist/issues/814#issuecomment-1227816876. That was handled in https://github.com/phetsims/joist/issues/851.

@arouinfar back to you, is there anything else needed now for this issue?

**Comment by arouinfar** [comment] 2022-09-12 21:55
Thanks @jessegreenberg. I think we're ready to close this issue. We can open new issues for the ESP work as we encounter them.

**Comment by samreid** [comment] 2022-10-04 14:48
Discovered in https://github.com/phetsims/chipper/issues/946, there are TODOs remaining in the code. Reopening.

**Closed** 2022-10-04 18:04 UTC
Labels: design:general
