### ISSUE TITLE
Barrier rectangle input listener does not set dialog.isShown

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/joist#229] opened 2015-03-23 22:08 UTC
I ran into this while investigating issue phetsims/molecules-and-light#107.   The barrier rectangle for a popup window in sim has the following input listener

    this.barrierRectangle.addInputListener( new ButtonListener( {
      fire: function( event ) {
        assert && assert( sim.barrierStack.length > 0 );
        sim.hidePopup( sim.barrierStack.get( sim.barrierStack.length - 1 ), true );
      }
    } ) );

Dialog uses a public variable isShown to control whether the popup window should be shown again.  Directly calling sim.hidePopup means that dialog.isShown stays true and the popup window can never be reopened. Would the following listener be better so that dialog.isShown is set to false when the window closes?

    this.barrierRectangle.addInputListener( new ButtonListener( {
      fire: function( event ) {
        assert && assert( sim.barrierStack.length > 0 );
        sim.barrierStack.get( sim.barrierStack.length - 1 ).hide();
      }
    } ) );

**Comment by jonathanolson** [comment] 2015-03-23 22:44
It might make sense to have Dialog have better detection for this type of thing. I'm not a huge fan right now of requiring hide() and show() methods on anything used with showPopup(), etc.

**Comment by jbphet** [comment] 2015-03-30 22:45
I was curious why this hasn't been a problem for the About dialog, and the answer is that this dialog is recreated each time.

**Comment by jbphet** [comment] 2015-03-30 23:14
I discussed this with @jonathanolson and we decided to add a function to Sim.js to test whether a node was popped up, i.e. was present on the barrier stack, and to use this in Dialog rather than a flag that could get out of sync (and which is the root cause of this issue).  The code has been committed, and @jonathanolson should review.

**Comment by pixelzoom** [comment] 2015-05-22 19:10
@jonathanolson please review.

**Comment by jonathanolson** [comment] 2015-05-22 19:25
Looks good.

**Closed by jonathanolson** 2015-05-22 19:25 UTC
Labels: bug, Summer 2015 redeploy
