### ISSUE TITLE
"adapted from" text doesn't show up in the home screen

### ISSUE THREAD

**Issue by jbphet** [phetsims/joist#239] opened 2015-05-21 22:58 UTC
I'm using the adapted-from-phet brand repo, and the "adapted from" text is not showing up in the home screen of a multi-screen simulation.  I've tested on States of Matter and Build and Atom, and this is true for both.  The text does show up when on the individual screens.

I tried setting the color of the text to always be red in AdaptedFromPhETText.js, and the text was visible on both the home screen and the individual sim screens, so the problem is tied to the state of navigationBarTextFillProperty.

**Comment by pixelzoom** [comment] 2015-06-25 19:01
The problem is that the "adapted from" texted is fill with sim.lookAndFeel.navigationBarTextFillProperty, which defaults to 'black' and doesn't have a correct value until a screen is selected and a navbar is created.

The home screen doesn't currently have and properties in the lookAndFeel (perhaps it should, see https://github.com/phetsims/joist/issues/255) and assumes a 'black' background.  So I'm going to literally set the "adapted from" fill to 'white' for the home screen.

**Comment by pixelzoom** [comment] 2015-06-25 19:03
Fixed. Assigned to @jbphet to verify.

**Comment by pixelzoom** [comment] 2015-06-25 19:04
Fixed. Assigned to @samreid to verify.

**Comment by samreid** [comment] 2015-06-25 19:10
Code diffs look good, I also checked out the adapted-from-phet branch of the brand repo, and tested in Acid Base Solutions and Gravity and Orbits, and it looked great, nice work, closing.

**Closed by samreid** 2015-06-25 19:10 UTC
Labels: Summer 2015 redeploy
