### ISSUE TITLE
Objects can be picked up as you enter screen

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/joist#689] opened 2021-01-27 23:50 UTC
**Device**
iPad 6th Gen
**OS**
iPadOS 14.4
**Browser**
Safari
**Problem Description**
For phetsims/QA#600. Seems to be a touch issue. When on the home screen, if you enter one of the screens by tapping a part of the icon that turns in to the object, the object will be picked up as you enter the screen. This is done without lifting your finger.

**Steps to Reproduce**
1. Go to the home screen
2. Enter the first screen ty tapping on the left side of the icon. Your finger will end up over the red chips
3. May take a few attempts to get positioning right.

**Visuals**

https://user-images.githubusercontent.com/41024075/106069299-80bfb700-60bf-11eb-8e51-4d37203b289a.MP4

**Comment by jonathanolson** [comment] 2021-01-29 23:13
> We were surprised by this--we thought at least one of these interruptions would stop the behavior. Perhaps @jonathanolson can help us understand this better?

My hypothesis (without any confirmation, but makes sense) is:

1. User presses on the home-screen button
2. FireListener attaches to the Pointer
3. Button fires immediately, which causes the screen switch
4. Sim.js screen change listener calls `interruptSubtreeInput()` on the home screen
5. The FireListener unattaches to the Pointer (because of the interruption)
6. The user is now on the new screen, with their finger down but unattached
7. A tiny touch-move (while the finger is still down) happens, touch-snagging the draggable object (since the pointer isn't attached).

The conceptual way of making this work generally would be to mark something on the Pointer saying "this pointer was interrupted, so don't allow it to touch-snag anything else"

**Comment by jbphet** [comment] 2021-01-30 00:22
I just discussed this issue with @kathy-phet as part of the issue review prior to publishing number-line-integers.  She agrees that these buttons should fire on touch release, the way our other buttons do, rather than on touch start, the way they do now.

**Comment by jbphet** [comment] 2021-02-03 20:15
Issue https://github.com/phetsims/joist/issues/624 is referenced in a comment in `HomeScreenButton.js`, and appears pretty related to this issue.

**Comment by jbphet** [comment] 2021-02-03 20:55
I decided to pursue the avenue of making the buttons fire on touch release rather than trying to interrupt the input, since this seems like the way the buttons should behave anyway.  I essentially removed the feature where the user can select different home screen buttons by sliding around, and it seems to solve the problem.  I didn't commit this, but a patch is included below.

The next question is whether we should make this tradeoff or not.  To summarize, we can make the home button behavior more consistent with other buttons and solve the problem of accidentally picking up items in the sim by removing the feature where the user can put their finger down on one home screen icon and then move to another without lifting up.

@samreid wasn't sure about the history of the slide-around-select feature, so I'm going to mark this for dev meeting and perhaps we can make a decision there, or forward it on to design meeting.

By the way, there might be a way to have our cake and eat it too, i.e. to have the slide-around-select behavior work in conjunction with fire-on-touch-release.  I was disinclined to spend much time on this it's not particularly conventional behavior compared to, say, an iPad home screen, and since I think that keeping these buttons simple is the wisest choice.  However, if we really feel that this feature is important, I or someone else could look into ways where we could continue to support it.

```diff
Index: js/HomeScreenButton.js
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/js/HomeScreenButton.js b/js/HomeScreenButton.js
--- a/js/HomeScreenButton.js	(revision 7d9981f35ad3e0f92afa90f304e5dea6173eac94)
+++ b/js/HomeScreenButton.js	(date 1612383965034)
@@ -167,11 +167,9 @@
     let buttonWasAlreadySelected = false;
 
     // If the button is already selected, then set the sim's screen to be its corresponding screen. Otherwise, make the
-    // button selected. The one exception to the former sentence is due to the desired behavior of selecting on
-    // touchover, in which case we need to guard on touchdown since we don't want to double fire for touchover and
-    // touchdown, see https://github.com/phetsims/joist/issues/624
-    const buttonDown = () => {
-      if ( isSelectedProperty.value && ( !( fireListener.pointer instanceof Touch ) || buttonWasAlreadySelected ) ) {
+    // button selected.
+    const buttonFired = () => {
+      if ( isSelectedProperty.value ) {
         homeScreenModel.screenProperty.value = screen;
       }
       else {
@@ -180,7 +178,7 @@
     };
 
     const fireListener = new FireListener( {
-      fire: buttonDown,
+      fire: buttonFired,
       tandem: options.tandem.createTandem( 'inputListener' )
     } );
     this.addInputListener( fireListener );
@@ -197,15 +195,6 @@
       out: () => isHighlightedProperty.set( false )
     } );
 
-    // If you touch an unselected button, it become selected. If then without lifting your finger you swipe over to the
-    // next button, that one becomes selected instead.
-    this.addInputListener( {
-      touchover: event => {
-        buttonWasAlreadySelected = homeScreenModel.selectedScreenProperty.value === screen;
-        homeScreenModel.selectedScreenProperty.value = screen;
-      }
-    } );
-
     // set the mouseArea and touchArea to be the whole local bounds of this node, because if it just relies on the
     // bounds of the icon and text, then there is a gap in between them. Since the button can change size, this
     // assignment needs to happen anytime the bounds change.
```

**Comment by KatieWoe** [comment] 2021-02-03 22:20
This can be done in RaP: https://github.com/phetsims/QA/issues/601.

**Comment by KatieWoe** [comment] 2021-02-03 22:22
Additionally, as discussed with @jbphet over Zoom. On multiple sims published, if you click down on a home icon with a mouse, you enter the screen without letting go. This does not pick up items as it does in touch.

**Comment by chrisklus** [comment] 2021-02-04 18:02
From 2/4/21 dev meeting:

Devs generally think that firing on touch up is the way to go and will simplify things.

We discussed improving HomeScreenButton by using some button component, i.e. button model, from Sun, but think that these buttons are too custom of behavior to do so.

JB: How about I try the patch above and make a dev version to try it out on a touch screen. In the process, I'll try out integrating more standard listeners like PressListener more. I will attempt to keep the behavior of touch sliding around on the home screen buttons in this change. UPDATE: This was cancelled per the discussion below:

SR + more devs - why don't we use normal sun buttons, not two-touch buttons, on the Home Screen? Single-click buttons feel like a better user experience. Devs are on board with this and we would not like to re-discuss with everyone and Kathy at the next dev meeting, but instead @jbphet will schedule time with @kathy-phet.

@jessegreenberg will revert the touch-on-down change so it's back in the original state, and then we will proceed with design time for reevaluating the home screen.

**Comment by samreid** [comment] 2021-02-04 18:05
> SR + more devs - why don't we use normal sun buttons, not two-touch buttons, on the Home Screen?

To elaborate on this, @pixelzoom and @jbphet said this has been a confusing user experience when they share PhET sim home screens with others.

**Comment by samreid** [comment] 2021-02-11 17:56
From developer meeting:

@jbphet: Since @kathy-phet determined that we will not investigate a larger-scale change in https://github.com/phetsims/joist/issues/690, I'll work on addressing this by having the buttons fire on button up.  This is a small-scale enough change that it won't warrant accessibility changes, or require interviews.  I'll try to keep the functionality that you can mouse/touch over icons to slide around and make them larger, so we don't change more than is necessary.

**Comment by jbphet** [comment] 2021-03-06 01:02
Okay, I've got something working where the listener for the home screen buttons fires on the 'up' event, and we still get the nice "slide-around" behavior when using the sim on a touch-based device.  However, one aspect of these changes - the part that determines whether the fire listener is being fired by a touch-like pointer - strikes me as a little hokey.  I've committed it to a branch to avoid messing up any pending releases, so it shouldn't be a danger to anyone.

@jonathanolson - Can you look at the TODO in the commit and see if it represents a bug with Scenery input?  If it doesn't, and this is the expected behavior, can you look at what I've done to check whether the pointer is touch-like and see if it's a decent way to do it?

@zepumph - You apparently volunteered to review this (see above).  Thanks for that.  Can you take the branch for a test drive and see if this seems like the behavior that we collectively described when we discussed this a while back?  If so, we can take it to the larger team for a functional review.  The final code review should wait until we hear from @jonathanolson on my question above.

**Comment by zepumph** [comment] 2021-03-09 01:17
Thanks for taking the lead on this!

I do think you found a bug in scenery. PressListener.onRelease is called before the callback for FireListener.fire (when firing on up isntead of down). Thus PressListener.pointer (along with many other things) are cleared before the callback is called. 

@jonathanolson please checkout the joist branch: `fireHomeButtonsOnUp`. Then apply my patch. There is a downstream issue here.

This patch get's things working:

```
Index: scenery/js/listeners/PressListener.js
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/scenery/js/listeners/PressListener.js b/scenery/js/listeners/PressListener.js
--- a/scenery/js/listeners/PressListener.js	(revision 90d2b7380a66383c29fa7cf6f7baed3b4a3130f5)
+++ b/scenery/js/listeners/PressListener.js	(date 1615251787154)
@@ -629,6 +629,8 @@
   onRelease( event, callback ) {
     assert && assert( this.isPressed, 'This listener is not pressed' );
 
+    callback && callback();
+
     this.pointer.removeInputListener( this._pointerListener );
     this._listeningToPointer = false;
 
@@ -642,8 +644,6 @@
 
     // Notify after the rest of release is called in order to prevent it from triggering interrupt().
     this._releaseListener( event, this );
-
-    callback && callback();
   }
 
   /**
Index: joist/js/HomeScreenButton.js
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/joist/js/HomeScreenButton.js b/joist/js/HomeScreenButton.js
--- a/joist/js/HomeScreenButton.js	(revision 62786b61018224b4231e305b0a3bae0a7df68743)
+++ b/joist/js/HomeScreenButton.js	(date 1615252011420)
@@ -170,15 +170,16 @@
     // touchdown, see https://github.com/phetsims/joist/issues/624
     const buttonFired = () => {
 
-      // TODO: Why doesn't the following work?  Seems like it should.  See https://github.com/phetsims/joist/issues/689.
-      // const pointerIsTouchLike = fireListener.pointer && fireListener.pointer.isTouchLike();
-      const pointerIsTouchLike = fireListener.overPointers.length === 1 && fireListener.overPointers[ 0 ].isTouchLike();
+      const pointerIsTouchLike = fireListener.pointer && fireListener.pointer.isTouchLike();
 
       if ( isSelectedProperty.value && ( !pointerIsTouchLike || buttonWasAlreadySelected ) ) {
 
         // Select the screen that corresponds to this button.  This will make that screen appear to the user and the
         // home screen disappear.
         homeScreenModel.screenProperty.value = screen;
+
+        // TODO: is this needed? https://github.com/phetsims/joist/issues/689
+        // buttonWasAlreadySelected = false;
       }
       else {
 
```

. . . as far as the touch will again required two touches to select. But there is a downstream issue.

Because we will select the screen as part of that callback, input will be interrupted on the home screen before we are fully released. Thus, here is the full patch proposal that I would like @jonathanolson to review. To be clear I am not recommending that we commit this, as the guard while releasing seems gross to me. Instead I just wanted to point @jonathanolson in the right direction so that he could use it to find a production-worthy solution.

<details>
<summary>Best proposal of fix so far</summary>

```diff

Index: scenery/js/listeners/PressListener.js
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/scenery/js/listeners/PressListener.js b/scenery/js/listeners/PressListener.js
--- a/scenery/js/listeners/PressListener.js	(revision 90d2b7380a66383c29fa7cf6f7baed3b4a3130f5)
+++ b/scenery/js/listeners/PressListener.js	(date 1615252528985)
@@ -629,9 +629,20 @@
   onRelease( event, callback ) {
     assert && assert( this.isPressed, 'This listener is not pressed' );
 
+    // Don't call release again if we interrupt while releasing (from callback)
+    if ( this.releasingCallback ) {
+      return;
+    }
+
     this.pointer.removeInputListener( this._pointerListener );
     this._listeningToPointer = false;
 
+    this.releasingCallback = true;
+
+    // Call the callback before clearing all "pressed properties"
+    callback && callback();
+    this.releasingCallback = false;
+
     this.pointer.cursor = null;
 
     // Unset this properties after the property change, so they are visible to listeners beforehand.
@@ -642,8 +653,6 @@
 
     // Notify after the rest of release is called in order to prevent it from triggering interrupt().
     this._releaseListener( event, this );
-
-    callback && callback();
   }
 
   /**
Index: joist/js/HomeScreenButton.js
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/joist/js/HomeScreenButton.js b/joist/js/HomeScreenButton.js
--- a/joist/js/HomeScreenButton.js	(revision 62786b61018224b4231e305b0a3bae0a7df68743)
+++ b/joist/js/HomeScreenButton.js	(date 1615252390862)
@@ -170,9 +170,7 @@
     // touchdown, see https://github.com/phetsims/joist/issues/624
     const buttonFired = () => {
 
-      // TODO: Why doesn't the following work?  Seems like it should.  See https://github.com/phetsims/joist/issues/689.
-      // const pointerIsTouchLike = fireListener.pointer && fireListener.pointer.isTouchLike();
-      const pointerIsTouchLike = fireListener.overPointers.length === 1 && fireListener.overPointers[ 0 ].isTouchLike();
+      const pointerIsTouchLike = fireListener.pointer && fireListener.pointer.isTouchLike();
 
       if ( isSelectedProperty.value && ( !pointerIsTouchLike || buttonWasAlreadySelected ) ) {

**Comment by jonathanolson** [comment] 2021-03-10 20:33
This was partly by design, so that the state change to "unpressed" would be complete before firing. I'm a bit worried about all the backward compatibility with release handlers and what things expect, we'd need FULL testing on a lot to make sure we wouldn't break anything.

It would definitely be possible here to add a listener to record whether it's touchlike on the start:
```js
let pointerIsTouchLike;
// ...
press: event => { isTouchLike = event.pointer.isTouchLike(); }
```

Thoughts on that approach, @zepumph and @jbphet?

**Comment by zepumph** [comment] 2021-03-11 00:39
I think I prefer your solution @jonathanolson to what @jbphet had committed:

```
     const pointerIsTouchLike = fireListener.overPointers.length === 1 && fireListener.overPointers[ 0 ].isTouchLike();
```

I don't feel strongly though. Also your rationale makes sense about why we want to clear out `this.pointer` in terms of regression, but not in terms of general design. I do not think of a "release" as after the pointer has any relation to the PressListener, but rather _as_ it is ending it. It would be like getting the `keyup` event didn't give you what key came up because it had already become "up" and been nulled out before the event callback.

**Comment by jbphet** [comment] 2021-03-11 16:30
Marking for developer meeting so that we can determine who, if anyone, needs to give the behavior a final thumbs up, and also to discuss the two approaches that have been used/suggested.

**Comment by zepumph** [comment] 2021-03-11 19:05
Discussed this during today's dev meeting. 

@jonathanolson mentioned another way that we could support this would be by storing a `lastPointer`, but reentrant scenarios could be tricky.

```diff
Index: scenery/js/listeners/PressListener.js
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/scenery/js/listeners/PressListener.js b/scenery/js/listeners/PressListener.js
--- a/scenery/js/listeners/PressListener.js	(revision 9adba82eff9ed09d351573ebba6b674e4f0cef72)
+++ b/scenery/js/listeners/PressListener.js	(date 1615488375975)
@@ -634,6 +634,8 @@
 
     this.pointer.cursor = null;
 
+    this.lastPointer = this.pointer;
+
     // Unset this properties after the property change, so they are visible to listeners beforehand.
     this.pointer = null;
     this.pressedTrail = null;
Index: joist/js/HomeScreenButton.js
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/joist/js/HomeScreenButton.js b/joist/js/HomeScreenButton.js
--- a/joist/js/HomeScreenButton.js	(revision 62786b61018224b4231e305b0a3bae0a7df68743)
+++ b/joist/js/HomeScreenButton.js	(date 1615488371915)
@@ -170,9 +170,7 @@
     // touchdown, see https://github.com/phetsims/joist/issues/624
     const buttonFired = () => {
 
-      // TODO: Why doesn't the following work?  Seems like it should.  See https://github.com/phetsims/joist/issues/689.
-      // const pointerIsTouchLike = fireListener.pointer && fireListener.pointer.isTouchLike();
-      const pointerIsTouchLike = fireListener.overPointers.length === 1 && fireListener.overPointers[ 0 ].isTouchLike();
+      const pointerIsTouchLike = fireListener.lastPointer && fireListener.lastPointer.isTouchLike();
 
       if ( isSelectedProperty.value && ( !pointerIsTouchLike || buttonWasAlreadySelected ) ) {
 

```


>     const pointerIsTouchLike = fireListener.overPointers.length === 1 && fireListener.overPointers[ 0 ].isTouchLike();

@jonathanolson mentioned multiple issues with this one also, like if there are multiple pointers over.



We as a team feel like the state of PressListener should be a bit more in sync during the onRelease callbacks. @jbphet will take the lead in moving the callback to be before the PressListener state is cleared in PressListener.onRelease. Note the issues I had with reentrancy about interrupt in https://github.com/phetsims/joist/issues/689#issuecomment-793235059

**Comment by jbphet** [comment] 2021-03-16 18:09
Removing the "status:ready-for-review" label because it isn't really.

**Comment by jbphet** [comment] 2021-03-16 18:46
I met with @jonathanolson yesterday, and we experimented with modifying the processing of `onRelease` events in `pressListener` such that the pointer and trail information is valid during the invocation of the callback and changes to the `isPressedProperty`.  We did some basic regression testing, and things seemed fine, but snapshot comparison testing was showing some differences.  I committed the changes to branches in joist (branch `fireHomeButtonsOnUp`) and scenery (branch `pointersValidOnRelease`), and @jonathanolson is going to take a look and see what he can figure out.

**Comment by jonathanolson** [comment] 2021-03-18 17:11
I did more review, and the Scenery change should be safe to merge to master.

I haven't identified why tiny differences are showing up, but I'm not concerned about it. The following temporary change aqua-tested fine, showing no OTHER use of these parameters in that space:

```diff
diff --git a/js/listeners/PressListener.js b/js/listeners/PressListener.js
index 810bcd60..b2e5ebe2 100644
--- a/js/listeners/PressListener.js
+++ b/js/listeners/PressListener.js
@@ -643,11 +643,35 @@ class PressListener {
     // Notify after the rest of release is called in order to prevent it from triggering interrupt().
     this._releaseListener( event, this );
 
+    const pointer = this.pointer;
+    const pressedTrail = this.pressedTrail;
+    Object.defineProperty( this, 'pointer', {
+      get: () => {
+        throw new Error();
+      }
+    } );
+    Object.defineProperty( this, 'pressedTrail', {
+      get: () => {
+        throw new Error();
+      }
+    } );
+
     callback && callback();
 
+    pointer.cursor = null;
+
+    Object.defineProperty( this, 'pointer', {
+      value: null,
+      writable: true
+    } );
+    Object.defineProperty( this, 'pressedTrail', {
+      value: null,
+      writable: true
+    } );
+
     // These properties are cleared now, at the end of the onRelease, in case they were needed by the callback or in
     // listeners on the pressed Property.
-    this.pointer.cursor = null;
+
     this.pointer = null;
     this.pressedTrail = null;
   }
```

so I'm going to merge in the Scenery change.

**Comment by jonathanolson** [comment] 2021-03-18 17:14
Ok, the related single-line change on `fireHomeButtonsOnUp` should be good to go, but I'm going to pass things back to you for that branch in general. Let me know if you need anything else.

**Comment by jbphet** [comment] 2021-03-19 22:07
@zepumph and @chrisklus - You two are listed as the authors for `HomeScreenButton.js`, so one of you should probably review the changes.  You can sort out which one between you.

Please assign this issue back to me when you're done regardless of the outcome.  If no changes are necessary based on your review, I plan to work with QA to decide if we should do any specific testing for this change.

**Comment by zepumph** [comment] 2021-03-25 00:27
Looks really nice! Thanks so much for taking this on. I like the change in scenery, and especially like that @jonathanolson signed off on it!

**Comment by jbphet** [comment] 2021-03-25 16:28
@zepumph - Thanks for the review.

@KatieWoe - I've given this some thought, and I think it would be wise to have QA verify that the changes to the home screen button behavior work correctly on all our supported platforms with a particular emphasis on touch-based devices.  This change is fairly subtle, but it affects every multi-screen sim, so it seems prudent to make sure there aren't any unanticipated consequences.  I'll assign this to you to do or to delegate the testing.  Basically, I think verifying it on a small number of 2, 3, and 4 screen sims using the various devices at QA's disposal should suffice, with an eye out for anything unexpected that would negatively impact our users.

**Comment by KatieWoe** [comment] 2021-03-25 17:42
- [ ] Win 10 Chrome
- [ ] Win 10 Firefox
- [ ] MacOS 11 Chrome
- [ ] MacOS 11 Safari
- [ ] ChromeOS Chrome
- [ ] iPadOS Safari

**Comment by KatieWoe** [comment] 2021-03-25 22:49
Looks good. QA is done

**Comment by jbphet** [comment] 2021-03-29 17:01
Awesome.  Thanks @KatieWoe.  Closing.

**Closed by jbphet** 2021-03-29 17:01 UTC
Labels: type:bug
