### ISSUE TITLE
Long screen names push navigation bar icon to the right when sim is launched

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/joist#725] opened 2021-07-01 22:51 UTC
For https://github.com/phetsims/QA/issues/662. Seen on MacOS 11 in FIrefox. Also went back to check recent GaO issue https://github.com/phetsims/QA/issues/657 and saw it there, so assigning @samreid as well.

When renaming one of the screens, the behavior in studio itself looks fine. However, when the sim is launched the icon above the longer name has moved and can overlap the neighboring icons.

<img width="1425" alt="Screen Shot 2021-07-01 at 4 44 16 PM" src="https://user-images.githubusercontent.com/41024075/124197779-8b2a1680-da8c-11eb-94b8-a19a680f75c6.png">
<img width="1251" alt="Screen Shot 2021-07-01 at 4 43 47 PM" src="https://user-images.githubusercontent.com/41024075/124197789-8d8c7080-da8c-11eb-94f0-57a5ee2ad00e.png">
x

**Comment by pixelzoom** [comment] 2021-07-01 22:59
I've lost count of how many times we've had problems with alignment of text + icons in the navigation bar. 

Is this a duplicate of https://github.com/phetsims/joist/issues/718?  Why isn't that issue blocking?

**Comment by pixelzoom** [comment] 2021-07-01 23:34
Tracking for Natural Selection 1.4 in phetsims/natural-selection#295.  This issue is blocking.

**Comment by pixelzoom** [comment] 2021-07-02 14:33
This is blocking https://github.com/phetsims/QA/issues/657 and https://github.com/phetsims/QA/issues/662.  Since the latter has top priority, this issue is elevated to top priority.

**Comment by samreid** [comment] 2021-07-02 15:46
Wrapping in nested nodes seems safe, and seems to help a lot:

```diff
Index: js/NavigationBarScreenButton.js
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/js/NavigationBarScreenButton.js b/js/NavigationBarScreenButton.js
--- a/js/NavigationBarScreenButton.js	(revision 4cf017dc6096c19e12246d288d5fbe9362ad0ef0)
+++ b/js/NavigationBarScreenButton.js	(date 1625239974056)
@@ -91,7 +91,7 @@
 
     // spacing set by Property link below
     const iconAndText = new VBox( {
-      children: [ iconAndFrame, text ],
+      children: [ new Node( { children: [ iconAndFrame ] } ), new Node( { children: [ text ] } ) ],
       pickable: false,
       usesOpacity: true, // hint, since we change its opacity
       maxHeight: navBarHeight
```

![image](https://user-images.githubusercontent.com/679486/124298701-cde60000-db19-11eb-900c-0c08aadcde85.png)

However, now the highlight overlay is not centered:
![image](https://user-images.githubusercontent.com/679486/124298736-d8a09500-db19-11eb-88dd-7ae2f58dbf72.png)

There is also a similar problem on the home screen:
![image](https://user-images.githubusercontent.com/679486/124298872-0259bc00-db1a-11eb-9624-a7b1a98223d5.png)

That is solved with a combination of resize: true and nested nodes, but I don't know if the resize:true is safe (the comment says it is not)

```diff
Index: js/HomeScreenButton.js
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/js/HomeScreenButton.js b/js/HomeScreenButton.js
--- a/js/HomeScreenButton.js	(revision 4cf017dc6096c19e12246d288d5fbe9362ad0ef0)
+++ b/js/HomeScreenButton.js	(date 1625240665678)
@@ -42,7 +42,7 @@
 
     options = merge( {
       cursor: 'pointer',
-      resize: false, // don't resize the VBox or it will shift down when the border becomes thicker
+      resize: true,
       showUnselectedHomeScreenIconFrame: false, // put a frame around unselected home screen icons
 
       // pdom
@@ -107,7 +107,7 @@
       textPropertyOptions: { phetioReadOnly: true } // text is updated via screen.nameProperty
     } );
 
-    super( merge( { children: [ nodeContainer, text ] }, options ) );
+    super( merge( { children: [ new Node( { children: [ nodeContainer ] } ), new Node( { children: [ text ] } ) ] }, options ) );
 
     // @public (read-only)
     this.screen = screen;

```

![image](https://user-images.githubusercontent.com/679486/124299048-3634e180-db1a-11eb-9b1c-9c27a66ed2d4.png)

It seems the preferable long-term solution would be to completely rewrite the joist buttons, but that would be a lot of effort and require coordinate between designers, phet-io, a11y, etc.

**Comment by samreid** [comment] 2021-07-02 17:04
I found we are no longer changing strokes or structure on highlight change, so it is safe to resize:true on the HomeScreenButton.  I applied that change and the nested Node container for the dynamic text, and this is working much better.  The navigation bar highlight is still a little off centered though.

**Comment by samreid** [comment] 2021-07-02 17:28
I found that running `updateLayout` in the next frame fixes everything, but it is unclear why running `updateLayout` after changing the text is insufficient.  I committed it as a workaround.  Note that using the `runOnNextTick` makes it so the nested `new Node` is not necessary--but I left it in as a safety valve because I don't really understand the problem here.

If @jonathanolson has time to consult on this, it would be best, but if we need to publish before we get @jonathanolson assistance, maybe that is OK?  I'll reach out to @jonathanolson.

**Comment by jonathanolson** [comment] 2021-07-06 15:56
I'm looking into depth into this. Workarounds seem safe.

**Comment by jonathanolson** [comment] 2021-07-06 19:05
Cleaned up NavigationBarScreenButton a bit, I'm not able to reproduce the bugginess before/after my above patch. @samreid can you look it over? It gets rid of the delay, updateLayout will be triggered on what it's relying on (text bounds), and the stroke will always exist for bounds purposes.

I'll be working on the HomeScreenButton bit next.

**Comment by jonathanolson** [comment] 2021-07-06 20:11
I may have rebroken NavigationBarScreenButton in this same way, it looks like I wasn't testing all of the different ways of triggering this.

**Comment by samreid** [comment] 2021-07-06 21:46
It seems so, pulling master and testing following these steps:

1. Launch gravity and orbits in studio
2. navigate to gravityAndOrbits.modelScreen.nameProperty
3. Set the value to Model NTHUONEUTHOEU
4. Press Preview Sim

It comes up like this:

![image](https://user-images.githubusercontent.com/679486/124670438-395d0400-de71-11eb-8dc9-8654aa81f07e.png)

Part of my confusion about this implementation is how "Preview Sim" has a different code path than the live view in studio.

**Comment by zepumph** [comment] 2021-07-07 16:03
>Part of my confusion about this implementation is how "Preview Sim" has a different code path than the live view in studio.


That isn't totally surprising to me, since it is being run through PhET-iO state.

Here are where my debuggers are:

```diff
Index: js/NavigationBarScreenButton.js
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/js/NavigationBarScreenButton.js b/js/NavigationBarScreenButton.js
--- a/js/NavigationBarScreenButton.js	(revision 80c2c767d2c97ab4a6bfdc49663bf1e145f17355)
+++ b/js/NavigationBarScreenButton.js	(date 1625672678883)
@@ -172,6 +172,7 @@
 
     // Update the button's layout
     const updateLayout = () => {
+      debugger;
 
       // adjust the vertical space between icon and text, see https://github.com/phetsims/joist/issues/143
       iconAndText.spacing = Math.max( 0, 12 - text.height );
@@ -198,6 +199,7 @@
 
     // Update the button's text and layout when the screen name changes
     screen.nameProperty.link( name => {
+      debugger;
       text.text = name;
     } );
 

```


To test follow @samreids steps above, but make sure to open the dev tools in studio before pressing "preview sim". The you should get 3 debugger pauses for each screen starting up (one in link and two updateLayouts), and then the 7th pause is inside the nameProperty link while setting state after startup. Note that when that function has been called, the text.text is already set to the new value. This is because the text.textProperty.targetProperty is also instrumented for PhET-iO. That isn't obviously a problem, but something to note. 

Another note is that I confirmed that even though that nameProperty link isn't changing the value, the updateLayout function is still being called afterward.

Next I wanted to note that after getting into the above buggy state (clearly caused by something in the PhET-iO state setting life cycle), I can force a re-layout that fixes the problem with this line in the console:

```
phet.phetio.phetioEngine.phetioObjectMap['gravityAndOrbits.general.view.navigationBar.modelScreenButton.text.textProperty'].value +='fdsa';
```

@jonathanolson @samreid any thoughts on this? I can't really take this much further.

**Comment by zepumph** [comment] 2021-07-07 18:28
> It gets rid of the delay, 

@jonathanolson said this in https://github.com/phetsims/joist/issues/725#issuecomment-875011127. I thought that it actually forces the delay, because the boundsProperty is only updated lazily, on updateDisplay. On paper that seems like the right thing, and similar to kicking things off to the next tick. It isn't clear to me why pushing updateLayout back to the next `updateDisplay` call still isn't late enough.


I took a wild guess and changed the boundsProperty link to be based on the textProperty link instead, and it actually fixed the bug. My best guess as to why is because text.textProperty, although it isn't instrumented as a `TinyForwardingProperty`, is tied to an instrumented Property, and so it get's a listener called to updateLayout during the undefer-and-notifiy step of the state engine. 

@jonathanolson please review.

It's not totally clear to me if there are problems with the home screen buttons currently, but perhaps this same pattern can be used there?

**Comment by samreid** [comment] 2021-07-08 14:25
The `textProperty` listener looks good to me, and works properly in my testing.  Likewise, the commit earlier in this thread to HomeScreenButton.js seems to be working correctly for the home screen button problem.

**Comment by zepumph** [comment] 2021-07-08 14:32
Are you ready to continue with cherry picking our sims, and we can keep this open for a final review by @jonathanolson?

**Comment by samreid** [comment] 2021-07-08 14:51
If @jonathanolson can review sometime today, then I think we should wait before cherry picking.  Also, @zepumph or @jonathanolson can you please review https://github.com/phetsims/joist/commit/58fd74142ca8144982ecc13df4abeab6fa946280 and comment?

**Comment by jonathanolson** [comment] 2021-07-08 16:02
I've been investigating, I'm reviewing, and I want to have a better understanding of what was causing the original problem (for the future).

I'm fine with whatever is decided to be cherry-picked.

**Comment by zepumph** [comment] 2021-07-08 17:07
>I'm fine with whatever is decided to be cherry-picked.

@jonathanolson confirmed this in person today during PhET-iO meeting. 

After further discussion, we feel like giving @jonathanolson the rest of this week to investigate, instead of immediately proceeding with potential work-arounds, feels best. We will hopefully cherrypick on Monday!

**Comment by jonathanolson** [comment] 2021-07-10 02:35
FYI I've tracked this down to a quite subtle unexpected behavior, where a specific combination of actions and a yet-as-of-unapplied maxWidth is breaking layout containers. I'll have more details soon.

**Comment by jonathanolson** [comment] 2021-07-10 04:28
Apologies about the time this took to properly track down! So it turns out that our normal usage of `maxWidth` kind of avoids what was a core bug, but the deferred Property state setting ended up triggering it.

Long story short, code-paths with the following exhibited buggy behavior with maxWidth/maxHeight:

1. Set a maxWidth/maxHeight on a Node that's already constructed
2. Trigger bounds validation
3. Adjust the Node's localBounds so that the scale needs to be adjusted
4. Trigger bounds validation once
5. Have a listener that triggers based on this (e.g. bounds) that triggers another modification of localBounds

It turns out that stuffing a maxWidth'ed node in a VBox, then changing the node's content seems to be a perfect trigger for this.

This particular case resulted in the single bounds-validation causing a buggy maxWidth handling, resulting in the centerX of the navbar text being set based on incorrect information (which is then corrected with future operations).

This was caused by the refactoring to use TinyStaticProperty for Node bounds, specifically localBoundsProperty. It caused a new path of re-entrance in validateBounds (`this.localBoundsProperty.notifyListeners( oldLocalBounds );` calls a `get()` which calls `validateBounds()`). We should probably vet all of these potential re-entrance locations again. When the re-entrant call to validateBounds() runs this same logic, they run in the reverse order, with the second one running with STALE values.

I also noticed and fixed a case where setting maxWidth triggers a listener that changes the maxWidth could result in buggy behavior.

@zepumph can you review https://github.com/phetsims/scenery/commit/f0adaceb9b2d8f0420258c1dc65bb94def77c1bd, or we could discuss together?

**Comment by jonathanolson** [comment] 2021-07-10 04:29
Also, as this is probably important, we should :

- [ ] Review re-entrancy in `validateBounds()` based on the Property changes

to see if there are any other bugs of this class.

**Comment by jonathanolson** [comment] 2021-07-10 04:35
For the joist changes, I stripped out the now-unneeded wrapping nodes, removed the explicit `resize:true` and `updateLayout()` parts that are superfluous now. I added dynamic centering of the navbar icons, so that they don't have to maintain the exact same bounds after construction. We were also setting a `maxWidth` on the icon dynamically later, so I added the explicit dependency of updateLayout() on `iconAndText.bounds`.

**Comment by jonathanolson** [comment] 2021-07-10 04:36
Also setting maxWidth on the icon feels buggy (https://github.com/phetsims/joist/blob/master/js/NavigationBarScreenButton.js#L200), as we don't resize the things that depend on its bounds (https://github.com/phetsims/joist/blob/master/js/NavigationBarScreenButton.js#L80). It seems like an unused code-path now that we force a minimum size and specific aspect ratio.

**Comment by jonathanolson** [comment] 2021-07-10 04:51
Reentrancy cases with notification should work fine, but I added warnings in the commit above where it's very unlikely code should be added in certain locations.

**Comment by zepumph** [comment] 2021-07-12 19:04
I asked for a bit of code comment in https://github.com/phetsims/scenery/commit/f0adaceb9b2d8f0420258c1dc65bb94def77c1bd, which feels optional since you have warnings at the end, but still if something comes to you.

I also would recommend writing a test, if possible, that demonstrates this bug. If for no other reason to help document this investigation and bug fix for future scenery maintainers.

**Comment by zepumph** [comment] 2021-07-13 16:45
https://github.com/phetsims/joist/issues/725#issuecomment-878520708 mentioned a few light pieces of cleanup, but nothing that should hold up publication of NS. @jonathanolson can we remove the blocking label and can you list the commits needed for cherry-pick?

**Comment by pixelzoom** [comment] 2021-07-13 17:09
I'm not a fan of partially cherry-picking issues, just to get the non-blocking bits.  It has the potential to create confusion in the future, about what commits were and were not included in the release branch. And what if something additional is discovered when writing unit tests?  

There are other things currently holding up NS 1.4, and the next RC probably won't happen until next week. So rather than cherry-picking what's been done so far, I'd be interested in hearing whether @jonathanolson can wrap up the remaining work by the end of the week.

**Comment by zepumph** [comment] 2021-07-13 17:17
I agree and understand. The only reason that I recommended that is because the only code left to write are unit tests.

**Comment by jonathanolson** [comment] 2021-07-13 17:29
Removed blocking labels.

**Comment by jonathanolson** [comment] 2021-07-13 17:31
> I also would recommend writing a test, if possible, that demonstrates this bug. If for no other reason to help document this investigation and bug fix for future scenery maintainers.

I'd be inclined personally to not go back and write the test, because this is exceedingly unlikely to break in the same way in the future. @zepumph objections?

> list the commits needed for cherry-pick?

Highly depends on where branches are at, these are the relevant commits I made more recently. Work was done throughout time however.

https://github.com/phetsims/scenery/commit/f0adaceb9b2d8f0420258c1dc65bb94def77c1bd
https://github.com/phetsims/joist/commit/33aab76edf4019b34a23ace105389ae787c251a3

@pixelzoom is there anything you need from me on this?

**Comment by pixelzoom** [comment] 2021-07-13 17:36
> @pixelzoom is there anything you need from me on this?

Yes. I need the exact set of cherry-picks needed to patch NS 1.4.

**Comment by samreid** [comment] 2021-07-13 17:37
I'll work on that for gravity and orbits, it should be the same for NS.  I'm just planning to cherry-pick all commits from this issue.

**Comment by samreid** [comment] 2021-07-13 18:08
I cherry picked as described above and testing worked well.  Over to @pixelzoom to cherry-pick for Natural Selection (I still have this problem which makes it difficult to help in this case https://github.com/phetsims/natural-selection/issues/298#issuecomment-875003109 )

**Comment by pixelzoom** [comment] 2021-07-13 18:27
Shas to cherry-pick are noted in https://github.com/phetsims/natural-selection/issues/295#issuecomment-879305525.  I'll continue patching NS 1.4 in that issue. Unassigning from this issue.

**Comment by zepumph** [comment] 2021-07-13 20:18
>I'd be inclined personally to not go back and write the test, because this is exceedingly unlikely to break in the same way in the future. @zepumph objections?

Sounds good to me!

I think this issue is ready to close, as cherry-pick issues are in their own repos.

**Closed by zepumph** 2021-07-13 20:18 UTC
Labels: dev:phet-io, status:ready-for-review, type:bug
