### ISSUE TITLE
incorrect scaling of Dialogs

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/joist#586] opened 2019-12-03 22:30 UTC
While working on Natural Selection, I noticed that Dialogs seem to be getting scaled.  And they are getting scaled _up_, which is generally bad.

Below is a screenshot to demonstrate.  `'Play Again'` and `'All of the bunnies have died'` are both using `PhetFont( 16 )`.   But the text in the Dialog appears to be significantly larger.

<img width="980" alt="screenshot_07" src="https://user-images.githubusercontent.com/3046552/70094661-430cee80-15e0-11ea-8dcc-f493485fa369.png">

The problem was introduced for in https://github.com/phetsims/joist/commit/5f66e57cd03c1b5703680f430604c28a26706394 for #219 by @samreid on 2/17/15.  

Line 132 of Sim.js is the culprit:

```js
132 self.topLayer.setScaleMagnitude( scale );
```

If I remove that line, then font sizes are consistent. (I don't know if anything else gets messed up.) E.g.:

<img width="978" alt="screenshot_08" src="https://user-images.githubusercontent.com/3046552/70095205-671cff80-15e1-11ea-8651-81882a53d2ec.png">

I'm not sure how to proceed here. Concerns:

(1) Were any dialogs messed up (by new scaling behavior) when this change was made? 
(2) How can we revert this incorrect Dialog scaling? 
(3) How do we identify and adjust dialogs that are compensating for incorrect scaling?

Assigning to @ariel-phet for prioritization and assignment, and labeling for developer meeting discussion.  In the meantime, I'll compensate by using a smaller (incorrect) font size in Natural Selection.

**Comment by pixelzoom** [comment] 2019-12-03 22:36
In the first screenshot shown in https://github.com/phetsims/joist/issues/586#issue-532310674, here are specifics of text height in the global coordinate frame:

"Play Again" => 17
"All of the bunnies have died" => 21.7

So the dialog in this case is being scaled up by ~28%.

**Comment by samreid** [comment] 2019-12-03 23:59
I commented out line 132 and used CMD+ to take this screenshot:

![image](https://user-images.githubusercontent.com/679486/70099986-a6e9e400-15ed-11ea-88e4-364a7ef38eeb.png)

Then I used CMD- to take this screenshot:
![image](https://user-images.githubusercontent.com/679486/70099997-b49f6980-15ed-11ea-8c51-5cb32bc22b51.png)

Note the tiny dialog in the top left.  I don't recall all of the details from https://github.com/phetsims/joist/issues/219 but it seems this change was to avoid the problem noted in https://github.com/phetsims/joist/issues/218 where the phet menu size is a function of browser zoom.

Hopefully we can find a way to apply the same scaling strategy to the `topLayer` as is used for the rest of the sim content (may need to deal with the fact that the sim scaling strategy probably subtracts the height of the navigation bar and the topLayer does not.)

**Comment by pixelzoom** [comment] 2019-12-04 00:46
> Then I used CMD- to take this screenshot: ... Note the tiny dialog in the top left.

What did you do before taking this screenshot to result in the tiny dialog?

**Comment by samreid** [comment] 2019-12-04 00:49
I held down the command key and pressed the minus button  several times to change the browser zoom level before taking the screenshot.

**Comment by pixelzoom** [comment] 2019-12-04 00:52
Thanks for clarifying.  I didn't grok that you were using the browser's zoom in/out feature. And I reproduced what you described.

**Comment by samreid** [comment] 2019-12-04 15:13
It looks like the same strategy is used for scaling screen content and the topLayer, which contains dialogs.  However, the value used for scaling screen content is
ScreenView.DEFAULT_LAYOUT_BOUNDS = Bounds2 {minX: 0, minY: 0, maxX: 1024, maxY: 618}

Whereas the value used for scaling the topLayer which contains dialogs is: 
HomeScreenView.LAYOUT_BOUNDS = Bounds2 {minX: 0, minY: 0, maxX: 768, maxY: 504}

Perhaps this was set up because we wanted dialogs to be centered on the full screen rather than above the navigation bar?  But that doesn't explain the difference in maxX.

@pixelzoom if you change Sim.js line 117 to use ScreenView.DEFAULT_LAYOUT_BOUNDS, does the problem go away?

```js
117: const scale = Math.min( width / HomeScreenView.LAYOUT_BOUNDS.width, height / HomeScreenView.LAYOUT_BOUNDS.height );
```

**Comment by pixelzoom** [comment] 2019-12-04 15:46
> @pixelzoom if you change Sim.js line 117 to use ScreenView.DEFAULT_LAYOUT_BOUNDS, does the problem go away?

Yes.

If you want to confirm with Natural Selection (by pressing the "Play Again" button), you'll also need to make this change in `NaturalSelectionConstants`:

```
- DIALOG_CONTENT_SCALE: 0.75, //TODO to compensate for https://github.com/phetsims/joist/issues/586
+ DIALOG_CONTENT_SCALE: 1, //TODO to compensate for https://github.com/phetsims/joist/issues/586
```

**Comment by jessegreenberg** [comment] 2020-03-12 19:13
From developer meeting 3/12/20 - @ariel-phet we need a developer to investigate a solution for this, can you please assign someone to do so?

**Comment by pixelzoom** [comment] 2020-03-23 16:30
Consensus at 3/12/20 dev meeting is that this should be done sooner, rather than later.  Otherwise we're continuing to make design decisions about dialogs based on incorrect scaling. 

Here's what needs to be done:

- [ ] Identify the cause of the problem (see clues above).
- [ ] Correct the problem.
- [ ] Identify and adjust dialogs that are compensating for incorrect scaling.

**Comment by pixelzoom** [comment] 2020-03-23 17:28
@ariel-phet and I discussed this via Zoom.  This doesn't impact the UX, so can't be a priority right now, so it will remain unassigned.   In the meantime, developers should be made aware of this problem, and should use a workaround like the one that I've used in Natural Selection. E.g.:

```js
new Dialog( content, {
  scale: HomeScreenView.LAYOUT_BOUNDS.width / ScreenView.DEFAULT_LAYOUT_BOUNDS.width
} );
```

This will be a high-priority PSA for developer meeting.

**Comment by jbphet** [comment] 2020-03-26 18:06
Discussed in the 3/26/2020 dev meeting, and we decided to address a couple of specific cases with the recommended workarounds and defer the larger fix for a couple of months.

**Comment by pixelzoom** [comment] 2020-03-31 01:43
Assigned to me because I'm supposed to add a calendar reminder for "a couple of months" from now. I've added a "Future Reminders" section at the top of the developer meeting document, and included this issue there.

**Comment by mattpen** [comment] 2020-05-28 18:58
Dev Meeting: @pixelzoom and @SaurabhTotey will take a look and report back at the next dev meeting.

**Comment by pixelzoom** [comment] 2020-06-04 15:13
@SaurabhTotey sorry I haven't gotten in touch with you about this. I've been busy with other higher-priority issues.

**Comment by pixelzoom** [comment] 2020-07-10 21:37
We suspect that this may be the cause (or related to) incorrect scaling of the About dialog in https://github.com/phetsims/ph-scale/issues/168.   So labeling this issue as "block publication".

This issue requires a bigger commitment than I've had time for.  So assigning to @ariel-phet for reassignment.  I recommend tracking down whoever last worked on Dialog scaling and have them work on addressing this issue and https://github.com/phetsims/ph-scale/issues/168.

**Comment by ariel-phet** [comment] 2020-07-15 19:55
Marking for some discussion at developer meeting, but not a blocking issue.

**Comment by samreid** [comment] 2020-07-15 21:21
@jonathanolson and I reviewed this today and have a recommendation for how to proceed.  

* Eliminate the `setScaleMagnitude` from `topLayer` in Sim.js.  That was too inflexible, and leads to awkward layout code that has to invert the scale for positioning things.
* Use the same pattern as `ScreenView.layout` for laying out popups.  Each popup can have its own layout function.  Dialog's default function can be to center in the area above the navigation bar.
* Change Dialog from `extends Panel` to `extends Node` so it can have `maxWidth` and `setScaleMagnitude` set at different levels, so they don't interfere.

Here's our patch so far that we tested in natural selection with and without a large "credits" section, which implements those steps:

<details>

```diff

Index: main/joist/js/Sim.js
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- main/joist/js/Sim.js	(revision a47d8e328dbe550277d86bb46a09b1c7a6af759a)
+++ main/joist/js/Sim.js	(date 1594847593504)
@@ -179,9 +179,12 @@
 
     // Layout each of the screens
     _.each( self.screens, m => m.view.layout( width, screenHeight ) );
+    self.topLayer.children.forEach( child => {
+      child.layoutFromSim && child.layoutFromSim( width, screenHeight );
+    } );
 
     // Resize the layer with all of the dialogs, etc.
-    self.topLayer.setScaleMagnitude( scale );
+    // self.topLayer.setScaleMagnitude( scale );
 
     // Fixes problems where the div would be way off center on iOS7
     if ( platform.mobileSafari ) {
Index: main/sun/js/Dialog.js
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- main/sun/js/Dialog.js	(revision 3098801503ccb1c1e7dd97ab5775fb08c1b99f82)
+++ main/sun/js/Dialog.js	(date 1594847593514)
@@ -11,6 +11,7 @@
 
 import BooleanProperty from '../../axon/js/BooleanProperty.js';
 import Property from '../../axon/js/Property.js';
+import ScreenView from '../../joist/js/ScreenView.js';
 import Shape from '../../kite/js/Shape.js';
 import inherit from '../../phet-core/js/inherit.js';
 import merge from '../../phet-core/js/merge.js';
@@ -32,6 +33,7 @@
 import RectangularPushButton from './buttons/RectangularPushButton.js';
 import DialogIO from './DialogIO.js';
 import Panel from './Panel.js';
+import Node from '../../scenery/js/nodes/Node.js';
 import sun from './sun.js';
 import sunStrings from './sunStrings.js';
 
@@ -119,14 +121,20 @@
     // {function|null} called after the dialog is hidden, see https://github.com/phetsims/joist/issues/478
     hideCallback: null,
 
+    //
+    contentsOptions: {
+      maxHeight: ScreenView.DEFAULT_LAYOUT_BOUNDS.height,
+      maxWidth: ScreenView.DEFAULT_LAYOUT_BOUNDS.width
+    },
+
     // pass through to Panel options
     cornerRadius: 10, // {number} radius of the dialog's corners
     resize: true, // {boolean} whether to resize if content's size changes
     fill: 'white', // {string|Color}
     stroke: 'black', // {string|Color}
     backgroundPickable: true,
-    maxHeight: null, // if not provided, then dynamically calculate based on the layoutBounds of the current screen, see updateLayoutMultilink
-    maxWidth: null, // if not provided, then dynamically calculate based on the layoutBounds of the current screen, see updateLayoutMultilink
+    // maxHeight: null, // if not provided, then dynamically calculate based on the layoutBounds of the current screen, see updateLayoutMultilink
+    // maxWidth: null, // if not provided, then dynamically calculate based on the layoutBounds of the current screen, see updateLayoutMultilink
     tandem: Tandem.OPTIONAL,
     phetioType: DialogIO,
     phetioReadOnly: PhetioObject.DEFAULT_OPTIONS.phetioReadOnly, // default to false so it can pass it through to the close button
@@ -148,6 +156,9 @@
     addAriaLabelledByFromTitle: true
   }, options );
 
+  assert && assert( !options.hasOwnProperty( 'maxWidth' ) );
+  assert && assert( !options.hasOwnProperty( 'maxHeight' ) );
+
   // by default, copy the state of the dialog
   PhetioObject.mergePhetioComponentOptions( {
     phetioState: options.phetioState
@@ -158,6 +169,8 @@
   assert && assert( options.yMargin === undefined, 'Dialog sets yMargin' );
   options.yMargin = 0;
 
+  this.layoutBounds = ScreenView.DEFAULT_LAYOUT_BOUNDS;
+
   // if left margin is specified in options, use it. otherwise, set it to make the left right gutters symmetrical
   if ( options.leftMargin === null ) {
     options.leftMargin = options.xSpacing + CLOSE_BUTTON_WIDTH + options.closeButtonRightMargin;
@@ -210,13 +223,13 @@
     }
   } );
 
-  assert && assert( options.maxHeight === null || typeof options.maxHeight === 'number' );
-  assert && assert( options.maxWidth === null || typeof options.maxWidth === 'number' );
+  // assert && assert( options.maxHeight === null || typeof options.maxHeight === 'number' );
+  // assert && assert( options.maxWidth === null || typeof options.maxWidth === 'number' );
 
   // keep track of if maxWidth and maxHeight were supplied by the client, because the default approach dynamically
   // updates them based on the current screens layoutBounds.
-  const suppliedMaxHeight = !!options.maxHeight;
-  const suppliedMaxWidth = !!options.maxWidth;
+  const suppliedMaxHeight = !!options.contentsOptions.maxHeight;
+  const suppliedMaxWidth = !!options.contentsOptions.maxWidth;
 
   // create close button
   const closeButton = new CloseButton( {
@@ -289,13 +302,14 @@
   } );
 
   // create content for Panel
-  const dialogContent = new HBox( {
+  const dialogContent = new HBox( merge( {
     children: [ contentAndTitleWithMargins, closeButtonWithMargins ],
     spacing: options.xSpacing,
     align: 'top'
-  } );
+  }, options.contentsOptions ) );
 
-  Panel.call( this, dialogContent, options );
+  const panel = new Panel( dialogContent, options );
+  Node.call( this, merge( { children: [ panel ] }, options ) );
 
   const sim = window.phet.joist.sim;
 
@@ -395,7 +409,7 @@
 
 sun.register( 'Dialog', Dialog );
 
-inherit( Panel, Dialog, {
+inherit( Node, Dialog, {
 
   /**
    * @public
@@ -439,12 +453,47 @@
    */
   focusCloseButton() {
     this.closeButton.focus();
+  },
+
+  /**
+   * Get the scale to use for laying out the sim components and the navigation bar, so its size will track
+   * with the sim size
+   * @param {number} width
+   * @param {number} height
+   * @returns {number}
+   * @public (joist-internal)
+   */
+  getLayoutScale: function( width, height ) {
+    return Math.min( width / this.layoutBounds.width, height / this.layoutBounds.height );
+  },
+
+  layoutFromSim( width, height ) {
+    this.resetTransform();
+
+    const scale = this.getLayoutScale( width, height );
+    this.setScaleMagnitude( scale );
+
+    let dx = 0;
+    let dy = 0;
+
+    //center vertically
+    if ( scale === width / this.layoutBounds.width ) {
+      dy = ( height / scale - this.layoutBounds.height ) / 2;
+    }
+
+    //center horizontally
+    else if ( scale === height / this.layoutBounds.height ) {
+      dx = ( width / scale - this.layoutBounds.width ) / 2;
+    }
+
+    this.translate( dx, dy );
   }
 } );
 
 // @private - Center in the screenBounds (doesn't include the navigation bar)
 Dialog.DEFAULT_LAYOUT_STRATEGY = ( dialog, simBounds, screenBounds, scale ) => {
-  dialog.center = screenBounds.center.times( 1.0 / scale );
+  dialog.setScaleMagnitude( scale );
+  dialog.center = screenBounds.center;
 };
 
 // {function(number,number):number}
Index: main/natural-selection/js/common/view/DiedDialog.js
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- main/natural-selection/js/common/view/DiedDialog.js	(revision dfd4ba88a0cd4d1c532761698ed1a6a5a58f4aae)
+++ main/natural-selection/js/common/view/DiedDialog.js	(date 1594846453959)
@@ -29,7 +29,11 @@
 
     const messageText = new Text( naturalSelectionStrings.allOfTheBunniesHaveDied, {
       font: NaturalSelectionConstants.DIALOG_FONT,
-      maxWidth: 450 // determined empirically
+      contentsOptions:{
+        maxWidth: 450, // determined empirically
+        maxHeight: 300
+      }
+
     } );
 
     super( messageText, options );

```

</details>

Remaining work:

* Implement `layoutFromSim` for the PhetMenu
* Implement `layoutFromSim` for the other popups with custom layout functions (there are 3)
* Make sure sims are passing maxWidth/maxHeight as a Panel option, not as a top-level Dialog option.
* Clean up other implementation details in Dialog
* Sim should assert that items added to `topLayer` have a `layoutFromSim` function.
* The patch still defines and uses `Dialog.layoutFunction`.  That will need to be eliminated.
* Broader testing

**Comment by Denz1994** [comment] 2020-07-16 18:19
From Dev Meeting on 07/16/20:

**Discussion:**
@samreid and @jonathanolson have come up with a plan for remaining work on this issue.

@pixelzoom: This pattern assumes we aren't using non-modal Dialogs.
@samreid: If we need a non-modal dialog we should investigate not using Dialog in those cases.

@brandonLi8: Collision-Lab uses a modal dialog for its keypad, but Unit-Rates and Projectile-Motion both use custom solutions.

**Resolution:** @jonathanolson Will continue working on this issue with the steps outlined above. He will relay to @ariel-phet a time estimate as well.

**Comment by jonathanolson** [comment] 2020-07-28 02:27
It would be good to discuss my above approach with @samreid, as it differs. Specifically, it keeps the code much cleaner (and similar) by calling showPopup on the sim with a wrapper Node that handles the ScreenView-like layout, so that the actual Dialog itself (or other popup content) can be positioned normally based on layoutBounds. This means we can have a varying ScreenView-like transform, while keeping the actual self-transform of the Dialog stable, AND this means if you use the same layoutBounds (or both the default), you can position the dialog relative to view elements easily. I've also isolated a Popupable trait, since we'll probably want to use that behavior with things that aren't panels with specific close buttons.

@samreid, would it be good to schedule a time to review the above approach?

**Comment by pixelzoom** [comment] 2020-07-28 23:54
@jonathanolson Did something get broken here?  Here's natural-selection with `?dev`.  The layoutBounds are no longer centered in the browser window. 

<img width="1494" alt="screenshot_441" src="https://user-images.githubusercontent.com/3046552/88740808-55054980-d0fb-11ea-88fc-171bccc1be3d.png">

**Comment by jonathanolson** [comment] 2020-07-29 01:33
> Did something get broken here?

I believe the fix for that was pushed yesterday, can you verify it's still happening off of master? I wasn't able to reproduce.

**Comment by pixelzoom** [comment] 2020-07-29 02:07
I just ran pull-all.sh, and yes, it's still reproducible in master.

**Comment by jonathanolson** [comment] 2020-07-29 03:45
@pixelzoom can you outline a way to reproduce this, ideally on phettest?

<img width="1343" alt="Screen Shot 2020-07-28 at 9 40 02 PM" src="https://user-images.githubusercontent.com/480878/88754195-4464cb80-d11b-11ea-85e3-1bb2106fcd58.png">
<img width="1680" alt="Screen Shot 2020-07-28 at 9 41 59 PM" src="https://user-images.githubusercontent.com/480878/88754196-462e8f00-d11b-11ea-927b-18abd95aaab9.png">

Using the same query parameters, I'm unable to reproduce. If I revert to a previous commit (instead of HEAD) (https://github.com/phetsims/joist/commit/68c2740e1057fd9b1e3472383373f426fd75e0e8), I'm able to reproduce the exact behavior shown above.

**Comment by samreid** [comment] 2020-07-29 11:56
Pulling master fixed the problem for me.

**Comment by samreid** [comment] 2020-07-29 12:55
I reviewed the changes in Joist as well as the commits in the sun and joist branches and this looks like it is working well.  In particular, I tested:

* The About Dialog shows at the same size on the home screen and the sim screen, and scales properly
* The `visibleBoundsProperty` is updated properly (tested in Bending Light which uses it for layout)

Some questions and ideas for next steps:

* How is the AboutDialog showing at the same size on the home screen (which uses non-default layout bounds) and a sim screen which uses the default layout bounds?
* Should `Sim.showPopup` require that its argument be a `Popupable` instance?  Should we document that `Sim.showPopup` should only be called by `Popupable`?
* PhetMenu is not using `Popupable` yet.
* If we ever have a `Popupable` that is supposed to persist across different screens with different `layoutBounds`, will we need to call `layout` when the screen changes?  Or will we decide this is not a supported feature?
* Possibly for another issue: factor out the code in Sim.js that relates to showing `Popupable`s into a new type like `PopupLayer` which manages its own `topLayer`, `modelNodeStack`, `barrierRectangle`, etc.
* Maybe rename `Popupable` to `Popup`?

I think this is a good direction to proceed, thanks @jonathanolson!

**Comment by pixelzoom** [comment] 2020-07-29 17:10
> @pixelzoom can you outline a way to reproduce this, ideally on phettest?

I was running locally. Must've been cacheing, because it looks OK now.

**Comment by jonathanolson** [comment] 2020-07-29 18:16
> How is the AboutDialog showing at the same size on the home screen (which uses non-default layout bounds) and a sim screen which uses the default layout bounds?

It's a consequence of the above design, where each Dialog has its own (optional technically) layoutBounds.

> Should Sim.showPopup require that its argument be a Popupable instance? Should we document that Sim.showPopup should only be called by Popupable?

showPopup doesn't actually get a reference to the Popupable, just to the parent Node. Furthermore, this seems unnecessary.

> PhetMenu is not using Popupable yet.

Its layout is handled separately (in Sim.js IIRC?), so it doesn't benefit from Popupable.

> If we ever have a Popupable that is supposed to persist across different screens with different layoutBounds, will we need to call layout when the screen changes? Or will we decide this is not a supported feature?

The Dialogs/popups are completely independent of what screen is active.

> Possibly for another issue: factor out the code in Sim.js that relates to showing Popupables into a new type like PopupLayer which manages its own topLayer, modelNodeStack, barrierRectangle, etc.

That sounds potentially beneficial, as essentially we'd want glass-pane handling for each screen, not just the whole sim, right?

> Maybe rename Popupable to Popup?

How are we handling trait/mixin names? I wouldn't want someone to accidentally inherit/extend Popup.

> I think this is a good direction to proceed

I'll proceed unless I hear other comments!

**Comment by jonathanolson** [comment] 2020-07-29 20:17
Pushed changes to master, includes sim changes to be compatible with the new layout (e.g. now the layoutStrategy won't NEED to handle scale/transform information, and can just position things in the same coordinate frame).

@ariel-phet, we'll likely want to adjust the About dialog sizing (or other dialogs), since they are now "matching" the default layout bounds behavior. What should be done to the behavior in master, or is the size acceptable?

**Comment by pixelzoom** [comment] 2020-07-29 20:28
> What should be done to the behavior in master, or is the size acceptable?

For Natural Selection and Collision Lab, search for "TODO https://github.com/phetsims/joist/issues/586".  

For AboutDialog, search for "TODO https://github.com/phetsims/joist/issues/586".

**Comment by pixelzoom** [comment] 2020-07-29 20:33
I'll take care of Natural Selection.

**Comment by pixelzoom** [comment] 2020-07-29 20:45
Searching for "import Dialog from"...

Common-code Dialogs:

- [ ] joist.AboutDialog
- [ ] joist.OptionsDialog
- [ ] joist.KeyboardHelpDialog
- [ ] joist.UpdateDialog
- [ ] vegas.RewardDialog
- [ ] scenery-phet.OopsDialog
- [ ] scenery-phet.ContextLossFailureDialog

Then there are sim-specific dialogs in:

- [ ] build-a-molecule
- [ ] collision-lab
- [ ] curve-fitting
- [ ] equality-explorer
- [ ] gene-expression
- [ ] make-a-ten
- [ ] masses-and-springs
- [ ] models-of-the-hydrogen-atom
- [ ] molecules-and-light
- [ ] pendulum-lab
- [ ] plinko-probability

I recommend that we:
*  address the common-code dialogs with high priority
* create issues for sim-specific dialogs, assigned to responsible developer

**Comment by pixelzoom** [comment] 2020-07-30 16:42
My sims are done.

Since my sims are the only clients of OopsDialog, I took care of that one. They all look fine, no changes to OopsDialog are needed.

**Comment by zepumph** [comment] 2020-07-30 17:42
Today during the PhET-iO meeting, we reviewed this work and saw that the PhetMenu also seems to have this problem.

**Comment by jonathanolson** [comment] 2020-07-30 17:49
> Today during the PhET-iO meeting, we reviewed this work and saw that the PhetMenu also seems to have this problem.

Restored scaling for the phet menu in the above commit.

**Comment by pixelzoom** [comment] 2020-07-30 18:11
I took care of RewardDialog, tested in equality-explorer and make-a-ten.  Font sizes and spacing were increased by ~1.3x.

**Comment by pixelzoom** [comment] 2020-07-30 19:35
In fd18e1c, I've adjusted OptionsDialog to account for the rescaling.  I did not increase the title ("Options") font size, since it already looks great to me, and formerly looked too big.

**Comment by pixelzoom** [comment] 2020-07-30 19:48
@jonathanolson would you mind handling UpdateDialog and UpdateNode? I don't know how to easily reproduce all of the cases, and there's `option.big` in UpdateNode that complicates things -- `big: false` is apparently used in AboutDialog, and it's unclear yet whether the AboutDialog will change.

**Comment by pixelzoom** [comment] 2020-07-30 20:54
In the above commit, I made a first pass at adjusting AboutDialog.  To be reviewed with @ariel-phet.

**Comment by pixelzoom** [comment] 2020-07-30 21:37
@ariel-phet and I reviews AboutDialog via Zoom, and it has been approved.  The goal was not to make it pixel-identical to how it looked before Dialog rescaling.  The goal was to polish and make it look good.

**Comment by jbphet** [comment] 2020-07-31 20:13
The scaling of the Options dialog looks good to me, and should be fine for the upcoming RC of States of Matter and its derivatives.

**Comment by jonathanolson** [comment] 2020-07-31 21:02
The UpdateDialog and uses of the UpdateNode look like they're at a great scale to me.

**Comment by chrisklus** [comment] 2020-08-06 18:37
From 8/6/20 dev meeting:

All common code parts are taken care of, so we're going to leave this open as a chip-away for sim-specific cases.

**Comment by ariel-phet** [comment] 2020-08-06 18:38
@ariel-phet will make a new chip-away issue with the remaining work.

**Comment by ariel-phet** [comment] 2020-08-06 18:58
Taking remaining work in https://github.com/phetsims/joist/issues/586#issuecomment-665917564 and moving to a new issue as this one has gotten impressively long. Closing

https://github.com/phetsims/joist/issues/650

**Closed by ariel-phet** 2020-08-06 18:58 UTC
Labels: dev:chip-away
