### ISSUE TITLE
some sims are briefly unresponsive after computer has been idle (Safari)

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/joist#140] opened 2014-07-22 22:00 UTC
Affected platform: Mac OS with Safari 7 or 8-beta

To reproduce:
1. run a sim
2. interact with the sim
3. don't touch your computer for at least 3 minutes
4. resume interacting with the sim

When you do step 4, the sim will be unresponsive for a few seconds. This is a concern because students may not touch their computer for a few minutes while listening to the teacher. And when they resume work with the sim, this interrupts the activity and is disconcerting.

This was first reported in https://github.com/phetsims/graphing-lines/issues/42, but has been demonstrated with other sims. It occurs on Mac OS with Safari 7 and 8-beta.  It does NOT occur with all sims, or with Safari on iOS, or with Chrome or Firefox on Mac OS.

See the above issue for details on discussion and prior investigation.

**Comment by jessegreenberg** [comment] 2017-05-01 16:57
Reopening.  There is a bug with VoiceOver in Safari that causes the virtual cursor to move to the heartbeat div when the innerHTML changes.  Found in phetsims/john-travoltage#235.

Adding ```hidden``` to the div seems to fix the problem.  But maybe the heartbeat div is not necessary any more.  I will try removing the div and will see if the problem is still there on PhET's supported iOS/macOS devices.

**Comment by jessegreenberg** [comment] 2017-05-01 17:16
Supported apple products as of 5/1/17

- [ ] iOS 9.3.5 + Safari
- [ ] iOS 10.0.1 + Safari
- [ ] MacOS 10.9.5 + Safari
- [ ] MacOS 10.10.5 + Safari
- [ ] MacOS 10.11.6 + Safari
- [ ] MacOS 10.12 + Safari

A check means it was tested without the heartbeat div and did not exhibit this issue.

**Comment by jessegreenberg** [comment] 2017-05-01 17:34
This is still a problem in MacOS 10.12.5 beta fora  build version of graphing-lines.  So the element cannot be removed.  What if we add ```hidden``` to it?

**Comment by jessegreenberg** [comment] 2017-05-01 17:45
When ```hidden``` is added the bug is still there, tested in build version of graphing lines.

**Comment by samreid** [comment] 2017-05-01 17:47
Sanity check: test on MacOS 10.12.5 beta with the heartbeat div but without hidden and confirm the sim doesn't fall asleep. (maybe they worked around our hack).

**Comment by jessegreenberg** [comment] 2017-05-01 17:53
Good idea, just tried a built version of graphing-lines on 10.12.5 beta and this issue is not there, so the heartbeat div is still working as intended.

**Comment by jessegreenberg** [comment] 2017-05-01 17:54
```tabindex=-1``` might also prevent virtual focus from moving to this element?

**Comment by jessegreenberg** [comment] 2017-05-01 18:03
Problem is still there with tabindex="-1".  When the heartbeat div looks like

```html
<div aria-hidden="true" tabindex="-1" style="opacity: 0; position: absolute; left: 0px; top: 0px; width: 0px; height: 0px; clip: rect(0px, 0px, 0px, 0px);">0.007566062897769732</div>
```

The virtual cursor will move onto the number.

**Comment by jessegreenberg** [comment] 2017-05-01 18:13
When a child of the sim div instead of the body, VoiceOver + Safari no longer has a problem with virtual focus.  Can we move the heartbeat div into the body? I'll test to make sure it works under the sim div.

**Comment by jessegreenberg** [comment] 2017-05-01 18:27
When in the body, the heartbeat div is working as desired.  I will now test with this change since it works with VoiceOver too.

Supported Apple platforms as of 5/1/17

 - [ ] iOS 9.3.5 + Safari
 - [ ] iOS 10.0.1 + Safari
 - [ ] MacOS 10.9.5 + Safari
 - [ ] MacOS 10.10.5 + Safari
 - [ ] MacOS 10.11.6 + Safari
 - [ ] MacOS 10.12 + Safari

A check means it was tested without the heartbeat div moved under the sim div, and the sim did not exhibit any freezing.

**Comment by jonathanolson** [comment] 2017-05-01 18:56
Sounds like a nice solution.

**Comment by jessegreenberg** [comment] 2017-05-01 19:15
I tested on the checked platforms above, couldn't locate the other devices. But this seems very safe.  Given @jonathanolson's comment https://github.com/phetsims/joist/issues/140#issuecomment-298402353 I am going to add some documentation and close.

**Comment by jessegreenberg** [comment] 2017-05-01 19:52
Done in the above commit, closing again.

**Comment by jessegreenberg** [comment] 2019-06-04 22:56
This bug or something very much like it has come back.  At first we weren't able to produce the bug anywhere other than ohms-law but I think it is because we weren't waiting long enough. Verified on master of ohms-law, resistance-in-a-wire, and gravity-force-lab-basics. @KatieWoe reported that this does not happen in published resistance-in-a-wire. Here was the initial report: https://github.com/phetsims/ohms-law/issues/146.

For initial debugging notes, see in particular https://github.com/phetsims/ohms-law/issues/146#issuecomment-497524254

I tried to debug remotely through remote access of one to one of the Mac testing devices but @KatieWoe and I found that screen sharing that way prevented this bug from happening at all.

Sims found with this bug so far have all had a11y enabled. @KatieWoe can we verify this happens in a non-a11y sim? Like https://phet-dev.colorado.edu/html/blackbody-spectrum/1.0.0-rc.1/phet/blackbody-spectrum_all_phet.html?

**Comment by jessegreenberg** [comment] 2019-06-04 22:58
I am assuming this blocks publication, adding label.

**Comment by samreid** [comment] 2019-06-04 23:15
I tested Ohm's Law master/requirejs on Mac Safari Version 12.1 (14607.1.40.1.4) running Mac OS 10.14.4.  I used the sim for 10 seconds, then set a timer for 2 minutes and waited.  After 2 minutes, I resume usage and there was no pause and the sim continued normally.

**Comment by jessegreenberg** [comment] 2019-06-05 00:10
Thanks @samreid. @KatieWoe initially reported this again on Mac 10.14.5 Safari 12.1.1 and @jbphet saw this on OSX version 10.10.5, Safari version 10.1.2

**Comment by jessegreenberg** [comment] 2019-06-05 00:16
@samreid suggested taking a look at the developer tool "timeline" in Safari to get any clues as to where time is being spent, @KatieWoe if you have time for this we could try to get that info together.

**Comment by KatieWoe** [comment] 2019-06-05 15:29
Was not able to reproduce on blackbody spectrum.  Either the rc or on master.

**Comment by jessegreenberg** [comment] 2019-06-05 16:44
@KatieWoe and I met to try get information out of the developer tool "timeline" but we could not see the bug when the developer tools were open. Here is a summary in order of what we tried, all tests were with blackbody-spectrum off of master.

- We tried without a11y and did not see the problem
- We tried with a11y and did see the problem
- We tried again with a11y again and did see the problem
- We tried with a11y while dev tools were recording and did not see the problem
- We tried again with a11y while dev tools were recording and did not see the problem
- We then tried with a11y without the dev tools open and did not see the problem
- We tried with a11y after reloading the sim and did see the problem, but the delay was only about 1 second
- We tried with a11y while using the "timeline" after reloading the sim and did not see the problem

After the first three tests, we thought that that this indicated a11y was the cause. But the following tests make this seem random.

**Comment by jessegreenberg** [comment] 2019-06-05 16:47
Adding developer meeting label in case anyone else has ideas for what to try next.

Also assigning to @ariel-phet so he is aware of this issue and to confirm that this is a priority that needs to be worked on further.

**Comment by jonathanolson** [comment] 2019-06-05 18:04
Does the "classic" style heartbeat div fix the issue?

**Comment by jbphet** [comment] 2019-06-06 18:49
This sounds a bit like the delays that we were seeing in https://github.com/phetsims/scenery/issues/621. @samreid will check to see if this is related.

**Comment by jbphet** [comment] 2019-06-06 18:52
@jessegreenberg - @jonathanolson and I have a couple of suggestions above, and we discussed in dev meeting and no other immediate ideas came up.  Back to you for now.

**Comment by samreid** [comment] 2019-06-06 18:53
I set to integrated graphics card and was still not able to reproduce the problem.

**Comment by jessegreenberg** [comment] 2019-06-14 02:24
Thanks for reviewing all. I am able to see this issue on a macOS Mojave 10.14.5 at https://phet-dev.colorado.edu/html/ohms-law/1.4.0-rc.3/phet/ohms-law_en_phet.html. I will try the "classic" heartbeat div recommended in https://github.com/phetsims/joist/issues/140#issuecomment-499192420.

**Comment by jessegreenberg** [comment] 2019-06-14 03:49
I am able to see this very consistently with ?a11y enabled and I am never able to see this without it, so I am pretty convinced this is caused by a11y somehow. I confirmed that even with a11y enabled the problem does not happen when recording with the "Timelines" Safari tool.

**Comment by jessegreenberg** [comment] 2019-06-14 19:57
I found two ways to fix this issue in AccessibleSiblingStyle.js: Add `z-index: -1` to the PDOM root, or position elements of the PDOM with `absolute` rather than `fixed`. Both changes work with desktop and mobile screen readers. I don't understand what is happening here yet. Putting z-index=1 on the heartbeat div does not solve the problem.

But `fixed` does not seem like the correct portioning attribute anyway, so I am going to make the change to absolute.

**Comment by jessegreenberg** [comment] 2019-06-14 20:44
I asked @KatieWoe to try to produce the bug with this version with the fix and she could not: https://phet-dev.colorado.edu/html/ohms-law/1.5.0-dev.3/phet/ohms-law_en_phet.html. This issue is fixed again, closing.

**Comment by jessegreenberg** [comment] 2019-06-16 22:27
Reopening. https://github.com/phetsims/scenery/issues/981 identifies why 'fixed' positioning is important for a11y, PDOM elements are positioned relative to the viewport. So we either need to go with the `z-index` workaround or change the way PDOM elements are positioned.

I am going with the z-index solution for now, I don't think it is worth changing our approach since this workaround is available and reasonable.

**Comment by jessegreenberg** [comment] 2019-06-17 17:20
I verified several times on macOS 10.14.5 that this is fixed.

**Closed by jessegreenberg** 2019-06-17 17:20 UTC
Labels: priority:2-high, type:bug
