### ISSUE TITLE
update feature for HTML5 sims

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/joist#189] opened 2015-01-01 23:46 UTC
This feature was originally requested in https://github.com/phetsims/chipper/issues/76.

@oliver-phet wrote:
> Currently, if a user runs a .jar file of a sim they downloaded and we have published an update to that sim, the sim will check to see if there is a more recent version available and prompt the user. We would like this behavior added to HTML5 downloaded sims.

**Comment by pixelzoom** [comment] 2015-01-01 23:58
For Java sims, this was a large feature. A server-side component provides information about the latest version number. The client-side implementation includes: prompting the user, handling download of the latest version, opting out of updates, requesting updates manually, skipping/ignoring specific updates, a preferences panel, reading/writing preferences to local storage,... For a full list of features, we'll need to review the Java implementation. And before we can begin to estimate what is involved, we'll need to know which aspects of the Java version of this feature are required/optional/unnecessary for HTML5 sims.

Notes on the Java implementation:
• The server-side component is PhetInfoServicePage.java
• The client-side implementation is all the files under phetcommon.updates.

**Comment by pixelzoom** [comment] 2015-01-02 00:01
@ariel-phet and @oliver-phet What is the priority of this feature? Timeframe for when you'd like to have it?  Thoughts on which aspects of the Java implementation are required vs. optional vs. unnecessary?

**Comment by ariel-phet** [comment] 2015-01-06 17:15
@pixelzoom - the question of this feature was brought up by @kathy-phet. Once we have HTML5 sim pages and the ability to download and run sims offline, @kathy-phet felt it would be useful for people to know if the sim is out of date. My sense is that in the HTML5 world, not as many people will be running our sims offline, but that is my guess, and we won't know until we have the ability to download them.

Personally, I think this feature could be as "simple" as just messaging the user that a newer version of the sim exists (ie not handling the download of the latest version). But this discussion should involve KP.

**Comment by pixelzoom** [comment] 2015-01-06 17:51
@ariel-phet wrote:
> Personally, I think this feature could be as "simple" as just messaging the user that a newer version of the sim exists (ie not handling the download of the latest version). But this discussion should involve KP.

Do we notify the user once? Keep bugging them until they update? Give them a choice? Let them opt out of update checking altogether?  Any "choice" that we give the user implies that we store the choices on disk, which opens up a can of worms.

**Comment by kathy-phet** [comment] 2015-01-06 18:00
Another question is how will this interact with translations? e.g. if the only change is new languages. 

Can someone recap the current plan for translations - my impression is that it involves redeployment every week or month? With a new version number?

**Comment by pixelzoom** [comment] 2015-01-06 18:10
The current plan is to process and deploy new translations monthly. Translations will be rolled out in maintenance releases, so yes, the version number will change.  Those same maintenance releases may contain other fixes and changes.

**Comment by kathy-phet** [comment] 2015-01-07 17:01
I don't think we will want to notify people to update if their are only new translations because monthly is going to be too often and people will get annoyed - so I think we'll need a strategy to be able to distinguish if they are "out-of-date" because of translations or otherwise - so we only alert them when it is our opinion that they should update. Perhaps we have a flag that says -- "this has an important update" and check both the version number and the "flag"? Other Suggestions?

**Comment by pixelzoom** [comment] 2015-01-07 18:09
What constitutes an "important update" is subjective. If you're the teacher in Romania who has been waiting for the Romain translation to be added/corrected, then they a translation update is what they're interested in.

Why not alert them that an update is available, provide a list of changes in the update, then let them decide whether it's an update that they are interested in?

**Comment by kathy-phet** [comment] 2015-01-07 19:33
If we can provide a list of changes, I agree that would be good.

**Comment by pixelzoom** [comment] 2015-01-08 17:46
What is the timeframe for this feature? When do you want it?

**Comment by samreid** [comment] 2015-01-08 19:00
At the Jan 8 developer meeting, @jbphet suggested collecting analytics after creating HTML sim pages with 'download' buttons, in order to understand how important this feature will be.

**Comment by jbphet** [comment] 2015-01-08 19:00
As we figure out how this works, we need to take into account versions running from the installer too.  Do we want the notification to behave the same way for installer versions?

**Comment by jbphet** [comment] 2015-01-08 19:04
We should do some data gathering after we have sim pages for HTML5 sims to see how often people are actually running the sims off line in a situation where the sim can contact our server.  If this is a very rare situation, then IMO it wouldn't be worth the time and effort to implement and maintain this feature.

**Comment by jbphet** [comment] 2015-01-08 19:11
In the 1/8/2015 developer meeting, we discussed the idea of having a menu item in the PhET Menu that says "Check for Updates".  This option would only appear if the sim was not served from our web site.  Once clicked, it would see if a newer version was available and, if so, give the user an option to go to the updated sim page.  The development team liked this idea, since it seemed relatively straightforward to implement and unobtrusive to the user.  We'd like to get @kathy-phet's opinion on this.

**Comment by jonathanolson** [comment] 2015-04-02 19:59
Costs for the update mechanism:
- Server-side logic to receive requests with version info and reply with whether we should recommend an  update (and what version to update, and any update messages)
- Client-side handling to send requests with version info and act on the reply. Should handle failure gracefully. Will also need to determine "are we in an installer", "are we built from PhET, or are we a 3rd party simulation", or if there are any other specialized conditions.
- Client-slide UI for recommending updates. Depends on translation updates/sim feature-bug updates/installer updates.
- Client-side persistent storage so we don't keep bugging someone (stores "ignore for this time", "ignore this update", "never remind me", etc. choices). Investigate cross-browser options (probably out of the question).

Additionally, do we need to make it compatible with the Java/Flash mechanism? It may be difficult.

I'd recommend taking care of other high-priority work first.

**Comment by pixelzoom** [comment] 2015-04-02 20:31
At 4/2/15 developer meeting, @ariel-phet wrote:
> I know we are planning to NOT notify when new translations occur, but what about for bug fixes?

This was news to me, but it sounded like @jbphet knew about it. 

Can @ariel-phet or @jbphet please summarize what the status of this is?  Are we going to deploy translations out of a maintenance branch without changing the version number? Or are we doing to somehow flag releases as "translation only"?  And if we're not going to use the Update feature to notify users that a new/modified translation is available, how do we intend to notify them?

**Comment by jonathanolson** [comment] 2015-06-11 20:03
New proposal for updates:

Similar to how Chrome/Firefox display updates, we could have the update only checked and shown in the About dialog. Once the user opens the About dialog, it would check whether the sim is up-to-date. While checking, it could shown a circling progress indicator. There are essentially three possibilities/messages:

1. Couldn't contact the server (no internet).
2. Sim is up to date.
3. Sim is out of date. Provide a link to somewhere with the message?

Additionally, we presumably wouldn't want to check/show the version if the sim was launched directly from the website, so it wouldn't exist in the layout then.

Alternatively, we could do the check on start-up, and color the menu button according to whether we are up-to-date (have it be colored if we are out of date?)

This approach is really quite simple compared to what we did with Java/Flash, since it requires no server-side logic (just reponds with version for a sim name request), and no complicated client-side logic (no need to store whether we told them about the update since it isn't intrusive, and no need to "ignore this update" and "ignore all future updates").

**Comment by samreid** [comment] 2015-06-11 21:12
> Alternatively, we could do the check on start-up, and color the menu button according to whether we are up-to-date (have it be colored if we are out of date?)

I just wanted to point out that this is how Chrome indicates that an update is available so (a) people may be accustomed to this feature and/or (b) google's UI team concluded this was a good approach.

I also wanted to point out another simplification we can make: all simulations (online/offline/installer/translations) would have the same feature to check for updates--don't try to make special cases for each one.

**Comment by samreid** [comment] 2015-06-11 21:16
At today's meeting, I also guesstimated that working on this at moderate priority, with a proper code review and our usual user interface polish, it would take around 2 weeks to develop.  Perhaps longer to thoroughly test on our many platforms and address issues that come up.

**Comment by jonathanolson** [comment] 2015-06-17 17:27
For the desired behavior, there are essentially four states that we can be in:
1. Up-to-date
2. Out-of-date
3. Checking version (internet request has not yet responded or been processed)
4. Check failed (presumably offline)

When the sim runs, we immediately fire off a check for the version.

Whenever a check completes, we will color the menu bar to a shade of green if we are out-of-date, otherwise it will be normal.

When the About dialog is opened, we do the following in each state:
1. Up-to-date: Display \<green checkmark like chrome\> "Sim is up to date."
2. Out-of-date: Display \<caution/attention icon\> "New version available." <-- all linked to whatever we want to point to
3. Checking version: Display \<rotator, somewhat like Chrome\> "Checking for updates." <-- until already-started check is complete
4. Check failed: immediately fire off a new check, going to (3).

When the check completes as either up-to-date or out-of-date, display the respective contents above. If it completes as "Check failed", display "Sim is offline."

We are out-of-date if the version string is different from what the website says is the most recent version string, and possibly if the build-date is different (@ariel-phet, @pixelzoom, @jbphet, @aaronsamuel137, do we want translation updates to trigger this process?).

For the initial prototype, I'll probably rely on existing metadata APIs. We can then standardize on a way of communicating. Long-term, would probably prefer sending something to a URL with a request:
```
{
  "api": "1.0",
  "simulation": "area-builder",
  "locale": "en",
  "currentVersion": "1.0.1",
  "buildDate": "2015-06-12 15:57:42 UTC"
}
```
and possible responses:
```
{
  "api": "1.0",
  "state": "up-to-date"
}
```
```
{
  "api": "1.0",
  "state": "out-of-date",
  "latestVersion": "1.0.2",
  "buildDate": "2015-06-17 15:57:42 UTC",
  "updateURL": "http://phet.colorado.edu/en/simulation/area-builder"
}
```
That API would need the comparison to be done on the server (safer long-term), and we don't need any complicated logic yet (just a comparison of version and possibly build-date) instead of the more-advanced recommendation system used in Java/Flash.

**Comment by jonathanolson** [comment] 2015-06-17 17:30
Also a quick note that if we do as described, '1.0.1-dev.1' would be declared out-of-date if '1.0.0' is the latest version. Do we need to do a more advanced comparison?

**Comment by pixelzoom** [comment] 2015-06-17 17:38
@jonathanolson asked:
> do we want translation updates to trigger this process?

In https://github.com/phetsims/joist/issues/189#issuecomment-69053182, @kathy-phet expressed a strong opinion about not notifying users about translation updates. But as I said in https://github.com/phetsims/joist/issues/189#issuecomment-69064225, what's constitutes an important update is subjective. Whether than unilateral deciding that translation updates are not important, I think we should give the user enough information about what's in the update to make their own decision.

**Comment by pixelzoom** [comment] 2015-06-17 17:40
@jonathanolson wrote:
> '1.0.1-dev.1' would be declared out-of-date if '1.0.0' is the latest version.

I don't follow. "1.0.1" is clearly more recent than "1.0.0", why would it be declared out-of-date?

**Comment by samreid** [comment] 2015-06-17 17:43
@jonathanolson said above:

> We are out-of-date if the version string is different from what the website says is the most recent version string, and possibly if the build-date is different 

I think he is trying to make simplifications to make this logic easier.

**Comment by jonathanolson** [comment] 2015-06-17 19:02
We can also do major/minor/maintenance checks, and treat suffixes differently.

Any preferences on how suffixes (not used for production versions) would be handled?

**Comment by kathy-phet** [comment] 2015-06-17 20:21
Overall this approach is sounding good to me. I like that the check is automatic, and that it tells you the answer.

Question: 
If they are in a translated version, would the update URL change or would it always go to english? 

If it changes it seems like it would have to have pretty good logic to know if a sim page existed in that language or not. Or it could go to the english page with the translations tab open if not english? 

What is the current version number change that you plan to make to a sim when a new translation is deployed?

**Comment by jonathanolson** [comment] 2015-06-17 20:25
> If they are in a translated version, would the update URL change or would it always go to english?

Presumably the update URL would be dependent on the locale. I wasn't yet sure if we were directing them to the sim page itself (in which case, the update URL would be dependent on whether there IS a website translation for that locale), or the up-to-date sim itself (which would usually be available for whatever locale launched).

> If it changes it seems like it would have to have pretty good logic to know if a sim page existed in that language or not. Or it could go to the english page with the translations tab open if not english?

The website could check if it has a translation for that locale. If so, it goes to the sim page in that locale. I'd need to check with @aaronsamuel137 if there's a good way of doing this (e.g. simulations/area-builder#translations).

> What is the current version number change that you plan to make to a sim when a new translation is deployed?

Currently no version number change is expected. The build date (below the version number) would be updated in this case.

**Comment by kathy-phet** [comment] 2015-06-17 20:33
In terms of where to send the link, it seems like there are some trade offs: 
Option 1: Sending them back to the sim page, brings anyone who hasn't been there lately or is accessing the sim from some 3rd party back to the phet website, which could certainly be useful. And download is pretty obvious from there now.
Option 2: Starting up the new sim for them gets them going with the new sim, but they may not realize how to download it one it is started in the browser. 
Option 3: A third option (if technically feasible) is initiating a download of the updated version of the sim for them, instead of launching it in the browser. This has the advantage of directly providing a file that they can use to replace their current file. 

I think my personal preference is sending them back to the PhET sim page to prioritize getting them back to the website itself.

**Comment by jonathanolson** [comment] 2015-06-17 20:38
> A third option (if technically feasible)

Yes, it's feasible.

> I think my personal preference is sending them back to the PhET sim page to prioritize getting them back to the website itself.

Sounds good to me, although I'd like to think about the best behavior for someone running a sim in locale X (assuming we don't have a website translation for locale X). If they click "New version available" (translated in the sim interface), it would be confusing to be brought to an English page if we don't have 'translations' opened and if we don't do something like highlight the translation they would use?

**Comment by jonathanolson** [comment] 2015-06-17 20:39
It's also possible to have multiple links/buttons in the About dialog when they are out-of-date, allowing a combination of any of the options.

**Comment by kathy-phet** [comment] 2015-06-17 20:48
Your comment made me wonder. 

Another option: About menu always has a "Sim Info and Lessons" or "Visit Sim Homepage" or "Visit Sim Webpage" or "Get Sim Lessons" link that brings you to the sim web page , and then have a "Download Update" if it is out of date.

**Comment by jonathanolson** [comment] 2015-06-17 20:55
> Another option: About menu always has a "Sim Info and Lessons" or "Visit Sim Homepage" or "Visit Sim Webpage" or "Get Sim Lessons" link that brings you to the sim web page , and then have a "Download Update" if it is out of date.

I'm fine with that approach, but I'd recommend primarily letting them know it's out of date, and then also having a way of downloading an update (since they may not be running a downloaded copy, I don't want "Download Update" to be the primary, particularly if they could bookmark the main sim from our website).

Also, do we want to disable the version update/check if running a custom-built together/interoperable version?

**Comment by kathy-phet** [comment] 2015-06-17 21:11
I did not mean to suggest not having your messages. I thought what you laid out was good ... eg a check mark with Sim up to date, etc. 

Good point that they may not be running a downloaded copy. Hmm ... then maybe just taking them to the sim page is right thing to do. 

I would say that for now at least - yes, we should disable this update feature for together/interoperable versions.

**Comment by jonathanolson** [comment] 2015-06-18 04:57
Added prototype version, will show tomorrow for feedback (http://www.colorado.edu/physics/phet/dev/olsonjb/update-tests/).

Currently checking dependencies.json comment on server to retrieve version, but it 404s for sims that haven't been published yet, and there should be better ways.

I also have a temporary URL meant for redirection for out-of-date sims, so that in the future we can control on the server where they get directed to, instead of baking that into the sim logic.

**Comment by jonathanolson** [comment] 2015-06-18 04:58
It would be helpful for @pixelzoom or @samreid to review my changes if possible.

**Comment by pixelzoom** [comment] 2015-06-18 14:21
I haven't had a chance to review the implementation yet, but took it for a quick test-drive.

Looks good for published sims, both in requirejs mode and with a build.

For an unpublished sim, I'm not wild about the error message (noted by @jonathanolson above) that occurs at startup and when the About dialog is opened (see below).  Error messages that are not really errors tend to obfuscate real error messages. (Remember PhetBuildGUI? Worthless console output.)  To avoid this, don't check for updates if version id starts with `'1.0.0-'`, which indicates an unpublished sim (in development, rc testing, etc., working towards 1.0.0).

```
GET http://phet.colorado.edu/sims/html/hookes-law/latest/dependencies.json 
XMLHttpRequest cannot load http://phet.colorado.edu/sims/html/hookes-law/latest/dependencies.json. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost' is therefore not allowed access. The response had HTTP status code 404.
```

A couple of UI comments... 

(1) How about putting the notice in the About dialog ("New version available") to the right of the version number, instead of below the build timestamp?  And then "Sim is up to date" can be shortened to "Up to date". (Regardless, the term "Sim" shouldn't be used.)

(2) The color change in the PhET menu bars is pretty subtle, and I'm skeptical that it will be an effective indicator. I don't have a better idea at the moment.  But perhaps we should do some user testing on this.

**Comment by pixelzoom** [comment] 2015-06-18 14:28
Another UI comment...

(3) Do we really need to put "Sim is offline" in the About dialog. Imo, no. But if yes, then maybe put it to right of version number, with a '?' icon and "offline". (Again, don't use "Sim".)

**Comment by pixelzoom** [comment] 2015-06-18 14:44
Implementation comments:

(1) `createUpdateNode` was added to AboutDialog. It's a significant chunk of code, and creating it isn't necessarily a responsibility of AboutDialog. Recommended to factor it out into a separate .js file. AboutDialog is presumably going to get refined in the future, and that will be easier if AboutDialog doesn't contain a bunch of code that doesn't need to be there.

(2) This bit of logic in AboutDialog:
`if ( UpdateCheck.areUpdatesChecked && ( UpdateCheck.state === 'offline' || UpdateCheck.state === 'unchecked' )` 
... should be encapsulated in UpdateCheck, something like:
```js
checkRequired: function() {
  return self.areUpdatesChecked && ( self.state === 'offline' || self.state === 'unchecked' );
}

(3) With Mac+Chrome and Wifi off, I never saw SpinningIndicatorNode in action. Is it wired up?

**Comment by pixelzoom** [comment] 2015-06-18 14:49
Re (2) immediately above... Perhaps `checkRequired` doesn't need to be public?  Clients could simply call UpdateCheck.check() and it would (internally) decide whether an update check was necessary, or whether to immediately return the previous successful check.

**Comment by pixelzoom** [comment] 2015-06-18 14:49
Close accidentally, reopened.

**Comment by jonathanolson** [comment] 2015-06-18 15:31
> For an unpublished sim, I'm not wild about the console error message
> To avoid this, don't check for updates if version id starts with '1.0.0-'

Sounds great, will do.

> (1) How about putting the notice in the About dialog ("New version available") to the right of the version number, instead of below the build timestamp? And then "Sim is up to date" can be shortened to "Up to date". (Regardless, the term "Sim" shouldn't be used.)
> (3) Do we really need to put "Sim is offline" in the About dialog. Imo, no. But if yes, then perhaps put it to right of version number, with a '?' icon and "offline". (Again, don't use "Sim".)

I was also wondering about both of those things. And "offline" may be inaccurate, since it also includes "some error", so something more about not being able to check for updates would be appropriate.

> (2) The color change in the PhET menu bars is pretty subtle, and I'm skeptical that it will be an effective indicator. I don't have a better idea at the moment. But perhaps we should do some user testing on this.

Subtle works with Chrome, since it auto-updates. Since sims don't, I could consider making it more noticeable.

> (1) createUpdateNode was added to AboutDialog. It's a significant chunk of code, and creating it isn't necessarily a responsibility of AboutDialog. Recommended to factor it out into a separate .js file. AboutDialog is presumably going to get refined in the future, and that will be easier if AboutDialog doesn't contain a bunch of code that doesn't need to be there.

I was also on the fence about this, but saw the credits were created this way. OK if I create UpdatePanel and CreditsPanel?

> This bit of logic in AboutDialog:
if ( UpdateCheck.areUpdatesChecked && ( UpdateCheck.state === 'offline' || UpdateCheck.state === 'unchecked' ) 
... should be encapsulated in UpdateCheck, something like
> ... checkRequired ...

It was a decision that the About dialog launching only rechecks given the 'offline' / 'unchecked' state, but other actions could in the future cause rechecks from other states. Given this behavior is specific to the About dialog launch, I'd prefer to leave it in place.

> (3) With Mac+Chrome and Wifi off, I never saw SpinningIndicatorNode in action. Is it wired up?

Yes, it's wired, see http://www.colorado.edu/physics/phet/dev/olsonjb/update-tests/color-vision-checking.html (in most of our cases right now, the request either fails or completes so quickly that it isn't really seen).

**Comment by jonathanolson** [comment] 2015-06-18 15:38
For the 'update-tests' link above, all files in that directory were created by changing/commenting-out code. To reproduce the "checking" locally, you can comment out lines 103-104 of UpdateCheck:
```js
req.open( 'get', 'http://phet.colorado.edu/sims/html/' + simName + '/latest/dependencies.json', true ); // enable CORS
req.send();
```
With it not actually sent, it will show "checking", waiting until it receives a reply.

**Comment by pixelzoom** [comment] 2015-06-18 15:38
> OK if I create UpdatePanel and CreditsPanel?

Yep.

> Given this behavior is specific to the About dialog launch, I'd prefer to leave it in place.

I'm still unclear on why the logic for the test (the `if` expression) can't be encapsulated in an UpdateCheck function. Ie, UpdateCheck can provide a function to test what AboutDialog wants to test, without the messy logic being in AboutDialog.  That doesn't require other client to use that behavior, it just keeps things like string literals from leaking into AboutDialog.

> Yes, it's wired, see http://www.colorado.edu/physics/phet/dev/olsonjb/update-tests/color-vision-checking.html

TypeError: undefined is not a function (evaluating 'Number.parseInt(n[1])')

**Comment by jonathanolson** [comment] 2015-06-18 15:46
> TypeError: undefined is not a function (evaluating 'Number.parseInt(n[1])')

Sorry, published those before making the fix for that. Will have new ones up soon.

**Comment by pixelzoom** [comment] 2015-06-18 18:53
6/18/15 dev meeting:
• Keep info in About dialog
• If an update is available, add "Get Update..." menu item in PhET menu, which takes you to the PhET website where the update is available

**Comment by jonathanolson** [comment] 2015-06-18 18:53
Also: Upper-case the 'w' in "PhET Website" for the PhET Menu.

**Comment by pixelzoom** [comment] 2015-06-18 19:00
> Also: Upper-case the 'w' in "PhET Website" for the PhET Menu.

I did this.

**Comment by jonathanolson** [comment] 2015-06-18 20:19
Latest UI:
Up-to-date: http://www.colorado.edu/physics/phet/dev/olsonjb/update-tests/molarity-up-to-date.html
Out-of-date: http://www.colorado.edu/physics/phet/dev/olsonjb/update-tests/molarity-out-of-date.html
Offline/failure to check: http://www.colorado.edu/physics/phet/dev/olsonjb/update-tests/molarity-offline.html
Checking: http://www.colorado.edu/physics/phet/dev/olsonjb/update-tests/molarity-checking.html

Font size tweak and added "Get Update..." into the PhET menu if it's out-of-date.

@kathy-phet, opinions?

**Comment by jonathanolson** [comment] 2015-06-25 17:02
Always in PhET Menu, "Check for updates..." - unless interoperable.

Will decide UI at end of meeting?

**Comment by jonathanolson** [comment] 2015-06-25 17:29
"Check for updates..." in PhetMenu, green if out-of-date.

Offline: Same thing as about dialog
Checking: Same thing as About dialog
Up-to-date: <green check> This simulation is up to date. ---- change About dialog to this text also.
Out-of-date:
```
There is a new version available: <latest version>. - left aligned
Your current version is <your version>. - left aligned
"Get Update..."(button)     "No Thanks"(button) -- center aligned with space
```

Text same size as in About dialog.

**Comment by jonathanolson** [comment] 2015-06-25 18:41
URL redirection proposal, from the code:
```js
    updateURL: 'http://phet.colorado.edu/html-sim-update' +
               '?simulation=' + encodeURIComponent( simName ) +
               '&version=' + encodeURIComponent( simVersion.toString() ) +
               '&buildTimestamp=' + encodeURIComponent( '' + phet.chipper.buildTimestamp ),
```

e.g.:
```
http://phet.colorado.edu/html-sim-update?simulation=molarity&version=1.1.0-dev.1&buildTimestamp=2015-06-18%2019%3A58%3A10%20UTC
```

**Comment by jonathanolson** [comment] 2015-06-25 18:42
Note that the server API will probably give the sim the URL to visit, so we could always avoid a redirection? Will discuss.

**Comment by aaronsamuel137** [comment] 2015-06-30 14:37
@jonathanolson, I have made an initial simplified API on the website, which I will deploy tonight. Feel free to review https://github.com/phetsims/website/commit/14cc7fafb93ce4a42b6013bb31f8f3e105dc51df.

Right now, the website does not track build date at all. Would you recommend adding a column for this? Which table do you think would be best. Currently, version information is in the project table, but I could also see build date being specific to a localized sim. Did you have any thoughts about how we will track build date on the server?

**Comment by pixelzoom** [comment] 2015-06-30 14:57
Just wanted to mention that hookes-law is getting close to production release. Will this feature be ready for inclusion in that release? Or do we need a way to disable it?

**Comment by jonathanolson** [comment] 2015-06-30 15:33
I'll plan to have it ready by the end of today, but I'm unsure of the testing schedule. @ariel-phet would have a better idea of whether it's realistic. I'll be able to bury it under a query-parameter if you find that helpful for now.

**Comment by jonathanolson** [comment] 2015-06-30 16:02
Latest UI: http://www.colorado.edu/physics/phet/dev/olsonjb/update-tests2/

Will have the internal work done soon.

**Comment by jonathanolson** [comment] 2015-06-30 16:31
Test requests:

On figaro, using "nc phet.colorado.edu 80" and piping/copy-pasting the following requests for testing:
```
POST /services/check-html-updates HTTP/1.1
Host: phet.colorado.edu
Content-Type: application/x-www-form-urlencoded
Content-Length: 125
Connection: close

{"api": "1.0","simulation": "molarity","locale": "en","currentVersion": "1.2.0-dev.1","buildDate": "2015-06-12 15:57:42 UTC"}
```

Since Molarity is 1.1.0, the following versions should respond for the following:
- 1.0.0 - Out of date
- 1.0.1 - Out of date
- 1.1.0-dev.2 - Out of date
- 1.1.1 - Up to date
- 1.1.0 - Up to date
- 1.2.0-dev.2 - Up to date
- 1.2.0 - Up to date

Note you'll need to change the Content-Length for the request to work nicely.

**Comment by jonathanolson** [comment] 2015-06-30 16:33
Also, if a website translation doesn't exist for some locale, we shouldn't direct to phet.colorado.edu/bad-locale/...

**Comment by jonathanolson** [comment] 2015-06-30 16:34
"updateURL" instead of "updateUrl", for the UPDATE_URL_KEY.

**Comment by jonathanolson** [comment] 2015-06-30 16:35
Additionally, CORS will need to be responding properly to allow requests. Might need to handle the OPTIONS request directly if we can?

**Comment by jonathanolson** [comment] 2015-06-30 16:40
Also, we should use 'buildTimestamp' instead of 'buildDate', sorry!

**Comment by jonathanolson** [comment] 2015-06-30 17:22
Actual submitted JSON post-data for implementation:
```js
{"api":"1.0","simulation":"molarity","locale":"en","currentVersion":"1.2.0-dev.1","buildDate":"2015-06-30 17:20:08 UTC"}
```

**Comment by aaronsamuel137** [comment] 2015-06-30 18:07
I assume you meant to put "buildTimestamp" in your last comment instead of "buildDate"?

**Comment by jonathanolson** [comment] 2015-06-30 18:37
Yes, fixed now. Thanks!

**Comment by aaronsamuel137** [comment] 2015-06-30 18:53
I've made these changes and tested. I'll deploy tonight. Feel free to review again if you'd like.

**Comment by jonathanolson** [comment] 2015-06-30 19:43
Looks good to me, I'll see if I can find any issues tonight. Thanks!

**Comment by jonathanolson** [comment] 2015-07-01 19:11
Notes:

1. If the locale matches a website translation, we probably shouldn't include the translation-header hash (e.g. for English, prefer http://phet.colorado.edu/en/simulation/molarity over http://phet.colorado.edu/en/simulation/molarity#translations-header).
2. For non-built sims, I'm seeing "{ "error": "JSONObject["buildTimestamp"] not found." }", since buildTimestamp is undefined. I think it's OK to have buildTimestamp undefined, can we allow it?

Besides those requested changes, it's working perfectly! I had to remove the content-type header the sims were sending (for now) due to CORS, but we could always look into ways to add it back. Assigning for those tweaks.

@ariel-phet, @aaronsamuel137, @pixelzoom and @samreid, do you have a preference for how this feature should be reviewed and tested?

**Comment by jonathanolson** [comment] 2015-07-01 19:13
Also, sample request and response for the current behavior (NOTE that browsers will do an OPTIONS request for CORS before making this request):
```
POST /services/check-html-updates HTTP/1.1
Host: phet.colorado.edu
Content-Length: 129
Connection: close

{"api": "1.0","simulation": "balancing-act","locale": "es","currentVersion": "1.0.2","buildTimestamp": "2015-06-12 15:57:42 UTC"}
```
```
HTTP/1.1 200 OK
Server: Apache
Access-Control-Allow-Origin: *
Access-Control-Allow-Methods: POST, OPTIONS
Pragma: no-cache
Cache-Control: no-cache, max-age=0, must-revalidate
Content-Language: en-US
Vary: Accept-Encoding
Content-Type: text/html;charset=UTF-8
Content-Length: 145
Accept-Ranges: bytes
Date: Wed, 01 Jul 2015 19:11:27 GMT
X-Varnish: 1009026971
Age: 0
Via: 1.1 varnish
Connection: close

{"latestVersion":"1.0.2","state":"up-to-date","api":"1.0","updateURL":"http://phet.colorado.edu/es/simulation/balancing-act#translations-header"}
```

**Comment by aaronsamuel137** [comment] 2015-07-01 22:35
I've made these changes. Will do a deploy tonight.

**Comment by aaronsamuel137** [comment] 2015-07-01 23:33
Deployed. Assigning to @jonathanolson for review.

**Comment by jonathanolson** [comment] 2015-07-02 15:41
Build timestamp optionality is working nicely, and I noticed that the stripping of "#translation-header" looks specific to English (http://phet.colorado.edu/es/simulation/molarity#translations-header). For now since we have only English sims, this definitely makes sense, but when we have a Spanish version of Molarity, presumably we wouldn't want to have the translations hash?

**Comment by jonathanolson** [comment] 2015-07-02 19:00
(Assigned for review).

**Comment by jessegreenberg** [comment] 2015-07-11 01:28
##### Review comments for update feature

* SpinningIndicatorNode.js

  * I notice that this.step( 0 ) initializes the colors, but isn't this called by by the sim anyway?  I am unsure if this is necessary.

  * I added the @constructor annotation, see commit above.

  * What are the scaling factors in rectangleFactory and circleFactory?  Were these calculated or empirically determined?

* SimVersion.js

  * The constructor takes an options object, but a few options are mandatory.  It seems strange to assert that some options are not optional.  Perhaps instead of calling it options, we could pass in an object called version?

* UpdateDialog.js

  * Top of UpdateDialog documentaiton says "Shows an ugly dialog that displays the current update status".  Did you mean for this to be long term documentation or was this a temporary development comment?

* UpdateNodes

  * Line 106: "Will closing be handled?"  Can this comment be removed?  It looks like the decision was to let AboutDialog handle closing.

That is all I could find in the review, it looks really good!  I also did some testing on various built and requirejs sims and versions and it is working very well.  Reassigning to @jonathanolson for remarks on above comments.

**Comment by jonathanolson** [comment] 2015-07-14 19:01
> I notice that this.step( 0 ) initializes the colors, but isn't this called by by the sim anyway? I am unsure if this is necessary.

I like to have the Node in a consistent graphical state after the constructor, without step() having been called yet. Is needed if someone wants to first display a "paused" indicator, but in general is more about safety and consistency.

> I added the @constructor annotation, see commit above.

Thanks.

> What are the scaling factors in rectangleFactory and circleFactory? Were these calculated or empirically determined?

Very empirically determined, so that the relative sizes look correct.

> The constructor takes an options object, but a few options are mandatory. It seems strange to assert that some options are not optional. Perhaps instead of calling it options, we could pass in an object called version?

Options does seem like an improper name. Mainly I'm hoping to be able to construct them like so (for readability mainly, but also so the constructor input is similar to the SimVersion object itself):
```js
return new SimVersion( {
  major: parseInt( matches[ 1 ], 10 ),
  minor: parseInt( matches[ 2 ], 10 ),
  maintenance: parseInt( matches[ 3 ], 10 ),
  suffix: matches[ 5 ],
  buildTimestamp: buildTimestamp
} );
```
Any thoughts on whether a new name for 'options' would work, or would SimVersion( major, minor, maintenance, options ) would be preferred?

> Top of UpdateDialog documentaiton says "Shows an ugly dialog that displays the current update status". Did you mean for this to be long term documentation or was this a temporary development comment?

Updated to note "fixed size", I probably editorialized too much (it has a ton of extra space in many cases).

> Line 106: "Will closing be handled?" Can this comment be removed? It looks like the decision was to let AboutDialog handle closing.

Updated to:
```js
// Closing the dialog is handled by the Dialog listener itself, no need to add code to close it here.
```

Thanks for the review. Let me know your opinion on SimVersion?

**Comment by jessegreenberg** [comment] 2015-07-15 20:02
Yes, I can see why it is desirable to construct a SimVersion with 
```
return new SimVersion( {
  major: parseInt( matches[ 1 ], 10 ),
  minor: parseInt( matches[ 2 ], 10 ),
  maintenance: parseInt( matches[ 3 ], 10 ),
  suffix: matches[ 5 ],
  buildTimestamp: buildTimestamp
} );
```
I prefer renaming Options.  Could we just rename the object to something like version?
```
  /**
   * @param {object} version - major/minor/maintenance properties are required
   * @constructor
   */
  function SimVersion( version ) {
    assert && assert( version.major !== undefined );
    assert && assert( version.minor !== undefined );
    assert && assert( version.maintenance !== undefined );

    this.major = version.major; // {number} major - Major version number
    this.minor = version.minor; // {number} minor - Major version number
    this.maintenance = version.maintenance; // {number} maintenance - Major version number
    this.suffix = version.suffix; // {string} [suffix] - Optional suffix (like 'dev.3')
    this.buildTimestamp = version.buildTimestamp; // {string} [buildTimestamp] - Optional build timestamp, like '2015-06-12 16:05:03 UTC' (phet.chipper.buildTimestamp)
  }
```

**Comment by jonathanolson** [comment] 2015-07-15 20:31
Fixed, anything else remaining to do?

**Comment by jessegreenberg** [comment] 2015-07-15 20:44
Nope, it looks very good as far as I am concerned, review is completed.  Reassigning to @jonathanolson to close if he is ready.

**Closed** 2015-07-16 01:00 UTC
Labels: enhancement, high-priority, Summer 2015 redeploy
