### ISSUE TITLE
No resize occurring when opening a second tab on mobile safari 

### ISSUE THREAD

**Issue by phet-steele** [phetsims/joist#234] opened 2015-04-01 18:13 UTC
This issue is only seen to be occurring on Safari 600.1.4, running on iOS 8 and later. When a sim is the only tab open in Safari, opening a second tab will not cause the sim to resize to the now smaller screen. This is seen across many sims, most likely all sims, but here is an example using Molecules & Light:

Only 1 tab:
![img_0007](https://cloud.githubusercontent.com/assets/5863899/6947866/5f786218-d867-11e4-9f09-a2af13dfda04.PNG)

After opening a second tab:
![img_0008](https://cloud.githubusercontent.com/assets/5863899/6947872/641049f8-d867-11e4-926b-a3552884fac3.PNG)

I believe this doesn't occur on earlier versions of Safari since the tab bar is always displayed, even with just one tab, so no resize needs to occur when opening subsequent tabs.

**Comment by pixelzoom** [comment] 2015-05-22 19:09
@ariel-phet please assess the priority of this.

**Comment by ariel-phet** [comment] 2015-05-27 18:49
I don't think this is quite "high priority" but it warrants investigation...is this a joist issue @pixelzoom? Can you do some quick investigation and offer some insight in what it will take to fix?

**Comment by pixelzoom** [comment] 2015-05-27 18:58
Investigation won't be "quick". I have never seen this occur, so first I'll need to reproduce it. And I don't have an immediate idea about where to look in joist.

**Comment by pixelzoom** [comment] 2015-05-29 17:04
@ariel-phet Investigation won't be "quick". I have never seen this occur, so first I'll need to reproduce it. And I don't have an immediate idea about where to look in joist.

**Comment by ariel-phet** [comment] 2015-05-29 17:10
@pixelzoom can you then see if you can reproduce the problem?

**Comment by pixelzoom** [comment] 2015-05-29 17:11
Will do.

**Comment by pixelzoom** [comment] 2015-05-29 17:12
Will do.

**Comment by pixelzoom** [comment] 2015-06-01 22:56
I'm testing on iOS 8.3 with Safari 600.1.4. I saw this problem on my first test, with Molecules and Light 1.0.1 from the PhET website. Then I tried master (requirejs and built versions) to see if it might be a joist issue that had been resolved, and didn't see the problem.  Then I went back to 1.0.1, and couldn't reproduce the problem.  Very weird.  I have no idea what might be causing this, and can't reproduce it reliably.

**Comment by pixelzoom** [comment] 2015-06-04 17:54
6/4/15 dev meeting: @samreid will take a second look.

**Comment by samreid** [comment] 2015-06-04 21:52
I'll be testing on Apple iPad 3rd generation running iOS 8.3.

@pixelzoom, how did you find your safari version?  I don't see it under Settings -> Safari.

First, when I launched the sim, there were many tabs.  When I closed the other tabs, Molecules and Light 1.0.1's size updated and it filled the new size.  Creating a new tab then switching back to the Molecules and Light tab, I can see that it did not resize and exhibits the same bug as shown in the issue description https://github.com/phetsims/joist/issues/234#issue-65746155  Rotating the screen to portrait->landscape refits it to be correct.  I was able to reproduce this bug on both times I tried to create it.

I see the same problem when running this with a freshly-built version of molecules and light.

**Comment by samreid** [comment] 2015-06-04 21:58
Same problem when running the requirejs version of molecules and light--this will be handy since it will help us more quickly test potential solutions.

**Comment by samreid** [comment] 2015-06-04 22:21
This person described the same problem we have here (but no applicable solution)
http://stackoverflow.com/questions/26741369/page-not-resizing-in-safari-mobile-when-user-opens-a-tab

This person showed how to set up a polling loop to detect if the tab has been re-selected after N seconds, then to trigger a relayout:
http://stackoverflow.com/questions/11085409/detect-moving-to-a-new-tab-in-mobile-safari

We are using `$( window ).resize()` to detect window size changes.  Looking at the jquery source code, it looks like this delegates to window.on('resize');

I tried switching to
```js
window.onresize = function() { sim.resizeToWindow(); };
```
but this had the same error.

NOTE: I tested this error in Safari Version 8.0.3 (10600.3.18) on OS X and the problem did *not* occur.

As noted here: http://stackoverflow.com/questions/14866775/detect-document-height-change we could poll the window height and update then, but it could slow down our app.  And indeed, it is unclear whether safari would report the new height value for this case.

**Comment by samreid** [comment] 2015-06-04 22:22
@pixelzoom can you review my notes above and suggest next steps?

**Comment by pixelzoom** [comment] 2015-06-04 23:28
@samreid Safari version is reported in PhET->Report A Problem.

**Comment by pixelzoom** [comment] 2015-06-08 18:06
I suggest passing this on the @jonathanolson as the next step.

**Comment by jonathanolson** [comment] 2015-06-22 19:34
> We could poll the window height and update then, but it could slow down our app.

@samreid, is there a specific reason why checking width/height every frame would slow it down?

**Comment by jonathanolson** [comment] 2015-06-22 20:39
Ok, not sure how to work around this so far.

Every way I can get the height returns the same amount (704) in the one-tab and buggy multiple-tab layout. Scrollable heights are 0, attempting to scroll to 0,0, skipping scrolling, and scrolling down and back up don't trigger any updates.

I haven't yet found a reliable marker for whether it's in the buggy state yet. Nothing under document/window/document.documentElement/scroll/window.screen seems to offer any clue that it is happening.

I've experimented heavily with viewport options, and setting other types of options don't seem to fix this situation (and caused other issues). Even wacky "mess with the DOM causing the contained content to change size" or "dynamically mess with CSS heights of the body" approaches don't seem to be triggering the proper height measurements.

@samreid or @pixelzoom, any thoughts on other potential approaches to try?

**Comment by pixelzoom** [comment] 2015-06-22 21:32
Sorry, beyond my comprehension.

**Comment by samreid** [comment] 2015-06-22 21:35
> @samreid, is there a specific reason why checking width/height every frame would slow it down?

I do not know whether checking size runs any code, or just returns a value (that was computed earlier).  May differ from browser to browser.

**Comment by samreid** [comment] 2015-06-23 02:10
> @samreid or @pixelzoom, any thoughts on other potential approaches to try?

Create a minimal reproducible test case and create a StackOverflow issue.

**Comment by pixelzoom** [comment] 2015-06-23 12:41
... and if you have a minimal reproducible test case, report to Apple.

**Comment by jonathanolson** [comment] 2015-06-25 16:14
I'm also curious whether this happens on iOS 9. @arnabp, would you be able to test this on the iOS 9 iPad?

**Comment by ariel-phet** [comment] 2015-06-25 17:02
Removing from summer redeploy, looks like we are punting on this issue for now.

**Comment by jonathanolson** [comment] 2015-06-25 17:03
Still planning on submitting a bug/issue report so hopefully we can figure out a solution ASAP.

**Comment by arnabp** [comment] 2015-06-25 17:59
On iOS 9 I am able to replicate this but only in certain situations:

Simply opening up a new tab and navigating back to the sim doesn't cause any cutoff and the sim resizes appropriately. However, if I open a link FROM the sim ("PhET website...", "Report a Problem...", etc.), then navigating back to the sim causes the tab to cover up part of the sim. In addition, iOS 9 has semitransparent tabs, so part of the sim is still visible:

![image](https://cloud.githubusercontent.com/assets/8583364/8361687/9e69309e-1b31-11e5-81a3-03e386cbb5c7.jpg)

**Comment by phet-steele** [comment] 2016-06-14 15:28
> Simply opening up a new tab and navigating back to the sim doesn't cause any cutoff and the sim resizes appropriately. However, if I open a link FROM the sim ("PhET website...", "Report a Problem...", etc.), then navigating back to the sim causes the tab to cover up part of the sim.

Still happens, this bug was never reported to Apple/StackOverflow. Does someone want to take a crack at it? Preferably not me, but someone more versed in the going-ons with this issue.

**Comment by ariel-phet** [comment] 2016-06-14 15:49
@samreid since you are often heavily involved with Joist, is this something you could report to apple? Or give @phet-steele some specific guidance?

**Comment by samreid** [comment] 2016-06-15 03:50
Since this issue is specific to iOS, let's test it on mobile safari on iOS 10 Beta which became available this week.  If it is still a problem, then we can work on scheduling creation of a minimal reproducible example that can be used on StackOverflow or as a bug report to Apple.  I'd be happy to help with that but would need to schedule it appropriately.

**Comment by brroberts1231** [comment] 2016-07-15 18:54
Tested on iOS 10.0, Safari 602.1, and confirmed that it is still a problem. Similar to what @arnabp said: 

> Simply opening up a new tab and navigating back to the sim doesn't cause any cutoff and the sim resizes appropriately. However, if I open a link FROM the sim ("PhET website...", "Report a Problem...", etc.), then navigating back to the sim causes the tab to cover up part of the sim. 

I found that if you open up a new tab without going anywhere (having it stay on the 'favorites' tab) then return back to the sim, the sim will resize. But instead if you open a new tab then go to any webpage, then return to the sim, it won't resize and the cutoff will occur.

**Comment by samreid** [comment] 2016-08-22 21:16
I noticed this problem again today during testing https://github.com/phetsims/bending-light/issues/351

**Comment by ariel-phet** [comment] 2016-09-28 14:57
Reread through this issue, 

@phet-steele take note for QA: Since this really appears to be a browser bug, (for which we have no easy workaround) and it requires switching tabs away from the sim and back to the sim, I think we are just not going to worry about it.

Making a minimal reproducible case is not exactly trivial.

@aadish do you feel like trying to make a minimal reproducible case here? If you feel like that would be a useful experience, give it a shot so we can report to apple. If not, feel free to close the issue.

**Comment by phet-steele** [comment] 2017-04-03 19:15
I encountered a new symptom after updating to iOS 10.3.1 (it's possible this was occurring before this update, but I never noticed).

1. DO THIS FIRST Open two tabs in mobile Safari
2. In one of them, load a sim
3. Close the other tab without a sim

The sim will not resize, evidenced by the navbar moving up from the bottom. No amount of refreshing the sim will fix this.

![img_0082](https://cloud.githubusercontent.com/assets/5863899/24626740/84584eaa-186f-11e7-8c56-6e800a44afab.PNG)

**Comment by lmulhall-phet** [comment] 2017-09-19 19:00
Resizing seems to work in iOS 11 for multiple sims.

**Comment by KatieWoe** [comment] 2018-10-31 18:11
Have seen this when testing https://github.com/phetsims/special-ops/issues/122 in random sims.  Difference is that the sim size is off upon opening the sim in a new tab, rather than from changes to tab number when the sim is already open.  Will post screenshot on next occurrence.

**Comment by samreid** [comment] 2018-11-12 23:50
@jonathanolson should we add a feature (maybe only on iOS) that just detects the window size each frame (or every N frames) and resizes if it is different?  @ariel-phet what is the priority of this issue?

**Comment by jonathanolson** [comment] 2018-11-13 05:55
At least before, Safari did NOT report a size change, and reported the incorrect (old) size, so I don't think polling would help? Maybe there is an alternative way to help? Maybe it is less buggy now?

**Comment by ariel-phet** [comment] 2018-11-14 18:58
@KatieWoe when this is seen, if the problematic tab is reloaded (so the sim is not properly sized, but your refresh that tab on the browser), does the problem fix itself?

**Comment by KatieWoe** [comment] 2018-11-14 19:06
It does.  I also think it might occur, or at least occur more often, if you go to the tab right away and switch back to the original tab before its loaded, and switch back to the sim tab very quickly.

**Comment by rea-laura** [comment] 2018-12-06 21:15
Also noticed this problem in MacOS 10.14.1 using Safari 12.0.1 while testing https://github.com/phetsims/QA/issues/234.

To Reproduce:
1) open sim
2) using the green expand button in the top left corner, open the window to full screen.
3) resize the window down again using the same green button
4) the downsized sim will now have the menu bar at the bottom cut off

**Comment by zepumph** [comment] 2021-07-19 16:38
@KatieWoe, do you still encounter this bug (anytime in the last year)?

**Comment by KatieWoe** [comment] 2021-07-19 17:18
I haven't seen this lately on iPadOS 12, 13, or 14. I can reopen if it reoccurs, but it can probably be closed for now.

**Comment by zepumph** [comment] 2021-07-19 19:27
Sounds good me!

**Closed by zepumph** 2021-07-19 19:27 UTC
Labels: type:bug, type:wontfix
