### ISSUE TITLE
Add Registered Trademark to Logo on Joist Nav Bar

### ISSUE THREAD

**Issue by kathy-phet** [phetsims/joist#258] opened 2015-06-25 20:36 UTC
We need to add the registered trademark R circle to our logo in the sim. 

Three places: 
- Loading screen
- Nav Bar 
- About dialog text "PhET Interactive Simulations" ... with R-circle small and next to top of the T. 

@amanda-phet : Can you mock up something that would be good for the size of loading screen and nav bars. These can possibly be a bit different.

**Comment by amanda-phet** [comment] 2015-06-30 21:40
The sizes used here are comparable to the sizes we decided on for the other logos we worked on. 

Navbar (blue):
![screen shot 2015-06-30 at 3 36 29 pm](https://cloud.githubusercontent.com/assets/7852916/8442714/daa55550-1f3d-11e5-911f-6d5e3bbb983b.png)
![screen shot 2015-06-30 at 3 36 40 pm](https://cloud.githubusercontent.com/assets/7852916/8442715/dd3b5f62-1f3d-11e5-8ac3-f7f7fdbe7815.png)

Navbar (gray): 
![screen shot 2015-06-30 at 3 37 44 pm](https://cloud.githubusercontent.com/assets/7852916/8442729/fbcdd680-1f3d-11e5-944a-57649c94d9d7.png)
![screen shot 2015-06-30 at 3 37 34 pm](https://cloud.githubusercontent.com/assets/7852916/8442732/fe422466-1f3d-11e5-9e49-167b8e4ab8f2.png)

Loading screen (blue, but it could be gray or white): 
![screen shot 2015-06-30 at 3 38 22 pm](https://cloud.githubusercontent.com/assets/7852916/8442743/154dd740-1f3e-11e5-9b23-f27f0ccff120.png)

About dialog:
![screen shot 2015-06-30 at 3 38 52 pm](https://cloud.githubusercontent.com/assets/7852916/8442763/2a89f6e8-1f3e-11e5-9429-08129d6d1ca9.png)

**Comment by pixelzoom** [comment] 2015-06-30 21:54
You're bucking convention by putting the registered trademark symbol (®) at the lower-right of the logo. By convention, it's placed at the upper-right. Eg see http://howconceptual.com/tm-symbol/.

Also wanted to verify... Has PhET obtained a Federal trademark registration certificate? The registered trademark symbol may only be used if you have such a registration certificate. Otherwise use the ™ trademark symbol.

**Comment by amanda-phet** [comment] 2015-06-30 22:01
We looked at a lot of logos, and the most consistent placement was on the right side of the logo-- usually the upper-right, but was often the lower-right as well (see coca-cola, for example). 

The logo is in fact registered, and we have been told to start using the symbol. It should be in at least one instance of the logo on any web page. @kathy-phet can confirm this and elaborate on it.

**Comment by amanda-phet** [comment] 2015-07-02 21:34
@pixelzoom Will you be the one implementing these changes? Kathy would like them done with the summer redeploy. If it is you, I will email the .png logo files to you- one for the navbar and one for the loading screen (which is identical to the website header logo). 

As for the text in the about dialog- each typeface handles ® differently. The Arial ® is as large as a lowercase letter, but we just want it in the top right corner after PhET. Let me know if I can help in any way with handling this- I can find another typeface for that symbol only, or give you an image file- or perhaps it can be drawn in code.

**Comment by pixelzoom** [comment] 2015-07-02 23:48
@amanda-phet I don't think this work has been assigned yet, @ariel-phet should probably handle assignment, but I'll be happy to do it.  

From what I see so far, this looks like we're just updating the PhET logo image file, and the "PhET®" string that appears in the About dialog.  Should we also change "PhET Website" to "PhET® Website" in the PhET menu?

**Comment by kathy-phet** [comment] 2015-07-03 05:05
I assigned this to Ariel, to discuss who should make these changes, but as Chris mentioned its primarly just updating the logo files. 

@pixelzoom - To confirm Amanda's comment, the PhET name and logo are both registered trademarks now. We only need to put the ® on one instance per page ... so we don't need to have it in the Menu item itself.

**Comment by pixelzoom** [comment] 2015-07-03 14:53
I added ® to the 'PhET' string in Brand.js, which is what appears in the About dialog. Here's how it looks:

![screenshot_545](https://cloud.githubusercontent.com/assets/3046552/8501238/e4b2bdce-2160-11e5-808b-3ae7312abe2c.png)

**Comment by ariel-phet** [comment] 2015-07-03 18:54
@pixelzoom please go ahead and complete this work. @amanda-phet should be able to provide any of the files you need.

**Comment by pixelzoom** [comment] 2015-07-06 03:44
@amanda-phet There are 3 logo files that I'll need: logo.png, logo-on-white.png and splash.svg. The current versions of those files can be found here: https://github.com/phetsims/brand/tree/phet/images.  According to the header in splash.svg, it was generated using "Adobe Illustrator 15.0.2, SVG Export Plug-In". I'm not positive, but I think the original .ai files are in https://github.com/phetsims/joist/tree/master/assets.

**Comment by pixelzoom** [comment] 2015-07-06 03:52
I wrote:
> I'm not positive, but I think the original .ai files are in https://github.com/phetsims/joist/tree/master/assets.

As part of #269, I took a closer look at these files. The 3 files are:

> phet-logo.svg
PhET_Logo_FINAL_RGB_NoTagLine.ai
PhET_Logo_FINAL_RGB_TagLine_White.ai

You can probably ignore phet-logo.svg.

PhET_Logo_FINAL_RGB_NoTagLine.ai is the PhET logo *without* "Interactive Simulations" below it.

PhET_Logo_FINAL_RGB_TagLine_White.ai is the PhET logo with "Interaction Simulations" below it, and those letters are in white.  When you open the .ai file in Illustrator, you'll have white letters on a white background, so you won't see them.  But mouse over them and you'll see that they're there.

**Comment by pixelzoom** [comment] 2015-07-06 14:40
@amanda-phet Looks like we also need a different set of black-&-white logo files for the "adapted from PhET" brand. You can see the current files here: https://github.com/phetsims/brand/tree/adapted-from-phet/images

**Comment by amanda-phet** [comment] 2015-07-09 17:57
We have two versions of the logo with the registered symbol:
1. When the PhET logo is small (such as in the navbar), the ® must be larger in relation to the logo.
2. When the PhET logo is larger (such as the loading page), the ® can be smaller in relation to the logo.

Is PhET_Logo_FINAL_RGB_NoTagLine the logo for the navbar, and PhET_Logo_FINAL_RGB_TagLine the larger logo used on the loading page? If the NoTagLine logo is used in an instance where it is larger, the ® will look really big. I guess it would be useful to know the instances of these two different logo files.

**Comment by pixelzoom** [comment] 2015-07-09 18:49
@ariel-phet says to also get the "official" .ai file for the PhET logo from @amanda-phet and check it into github.

**Comment by pixelzoom** [comment] 2015-07-09 19:00
@amanda-phet Regarding your questions about the asset files... I'm unclear on the history/use of these, and we're trying to figure that out in https://github.com/phetsims/joist/issues/258.

**Comment by pixelzoom** [comment] 2015-07-10 20:18
@amanda-phet emailed me phet-brand-assets.ai, with this information:

> Here is a single .ai file with four registered trademark versions of our logo.
> 1. a full-size color version with white text (for loading page)
> 2. a mini color version (for all navbars)
> 3. a mini black version (for adapted navbars)
> 4. a mini white version (for adapted navbars)

**Comment by pixelzoom** [comment] 2015-07-10 20:19
@amanda-phet also sent me revised versions of PhET_Logo_FINAL_RGB_NoTagline.ai and PhET_Logo_FINAL_RGB_Tagline_White.ai.  I replied:

> Hi Amanda,

The files that you attached are .ai files. I had mentioned these files in https://github.com/phetsims/joist/issues/258#issuecomment-118707088 in case you needed to modify them to create the image files.  These .ai files appear to be covered by the phet-brand-assets.ai file that you sent me in a separate email, so I don’t need them.

The files that I do need are logo.png, logo-on-white.png, splash.svg, as  described in https://github.com/phetsims/joist/issues/258#issuecomment-118706666.

Chris

**Comment by amanda-phet** [comment] 2015-07-10 20:49
I can export the .pngs from the .ai file I sent you with the following:

>1. a full-size color version with white text (for loading page)
2. a mini color version (for all navbars)
3. a mini black version (for adapted navbars)
4. a mini white version (for adapted navbars)

The full-size version (1) is what I imagine you'll use for splash.svg, but logo.png and logo-on-white.png can be consolidated using the mini color version (2). We decided to use the same yellow for the logo in all occurrences rather than have two different yellows floating around.

**Comment by pixelzoom** [comment] 2015-07-10 21:01
@amanda-phet ...

> The full-size version (1) is what I imagine you'll use for splash.svg,

Yes. Please export from .ai so that it is has the same dimensions as brand/images/splash.svg.

> but logo.png and logo-on-white.png can be consolidated using the mini color version (2). We decided to use the same yellow for the logo in all occurrences rather than have two different yellows floating around.

I'll take your word for it, I was not involved in the decision.  Feel free to send me a single PNG with transparent background and the same dimensions as logo.png.

Thanks.

**Comment by pixelzoom** [comment] 2015-07-10 22:15
Updates for the 'phet' brand are done.

Now we need to update the 'adapted-from-phet' brand, as described in https://github.com/phetsims/joist/issues/258#issuecomment-118875729.

**Comment by pixelzoom** [comment] 2015-07-10 22:21
Ah… Now we have a big problem.  We previously had logo.png and logo-on-white.png, and logic in joist for which logo to use based on the navbar background color.  In https://github.com/phetsims/joist/issues/258#issuecomment-118875729, @amanda-phet said that the decision was made to consolidate to a single logo.png.  That may work for the ‘phet’ brand, but it doesn’t work for the ‘adapted-from-phet’ brand, where the logo is either totally white or totally black.   I’ve already deleted the code from joist, so things are messed up (which doesn’t make me happy on Friday at happy hour :)  Should I revert?  How to proceed?

**Comment by pixelzoom** [comment] 2015-07-10 22:40
I've restored the joist logic for logo.png and logo-on-white.png, and in the 'phet brand logo-on-white.png is an identical copy of logo.png.

I also noticed that 'interoperable' brand has the same logo files as 'phet' brand. @ariel-phet said for now to copy the logos from 'phet' brand to 'interoperable' brand.

Also noticed that any sim using 'master' brand fails at startup if it's navbar is white, because that brand is missing logo-on-white.png.

**Comment by pixelzoom** [comment] 2015-07-10 23:38
Here are dev versions showing the various revised logo files.

'phet' brand, black navbar:
http://www.colorado.edu/physics/phet/dev/html/scenery-phet/1.0.0-dev.4/scenery-phet_en.html

'phet' brand, white navbar:
http://www.colorado.edu/physics/phet/dev/html/scenery-phet/1.0.0-dev.5/scenery-phet_en.html

'adapted-from-phet', black navbar:
http://www.colorado.edu/physics/phet/dev/html/scenery-phet/1.0.0-dev.7/scenery-phet_en.html

'adapted-from-phet', white navbar:
 http://www.colorado.edu/physics/phet/dev/html/scenery-phet/1.0.0-dev.8/scenery-phet_en.html

**Comment by pixelzoom** [comment] 2015-07-11 00:16
You can ignore the above dev versions, we're going to start over.

In brand#15 the quality of the logo was flagged. We decided to use mipmapping for the logo in the navbar (PhetButton). This will require adding the mipmap plugin to all config.js files. The image files may already be bigger than needed (273x108), since PhetButton is scaling that by 0.28. @samreid will experiment and provide @ariel-phet with new image dimensions. Then @ariel-phet will generate the 4 images files needed (logo.png, logo-white.png, for 2 brands: 'phet' and 'adapted-from-phet') taking care not to chop off the right and bottom edge of the (R)

**Comment by pixelzoom** [comment] 2015-07-11 00:23
TODO:

- [ ] Add mipmap plugin to config.js files for all repositories
- [ ] Replace logo.png and logo-on-white.png in 'phet' branch of brand
- [ ] Replace logo.png and logo-on-white.png in 'adapted-from-phet' branch of brand
- [ ] Replace `image!` with `mipmap!` in PhetButton.js
- [ ] Possibly adjust scale of `var phetLabel` on line 77 of PhetButton.js
- [ ] Publish 4 new dev versions, as in https://github.com/phetsims/joist/issues/258#issuecomment-120551152

**Comment by pixelzoom** [comment] 2015-07-11 00:25
TODO for @pixelzoom unless otherwise noted:

- [ ] determine optimal size for logo.png and logo-on-white.png (@samreid)
- [ ] create new logo.png and logo-white.png for 'phet' and 'adapted-from-phet' brands (@ariel-phet)
- [ ] Add mipmap plugin to config.js files for all repositories
- [ ] Replace logo.png and logo-on-white.png in 'phet' branch of brand
- [ ] Copy logo.png and logo-on-white.png from 'phet' branch to 'interoperable' branch of brand
- [ ] Replace logo.png and logo-on-white.png in 'adapted-from-phet' branch of brand
- [ ] Replace `image!` with `mipmap!` in PhetButton.js
- [ ] Possibly adjust scale of `var phetLabel` on line 77 of PhetButton.js
- [ ] Publish 4 new dev versions, as in https://github.com/phetsims/joist/issues/258#issuecomment-120551152

**Comment by samreid** [comment] 2015-07-13 16:09
Here's my plan:

1. I'm going to track down the logo with the same resolution as before where the (r) is not truncated, possibly one provided last week by @ariel-phet.
2. Test that logo in Firefox on my 39.0 OS X with joist as it is
3. Test the same logo, but with mipmap turned on (make sure to clear cache between tests)

If this doesn't look good enough, I'll experiment with different image sizes.  If this looks OK then we can proceed and I'll turn it back over to @pixelzoom.

**Comment by samreid** [comment] 2015-07-13 16:40
I couldn't see a blue+yellow phet logo so I took the following steps to create one (may not be optimal):

1. resized artboards in the AI file
2. maximize the AI file so it fills the screen
3. screen capture
4. paste to photoshop
5. clear background using magic wand
6. crop appropriately
7. use save to web and set height to 108 px and verify that width is 270px

I noticed that this process created a circle (r) that is very feathery and may not work at all.

![image](https://cloud.githubusercontent.com/assets/679486/8654970/4d83c234-294b-11e5-8f28-00fe4ab1a8c5.png)

Compare to the original:
![image](https://cloud.githubusercontent.com/assets/679486/8655010/8b4f97e6-294b-11e5-811b-7495255ee9af.png)

**Comment by samreid** [comment] 2015-07-13 16:46
I exported to PNG directly from AI and it looked much better:

![image](https://cloud.githubusercontent.com/assets/679486/8655127/674fdaa8-294c-11e5-9365-963727a48f38.png)

**Comment by amanda-phet** [comment] 2015-07-13 16:52
The .ai file is in google drive. Go to PhET Ai Files > Website > Logos > phet-brand-assets.ai. The artboards are sized at 273x108.

**Comment by samreid** [comment] 2015-07-13 16:52
OK, thanks, I'll take a look.

**Comment by pixelzoom** [comment] 2015-07-13 16:55
@amanda-phet @ariel-phet Note that phet-brand-assets.ai in GitHub already appears to be stale, as changes are being made to Google Drive without checking them into GitHub.  And this is continuing to result in confusion and wasted developer time.

**Comment by samreid** [comment] 2015-07-13 16:56
@amanda-phet should I use logo.png or export from phet-brand-assets.ai to raster?

**Comment by samreid** [comment] 2015-07-13 17:00
Using the artwork I sampled manually (since I'm still waiting to hear from @amanda-phet which one to use), the artwork looks a bit jagged in Firefox:

Here's the manually sampled image:
![logo](https://cloud.githubusercontent.com/assets/679486/8655416/30f27c2a-294e-11e5-8df1-bfcdfdaabe16.png)

Here's how it looks in firefox:
![image](https://cloud.githubusercontent.com/assets/679486/8655434/4de94084-294e-11e5-99fb-1087eb32fbc8.png)

I'll try a mipmap next.

**Comment by amanda-phet** [comment] 2015-07-13 17:00
I was just trying to point @samreid in the direction of an updated file because I saw that he wrote 
>I couldn't see a blue+yellow phet logo so I took the following steps to create one (may not be optimal).

and the work had already been done.

**Comment by samreid** [comment] 2015-07-13 17:01
> I was just trying to point @samreid in the direction of an updated file 

Thanks, I appreciate it and am not interested in duplicating work unnecessarily.  However, I'm still not sure while file to use, as I asked above:

> @amanda-phet should I use logo.png or export from phet-brand-assets.ai to raster?

**Comment by samreid** [comment] 2015-07-13 17:02
Also, @amanda-phet I heard someone mention that we were picking a yellow that worked well against black and white, so we wouldn't have different logo for each situation.  Is that true?  Is the appropriate shade of yellow in some of the google drive files?

**Comment by samreid** [comment] 2015-07-13 17:04
Sorry, forgot to grunt build after updating to the better raster.  Here's what it looks like in firefox with image!

![image](https://cloud.githubusercontent.com/assets/679486/8655525/f60257b0-294e-11e5-9542-ed6abc83a946.png)

**Comment by amanda-phet** [comment] 2015-07-13 17:07
@samreid Use logo.png since it is already exported and resized to 273x108. The yellow that you are using here is the universal yellow. It is documented in the PhET Visual Identity google doc.

**Comment by samreid** [comment] 2015-07-13 17:07
Here's what it looks like in firefox after mipmap! plugin:

![image](https://cloud.githubusercontent.com/assets/679486/8655587/57efc192-294f-11e5-8a3a-cea9fcdf5a9c.png)

**Comment by ariel-phet** [comment] 2015-07-13 17:10
@samreid - please do a skype call with @amanda-phet to avoid back and forth in the github issue and eliminate any confusion.

**Comment by samreid** [comment] 2015-07-13 17:12
@ariel-phet ok will do.

**Comment by samreid** [comment] 2015-07-13 17:14
Using the raster from google docs + the requirejs plugin, it looks like this in firefox:

![image](https://cloud.githubusercontent.com/assets/679486/8655732/430a3db0-2950-11e5-978d-c3b87d6a6c2c.png)

**Comment by pixelzoom** [comment] 2015-07-13 17:19
@samreid asked:
> Also, @amanda-phet I heard someone mention that we were picking a yellow that worked well against black and white, so we wouldn't have different logo for each situation. Is that true? Is the appropriate shade of yellow in some of the google drive files?

Separate logo.png and logo-on-white.png files are still necessary. 
See https://github.com/phetsims/joist/issues/258#issuecomment-120541167 and https://github.com/phetsims/joist/issues/258#issuecomment-120543577. For the 'phet' and 'interoperable' brands, the 2 files will be identical.

**Comment by samreid** [comment] 2015-07-13 20:21
OK I followed these steps:

1. Ilustrator: export artboard 2, optimize for art on transparent background
2. resize canvas to 273x108 in photoshop
3. save for web as PNG
4. build hooke's law
5. clear firefox browser cache
6. launch built version:

It looks like this on my OS X firefox (with mipmap) at fullscreen minus chrome and taskbar:

![image](https://cloud.githubusercontent.com/assets/679486/8659765/1ecf5088-296a-11e5-9719-3353dc585472.png)

And here is the same thing with no mipmaps (just plain image):
![image](https://cloud.githubusercontent.com/assets/679486/8659802/5e49d436-296a-11e5-9dd8-8b5fcc0e58dd.png)

**Comment by samreid** [comment] 2015-07-13 20:25
This is with a 40px high image, scaled at `0.28*108/40`

![image](https://cloud.githubusercontent.com/assets/679486/8659885/eb0a3f6e-296a-11e5-85c1-fa6e3ee6a24b.png)

**Comment by samreid** [comment] 2015-07-13 20:46
Chrome using image (fullscreen-toolbars on non-retina air)
![image](https://cloud.githubusercontent.com/assets/679486/8660277/480048ec-296d-11e5-99ec-5731e357bab3.png)

Chrome using mipmap:
![image](https://cloud.githubusercontent.com/assets/679486/8660334/9cd76882-296d-11e5-9ee9-9f122bed774f.png)

In my opinion, both of these seem OK, so I think it is OK to proceed with the original dimensions 273x108 with the revised (non-clipped) artwork with mipmapping.

**Comment by samreid** [comment] 2015-07-13 20:53
Please note, the artwork checked in to master has an artboard of 109px tall, so I needed to manually trim the canvas in photoshop to be 108px high (could not quickly find out how to resize an artboard in illustrator).

@amanda-phet do the black or white logos need to be re-edited to match the last version of the color logo we created today? available here: https://github.com/phetsims/brand/blob/phet/assets/phet-brand-assets.ai

Also @amanda-phet can you help resize the artboard to 108px high?  When you are done, please re-upload to google drive and let me know when it has been updated so I can re-commit to github.

Just a note--One other thing @amanda-phet and I discussed was pixel-editing the exported raster from illustrator, but I'm not sure that is warranted at this point.

**Comment by samreid** [comment] 2015-07-13 21:52
I checked off two items in https://github.com/phetsims/joist/issues/258#issuecomment-120555603, and reassigning to @pixelzoom.  Chris: please be on the alert for issues--while minimally modified, these logos have not been looked at on many platforms with mipmapping, so please be critical and raise any issues you see.

**Comment by pixelzoom** [comment] 2015-07-14 00:30
Here's a new set of dev versions that demonstrate the revised logo files:

'phet' brand, black navbar:
http://www.colorado.edu/physics/phet/dev/html/scenery-phet/1.0.0-dev.9/scenery-phet_en.html

'phet' brand, white navbar:
http://www.colorado.edu/physics/phet/dev/html/scenery-phet/1.0.0-dev.10/scenery-phet_en.html

'adapted-from-phet', black navbar:
http://www.colorado.edu/physics/phet/dev/html/scenery-phet/1.0.0-dev.11/scenery-phet_en.html

'adapted-from-phet', white navbar:
 http://www.colorado.edu/physics/phet/dev/html/scenery-phet/1.0.0-dev.12/scenery-phet_en.html

**Comment by pixelzoom** [comment] 2015-07-14 00:35
All changes completed.  Remaining tasks:

- [ ] Have someone review the above dev versions to see if the quality is acceptable on all browsers.
- [ ] Determine if there is any appreciable performance or size penalty for requiring the mipmap plugin to be included in every sim.  If there is, decide whether it's worth the quality improvement.

**Comment by ariel-phet** [comment] 2015-07-14 02:25
@pixelzoom I reviewed on all windows 7 browsers (IE11, FF, Chrome). All four versions look good. Marked improvement in FF, and the logo looks quite crisp in IE11, and Chrome

**Comment by ariel-phet** [comment] 2015-07-14 02:26
And I should say...nice work! I know that turned into a much bigger project, but I am glad our logo now looks so much less aliased.

**Comment by pixelzoom** [comment] 2015-07-14 14:52
@amanda-phet and @samreid Please review the dev versions.

Assigning this back to @kathy-phet for approval since she opened the issue.

**Comment by amanda-phet** [comment] 2015-07-14 15:30
I reviewed in Safari, Chrome, and FF. They all look great on my retina macbook:
<img width="438" alt="screen shot 2015-07-14 at 9 29 11 am" src="https://cloud.githubusercontent.com/assets/7852916/8677172/d82f6680-2a0a-11e5-8eb5-73953092d4d6.png">
and external monitor:
![screen shot 2015-07-14 at 9 27 34 am](https://cloud.githubusercontent.com/assets/7852916/8677181/e3d543c4-2a0a-11e5-858b-96bc24005d4e.png)

**Comment by kathy-phet** [comment] 2015-07-14 15:37
Looks good to me, too! Thanks for all the work on making this change happen, and look so nice across all the browsers..

**Comment by kathy-phet** [comment] 2015-07-14 15:39
Assigning back to Ariel to oversee or assign final checks on Chris' list.

**Comment by pixelzoom** [comment] 2015-07-14 15:46
@ariel-phet Here's what's left to do:

Get @samreid's feedback on quality. (Everyone else has given a thumb's up.)

Have someone check that performance hasn't been adversely affected. I don't have time to do this. Recommended to assign to @jonathanolson since he's most familiar with the mipmap plugin.

**Comment by jonathanolson** [comment] 2015-07-14 15:58
Since the logo isn't being moved after the sim is launched, there shouldn't be any runtime performance drawback (it's as if you had used a single resolution that was properly selected yourself, instead of mipmapping).

Is there any other thing that should be reviewed for performance?

**Comment by samreid** [comment] 2015-07-14 18:58
Assigned to myself to give feedback on quality as prescribed above.  Afterwards I'll reassign to @ariel-phet to see if anything else remains for the issue.

**Comment by samreid** [comment] 2015-07-14 19:19
Testing OS X + Chrome Version 43.0.2357.134 (64-bit) on my large external monitor: All 4 tests look great.

Testing on OS X + Firefox 39 on my 11" Macbook Air built-in screen.  The navbar :registered: looks like a broken clock: 
![image](https://cloud.githubusercontent.com/assets/679486/8682175/b9e7ed46-2a28-11e5-8975-c60bf84d2b7a.png)

On white it is very faint:
![image](https://cloud.githubusercontent.com/assets/679486/8682196/db3a5646-2a28-11e5-91d4-a712a3cc3806.png)

Testing on OS X + Safari on my large screen, http://www.colorado.edu/physics/phet/dev/html/scenery-phet/1.0.0-dev.10/scenery-phet_en.html looks good.

All 4 tests are gorgeous on the iPad retina.

On Win8/IE11, the :registered: looks good at fullscreen but gets blurry/aliased if the window gets a bit smaller, here is a screenshot of the entire screen for context:
![image](https://cloud.githubusercontent.com/assets/679486/8682506/9f6d5ec2-2a2a-11e5-9368-5744f891ae3a.png)

In my opinion, it is probably OK to say it won't look good on Firefox on 11" MacBook Air or smaller window sizes but I'll leave it up to @ariel-phet to review my notes and screenshots above and decide.

**Comment by pixelzoom** [comment] 2015-07-14 19:23
@jonathanolson 
> Is there any other thing that should be reviewed for performance?

I guess the only other thing is deliverable (html file) size. But I can take a stab at that.

Here are a couple of sims, showing size before adding mipmap, after adding mipmap, and the increase:

hookes-law_en.html:
  before: 907733 (1.0.0-dev.24)
  after: 938490 (master)
  increase: 30757

balancing-chemical-equations_en.html
  before: 1070710 (1.1.0-dev.2)
  after: 1098733
  increase: 28023

Based on this (admittedly small) sampling, it looks like we're adding <= 30K to the download size.

Here's the mipmap output from `grunt -d`:

```
[D] mipmapped /Users/cmalley/PhET/GitHub/brand/js/../images/logo.png to level 4 with quality: 98
[D] level 0 (PNG 273x108) base64: 3558 bytes 
[D] level 1 (PNG 137x54) base64: 2326 bytes 
[D] level 2 (PNG 69x27) base64: 1374 bytes 
[D] level 3 (PNG 35x14) base64: 866 bytes 
[D] level 4 (PNG 18x7) base64: 506 bytes 
[D] mipmapped /Users/cmalley/PhET/GitHub/brand/js/../images/logo-on-white.png to level 4 with quality: 98
[D] level 0 (PNG 273x108) base64: 3558 bytes 
[D] level 1 (PNG 137x54) base64: 2326 bytes 
[D] level 2 (PNG 69x27) base64: 1374 bytes 
[D] level 3 (PNG 35x14) base64: 866 bytes 
[D] level 4 (PNG 18x7) base64: 506 bytes 
```

Adding these up is 17260 bytes.

**Comment by ariel-phet** [comment] 2015-07-14 19:35
@samreid - I think these are acceptable compromises. I think at this point we have done the best we can. The other option would be to increase these size of the R considerably. I do not think that is a reasonable option, and we are following convention when compared to brands such as CocaCola that the presence of the R is often not particularly legible, and in many context looks like a small dot/circle/etc.Overall, these are looking good, and screen resolutions will only increase in the future to alleviate such concerns.

@pixelzoom - <=30K seems like an acceptably small percentage increase IMO

**Comment by samreid** [comment] 2015-07-14 19:39
I agree with @ariel-phet's remarks but just wanted to comment on one detail from a previous comment.  @pixelzoom said:

> Based on this (admittedly small) sampling, it looks like we're adding <= 30K to the download size.

But it looks like @pixelzoom was comparing uncompressed sized and we should be looking at gzipped sizes for download.  So 30K would be an upper bound since these images-as-text may be somewhat compressible.

**Comment by pixelzoom** [comment] 2015-07-14 19:49
@jonathanolson confirmed that level 0 is equivalent to the size that we were bundling when using the image plugin. So the addition size for the images is actually 10144 bytes.  The rest of the size increase is probably the mipmap plugin itself

Here's a better size comparison. I did 2 builds of hookes-law, with and with mipmap:

with mipmap: 938490
without mipmap: 924787
increase: 13703

So 10144 bytes for additional images, 3359 for mipmap plugin.

**Comment by pixelzoom** [comment] 2015-07-14 20:01
Forgot about splash.svg. It's size increased from 7057 to 8834 bytes.

**Comment by pixelzoom** [comment] 2015-07-14 20:02
Forgot about splash.svg. It's size increased from 7057 to 8834 bytes. But that's not related to mipmap, and it's the same splash.svg used in both of the hookes-law builds above.

**Comment by pixelzoom** [comment] 2015-07-14 20:06
Rendering quality has a thumbs up from everyone.
Size increase has been deemed acceptable.

I believe that's everything. Closing.

**Closed by pixelzoom** 2015-07-14 20:06 UTC
Labels: Summer 2015 redeploy
