### ISSUE TITLE
Move window.simDisplay to window.phet.simDisplay

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/joist#201] opened 2015-01-29 19:58 UTC
Check for other globals on Sim.js

**Comment by samreid** [comment] 2015-02-01 05:55
May be related to https://github.com/phetsims/tasks/issues/160

**Comment by pixelzoom** [comment] 2015-02-01 05:58
This is a duplicate of phetsims/tasks#160 and has been done.

**Closed by pixelzoom** 2015-02-01 05:58 UTC
Labels: enhancement
