### ISSUE TITLE
Chrome beta bottom tab sizing issue. 

### ISSUE THREAD

**Issue by orejolaphet** [phetsims/joist#141] opened 2014-07-24 20:02 UTC
Tested on windows 8 with Chrome 37.0.2062.20 beta-m

It seems that multi-scene sims have an issue with the bottom tab. That is the text for each scene is cut of at the bottom of the window.

![untitled](https://cloud.githubusercontent.com/assets/5631059/3693950/62abd1fa-136d-11e4-87ce-cf79e314ab35.png)
![untitled2](https://cloud.githubusercontent.com/assets/5631059/3693951/65b043b8-136d-11e4-97ee-0e74c4e24dda.png)

**Comment by jonathanolson** [comment] 2015-05-23 04:36
Can't reproduce on Chrome 45 (Win7), @orejolaphet, can you confirm if this is still an issue, since it was reported so long ago?

**Comment by ariel-phet** [comment] 2015-05-28 05:19
All working fine on both win 7 and win 8 for latest chrome  (43.0.2357.81). I checked several sims on both platforms. Closing

**Closed by ariel-phet** 2015-05-28 05:19 UTC
Labels: high-priority, Summer 2015 redeploy
