### ISSUE TITLE
Closing a dialog in the state wrapper leads to a dimmed downstream sim

### ISSUE THREAD

**Issue by samreid** [phetsims/joist#849] opened 2022-08-27 23:32 UTC
Discovered in https://github.com/phetsims/circuit-construction-kit-common/issues/867.  After closing the preferences dialog in the state wrapper, the downstream Preferences Dialog closes, but the semi-transparent overlay is still there.

<img width="556" alt="image" src="https://user-images.githubusercontent.com/679486/187051463-bc7913bc-4d94-4138-b782-4d56be7088df.png">

@jessegreenberg can you please take a look?

**Comment by marlitas** [comment] 2022-08-29 18:30
@samreid and I did some exploration.

We learned:
- dispose is called in the downstream sim, but not in the upstream
- hidePopup is called in the upstream, but not in the downstream

Questions:
- In the upstream sim, when the preferences dialog is clicked out of/ exited, do we want to dispose or keep in memory?

**Comment by zepumph** [comment] 2022-08-30 23:23
This was a regression caused by https://github.com/phetsims/axon/issues/409. @samreid and I were able to work it out. Basically, on dispose of a Dialog, we are calling `isShowingProperty.value = false`, which the calles `hidePopup` via a listener. This was no longer happening because of this code:

https://github.com/phetsims/axon/blob/b5c62d90476a1e9c2684bbb71ffa6183b5c775a5/js/ReadOnlyProperty.ts#L230-L236

Because this Property is instrumented. The solution is to not consider dynamic element clearing (occurring on `onBeforeSetState` as part of `this.isSettingPhetioStateProperty: true` territory. Commits above. @marlitas would you like to spot check? Feel free to close.

**Comment by marlitas** [comment] 2022-09-02 15:29
Spot checked the commits, and all looks good to me. I'm not sure I'm fully following the order of things that caused the bug, but the explanation and fix seems reasonable. Closing!

**Closed by marlitas** 2022-09-02 15:29 UTC
Labels: dev:phet-io, status:ready-for-review
