### ISSUE TITLE
Long Title strings off center in home screen

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/joist#645] opened 2020-07-23 22:01 UTC
Found during https://github.com/phetsims/QA/issues/514. pH issue made in https://github.com/phetsims/ph-scale/issues/184.
This issue seems to be independent of platform. When strings are long, the title text on the home screen seems to be further to the left than center. Unsure if this ended up in any published sims.
![longoffcenter](https://user-images.githubusercontent.com/41024075/88342933-9661b780-ccfd-11ea-8563-84cb58df57f2.png)
Assigning @samreid due to recent Joist work. Please reassign as appropriate.

**Comment by pixelzoom** [comment] 2020-07-23 22:07
@arouinfar @kathy-phet does this block publication of pH Scale?

**Comment by samreid** [comment] 2020-07-26 20:22
I removed a line that looked like a prior way of addressing maxWidth.  The title already specifies `maxWidth` as a constructor option, so the line I deleted was extraneous, and since it appeared after centering, it was causing incorrect layout.  @ariel-phet can you please recommend a reviewer for this minor change?

**Comment by ariel-phet** [comment] 2020-07-27 17:44
@pixelzoom this issue does not block publication of pH scale. Could you quickly review @samreid's change.

**Comment by pixelzoom** [comment] 2020-07-27 18:01
I verified the fix.  

Even though it's not blocking, I'm going to cherry-pick for ph-scale so that we can resolve phetsims/ph-scale#184.

**Comment by pixelzoom** [comment] 2020-07-27 18:08
Cherry-picked to ph-scale and ph-scale-basics 1.4 branches.

This also affects MAL RC.  Assigning to @ariel-phet and @jessegreenberg to decide whether to cherry-pick there.

**Comment by ariel-phet** [comment] 2020-07-28 01:15
@jessegreenberg up to you if you want to cherry-pick. This is a minor aesthetic issue in my opinion, but if it is only a couple of minutes to do it might be worth it. 

Whether you cherry pick or not, please note here and then close the issue.

**Comment by jessegreenberg** [comment] 2020-07-29 21:24
Looks like it wouldn't take much time to cherry-pick, but since molecules-and-light is a single screen sim and doesn't show a home screen it should not be impacted by this issue at all so I am going to continue without.

Closing this issue.

**Comment by KatieWoe** [comment] 2020-08-07 18:16
This seeps to happen in https://github.com/phetsims/QA/issues/525

**Comment by pixelzoom** [comment] 2020-08-07 18:20
@KatieWoe can you please check in master?  If this is not fixed in master, then what I cherry-picked for phetsims/ph-scale#184 won't be sufficient.  Or perhaps it's fixed in master and just hasn't been cherry-picked to SOM.

**Comment by KatieWoe** [comment] 2020-08-07 18:24
Actually, now that I'm looking at it more, this is pretty weird. I don't see it on Win 10 Chrome, but I am seeing it on Mac 10.12 Safari. @jbphet let me know if pairing would help with this issue.

**Comment by pixelzoom** [comment] 2020-08-07 18:26
Yes, master looks different on different browsers.

macOS + Chrome + Firefox look OK:

<img width="920" alt="screenshot_459" src="https://user-images.githubusercontent.com/3046552/89676359-c8038280-d8a8-11ea-844b-2382deb61317.png">

macOS + Safari looks shifted to the left:

<img width="787" alt="screenshot_461" src="https://user-images.githubusercontent.com/3046552/89676554-1749b300-d8a9-11ea-9b16-45d213c45cf0.png">

Reopening phetsims/ph-scale#184.  @jessegreenberg and @jbphet FYI in case you need to do anything for MAL and SOM.

Back to @samreid with high priority.

**Comment by samreid** [comment] 2020-08-07 18:41
I'm seeing the same thing, Mac/Chrome above, Mac/Safari below:

![image](https://user-images.githubusercontent.com/679486/89677825-58db5d80-d8ab-11ea-92d6-ecb3c7fa8be4.png)

**Comment by samreid** [comment] 2020-08-07 18:47
Using the scenery inspector, it seems the title text has incorrect bounds on Safari.

![image](https://user-images.githubusercontent.com/679486/89678245-19614100-d8ac-11ea-8fa4-530d0a92c234.png)

@jonathanolson can you please advise?

**Comment by KatieWoe** [comment] 2020-08-07 22:55
Noting that this shows up in mobile safari as well.

**Comment by jbphet** [comment] 2020-08-10 21:11
I just tested [the current States of Matter RC version](https://phet-dev.colorado.edu/html/states-of-matter/1.2.0-rc.1/phet/states-of-matter_en_phet.html) on a Macbook Air running 10.12.6, and I can see the the title is off center under normal circumstances (i.e. not just when testing long strings).  Here is a screen shot:

![som-off-center-title](https://user-images.githubusercontent.com/3082831/89831625-6434c000-db1b-11ea-97f6-d1d5e1143fdf.png)

If the fix is simple, I'd like to pull it in to the RC branch before publishing.

**Comment by jbphet** [comment] 2020-08-10 21:22
I tested the [current SOM RC](https://phet-dev.colorado.edu/html/states-of-matter/1.2.0-rc.1/phet/states-of-matter_en_phet.html) on Safari using the nominal (non long string) case, and it looks fine.  Since a title this long is unlikely to occur, and since the consequences are minor if it were to happen, I'm going to deem this non-blocking for the RC and unassign myself.

**Comment by jessegreenberg** [comment] 2020-08-10 21:27
> https://github.com/phetsims/joist/issues/645#issuecomment-670650086

Thanks, but MAL is a single screen sim so there isn't anything to do for that sim.

**Comment by pixelzoom** [comment] 2020-08-10 23:52
I'll give this another day to be fixed before I punt on it for ph-scale 1.4 and ph-scale-basics 1.4 RCs.

**Comment by samreid** [comment] 2020-08-11 13:32
I tested ph scale in safari and did not see a problem with the bounds:

![image](https://user-images.githubusercontent.com/679486/89903306-ba017a80-dba4-11ea-994b-8ad7f93a78a6.png)

I wonder if Safari is sometimes giving bounds to a LTR RTL directive character?

**Comment by samreid** [comment] 2020-08-11 13:37
The problem also disappears when I switch the font from `'Century Gothic, Futura';` to `monospace`:

![image](https://user-images.githubusercontent.com/679486/89903897-78bd9a80-dba5-11ea-9b93-780a80aac61f.png)

A reminder to myself that I had to clear Safari cache when testing this.

**Comment by samreid** [comment] 2020-08-11 13:41
Based on the statistics in https://www.cssfontstack.com/ I tried Verdana and it did not have the bounds problem.

**Comment by pixelzoom** [comment] 2020-08-11 16:09
Punting on this issue for pH Scale 1.4, closing https://github.com/phetsims/ph-scale/issues/184 as "won't fix".

**Comment by arouinfar** [comment] 2020-08-15 04:05
Relevant to https://github.com/phetsims/QA/issues/528, though I don't think it's very critical @chrisklus.

**Comment by jonathanolson** [comment] 2020-08-17 17:16
This seems to be specific to the Futura font (from what I'm finding), and some characters throw things off more than others:

![image](https://user-images.githubusercontent.com/480878/90424206-f76d7880-e07a-11ea-9697-6a021a990c7c.png)

@ariel-phet should I look into this further, to see whether it's a Scenery-side bug, or a Safari-side bug? Other fonts could also work around the issue.

**Comment by ariel-phet** [comment] 2020-08-17 20:04
@jonathanolson I think we should just use a different font. So lets make sure the specified fonts and fall back do not exhibit the problem. Not worth looking into if it is a scenery/browser bug if using different fonts does an acceptable work around.

**Comment by samreid** [comment] 2020-08-17 20:07
For @jonathanolson's reference: During https://github.com/phetsims/scenery-phet/issues/616 @ariel-phet and I consulted https://www.cssfontstack.com/ to see which platforms have which fonts.  But we aren't sure where those percentages came from.

**Comment by jonathanolson** [comment] 2020-08-17 20:19
Sounds like a plan. I saw I'm assigned back, should I be looking into replacement fonts?

**Comment by ariel-phet** [comment] 2020-08-18 02:44
@jonathanolson yes, please look into replacement fonts

**Comment by jbphet** [comment] 2020-10-07 14:49
I'm not sure why this was assigned to me, and I asked @KatieWoe, and she couldn't recall either.  It sounds like @jonathanolson is on it, so I'm unassigning myself.

**Comment by zepumph** [comment] 2021-07-19 15:20
This issue was marked as high priority. @jonathanolson can you please comment on the current status of things?

**Comment by jonathanolson** [comment] 2021-07-19 17:15
High on my project board, and I'll need to look through a variety of fonts to see what would have proper browser support. Presumably then I'll propose a few options and see what works for the sim design.

**Comment by jonathanolson** [comment] 2022-09-20 01:31
Adjusted the font family in PhetFont, and I added a `?fontFamily=` query parameter to test out different fonts. `Helvetica Neue` used to be a default for macOS and has a good appearance for Safari (stretches to the full amount). I added the typical backup fonts for it, including Arial in the chain.

@kathy-phet and @KatieWoe, can you see if this works, see if it looks good, and possibly try out alternative fonts with the query parameter?

**Comment by KatieWoe** [comment] 2022-09-21 19:10
Things looked ok on my end.

**Comment by chrisklus** [comment] 2022-09-26 16:02
I think this issue may be causing some layout issues in NumberPlay, and I suspect many other sims are affected as well. It seems like there's a lot riding on the specific family of PhetFont, so likely shouldn't be changed without lots of pixel testing.

Please compare screen 3 and the bottom right panel of screen 5 of these dev versions: 
Pre-font family change: https://phet-dev.colorado.edu/html/number-play/1.1.0-dev.3/phet/number-play_en_phet.html
Post-font family change: https://phet-dev.colorado.edu/html/number-play/1.1.0-dev.4/phet/number-play_en_phet.html

Adding blocks-publication label.

**Comment by kathy-phet** [comment] 2022-09-26 16:22
Can you post screenshots @chrisklus ? I don't see any changes in screen 3, or bottom right panel of screen 5

**Comment by chrisklus** [comment] 2022-09-26 16:46
It's easiest to compare if you click on each of these to open in their own tab. Most notably, the new font doesn't vertically center symbols like <, = , and >. It looks like number characters are slightly lower too, causing misalignment with the arrow buttons in the second screenshot.

before:

![Number Play screenshot (3)](https://user-images.githubusercontent.com/5618316/192333078-322257f6-6aad-469a-9627-f3fa5b054e40.png)

after:

![Number Play screenshot (4)](https://user-images.githubusercontent.com/5618316/192333378-e0806767-3312-4fca-8dbc-4d5ab1ee136c.png)

before:

![Number Play screenshot (1)](https://user-images.githubusercontent.com/5618316/192333322-e51fb330-e958-4e47-a93d-7ff54a8d18a1.png)

after:

![Number Play screenshot](https://user-images.githubusercontent.com/5618316/192333182-7d7c3797-6c65-4222-99b9-aa48233e4447.png)

**Comment by kathy-phet** [comment] 2022-09-26 21:25
On a PC, just reporting that I don't see the font offset you are seeing on the mac. 
Old: 
![image](https://user-images.githubusercontent.com/5096804/192383425-a8c93e5e-b57d-411e-a52c-96869c69ac64.png)
New:
![image](https://user-images.githubusercontent.com/5096804/192383515-49672a7d-313b-4bd9-8fb5-81aa09547abf.png)

**Comment by jonathanolson** [comment] 2022-09-27 00:02
This is happening on my system, with the "Helvetica Neue" font on macOS. It does NOT happen with Arial. Perhaps we should choose another common font?

**Comment by KatieWoe** [comment] 2022-09-27 19:20
I'm seeing this in https://github.com/phetsims/qa/issues/838 (Win 11 Chrome). It also seems that this can throw off icons such as those in the nav bar. @samreid let me know if you want this as a separate issue for the GaO rc.
RC:
<img width="292" alt="off" src="https://user-images.githubusercontent.com/41024075/192616284-c1c403b5-37a3-46a6-ac48-3aa0fd6ae660.png">
Published:
<img width="286" alt="onn" src="https://user-images.githubusercontent.com/41024075/192616344-680853fd-111c-4e81-ad6e-72ef910fea1e.png">

**Comment by samreid** [comment] 2022-09-28 00:16
Yes, a sim-specific issue would be great so we can track cherry-picking & maintenance, thanks!

**Comment by samreid** [comment] 2022-10-04 17:30
Probably not related to https://github.com/phetsims/gravity-and-orbits/issues/448

**Comment by samreid** [comment] 2022-10-05 15:36
@marlitas and I reviewed this today in the context of the Gravity and Orbits RC.1 for https://github.com/phetsims/qa/issues/838.  It seems the title font is corrected by the new font, and the problem @chrisklus pointed out mainly affects mathematical symbols which do not appear in Gravity and Orbits. We reproduced the problem in number play and confirmed those math symbols do have incorrect looking bounds:

<img width="412" alt="image" src="https://user-images.githubusercontent.com/679486/194101806-68a48be2-d9e4-4faa-bac0-d9cab7c6db95.png">

**Comment by samreid** [comment] 2022-10-05 16:21
In discussion with @marlitas and @arouinfar, we think this font change may have also caused https://github.com/phetsims/scenery/issues/1458

**Comment by jonathanolson** [comment] 2022-10-06 16:25
Should we potentially revert the font change? Are we able to use the query parameter to figure out what might work in all of these cases?

**Comment by samreid** [comment] 2022-10-06 16:40
Should those math symbols be translatable?  Maybe sims should be using `MathSymbolFont` for that?  Or even `MathSymbols`?

**Comment by zepumph** [comment] 2022-10-20 17:20
@chrisklus can you comment on the blocking status of this issue?

**Comment by zepumph** [comment] 2022-10-27 19:08
@kathy-phet, "I would say this is high priority because it is blocking number play."

@kathy-phet: "Is it just the math symbols that are off center?"


We are not sure. We will reach out to @chrisklus.

**Comment by chrisklus** [comment] 2022-10-27 19:18
Sorry - it is math symbols most noticeably, but numbers and regular are sitting a little low, too. Compare the two Compare screen screenshots from https://github.com/phetsims/joist/issues/645#issuecomment-1258333234 and you'll see the math symbols most noticeable off, but the numbers in the total are a bit low and no longer vertically centered. Also notice the comparison statement and sim title are a little bit lower.

For this screen of Number Play, I think just the math symbols and total numbers are blocking, but given that general text is low too, I have to think there are plenty of pixel-perfect text alignments in many other sims that are now a little off in a noticeable way.

Should we close this issue and open a side issue for the alignment problems?

**Comment by zepumph** [comment] 2022-10-27 19:35
>Should we close this issue and open a side issue for the alignment problems?

That would be very helpful! Can you please mark as high priority and assign to KP and JO?

**Comment by chrisklus** [comment] 2022-10-27 23:08
Thanks! Sure thing, I opened https://github.com/phetsims/scenery-phet/issues/785. Closing!

**Closed by chrisklus** 2022-10-27 23:08 UTC
Labels: type:bug, priority:2-high, status:blocks-publication
