### ISSUE TITLE
Full Screen on iOS 12

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/joist#524] opened 2018-09-25 21:22 UTC
Found during https://github.com/phetsims/QA/issues/194
Affects published sims as well.

When in a sim on an iOS 12 device you can open the phet menu and select full screen.  This option is missing for other instances of iOS.  In this full screen mode you can see an odd graphical issue in which the bottom bar is raised from the bottom of the screen.  This is fixed by changing the orientation.  Discussion on Slack indicates that Full Screen option itself is due to iOS 12 specifically supporting it now.  Bottom bar and orientation issue is similar to the problem encountered on iOS sims when an extra tab is added or taken away.

More concerning, I was unable to escape full screen at one point.  Full screen is left normally by either pressing an X in the upper left corner or by opening the phet menu and unselecting full screen.  Neither method worked.  Tapping in certain places brought up a message saying "You are trying to type in full screen mode.  Exit full screen?"  However, selecting this option did not let me leave either.  I had to use the home button to leave safari entirely and close safari to fix this.  I have been unable to recreate this problem as of yet.  Will update if it shows up again or I find a reproducible method.

Screenshots:
![img_1309](https://user-images.githubusercontent.com/41024075/46046038-d6918800-c0dc-11e8-8fc9-b0ca3fc2ca21.PNG)
![img_1310](https://user-images.githubusercontent.com/41024075/46046039-d6918800-c0dc-11e8-80e3-2ad48fe8e792.PNG)

@ariel-phet for severity and next steps.

**Comment by ariel-phet** [comment] 2018-09-25 21:53
Tagging for dev meeting to see what some options are here.

**Comment by KatieWoe** [comment] 2018-09-25 22:15
@jonathanolson @ariel-phet 
I believe I have a method of reproducing the "unable to escape full screen" fairly reliably.
1. Go to the sim
2. Open phet menu and select Full Screen
3. Use your finger to drag a non-interactable part of the sim.  You should see the normal sim "behind" it.  Don't release the sim.
4. Drag the sim back up to its original position and release.  If you release in another position full screen will be left instead.
5. Attempt to leave full screen.  You will be unable to.
6. To fix double click the home button and close safari.  This will cause the page to reload when you open safari again, and it will not be in full screen.

**Comment by KatieWoe** [comment] 2018-09-25 22:27
Video of issue.
https://drive.google.com/file/d/1YSXgv6EmIcypuqeFoaTtWCu1yt9c2LPc/view?usp=sharing

**Comment by samreid** [comment] 2018-09-27 04:32
I'm not sure what the problem is and couldn't find others reporting this problem in a quick search.  Some possibilities about how we might proceed:

1. Assign one or more developers an iOS 12 iPad and time to investigate and explore/identify options.  Is there a programmatic way to un-full-screen?  Why isn't it working?  What's happening when the sim "drags" in front of itself?
2. Create a small self-contained example (not using a PhET sim) that isolates/demonstrates this problem, and submit it as a bug report to Apple.  Sometimes an isolated test case can also help us understand what's going wrong or possible workarounds.
3. Decide that it's a rare enough problem and doesn't need to be addressed at all
4. Eliminate the full screen button when iOS 12 mobile safari is detected.

I can see code in PhetMenu.js that prevents the fullscreen button from appearing in the iOS app, so that's safe.

**Comment by samreid** [comment] 2018-09-27 19:05
Based on discussion in dev meeting, I pushed a fix that removes the fullscreen button from mobile safari.  @KatieWoe can you please test on master?  After that checks out, @jonathanolson will coordinate with @samreid for a maintenance release.

**Comment by jbphet** [comment] 2018-09-27 19:06
In today's dev meeting it was decided that this should go out in a maintenance release.  There is currently and RC in progress for John Travoltage, and the branch is 1.5.  This should be patched too if it hasn't been published by the time this maintenance release occurs.

**Comment by jessegreenberg** [comment] 2018-09-27 19:08
Like https://github.com/phetsims/joist/issues/524#issuecomment-425208226 rutherford-scattering is also in RC testing and the 1.1.0 branch will need this too.

**Comment by samreid** [comment] 2018-09-27 19:27
Can you please test that the Fullscreen button is still present on other platforms?

**Comment by KatieWoe** [comment] 2018-09-27 20:47
Tested on Win 10 chrome and edge, and on Mac OS 10.13 safari.  All looks well.

**Comment by KatieWoe** [comment] 2018-09-28 16:28
Linking to JT rc as reminder.  https://github.com/phetsims/QA/issues/196

**Comment by KatieWoe** [comment] 2018-10-04 17:48
Just checked chrome and firefox on iOS 12 iPad and full screen does not show up as an option either in sims before or after the fix.

**Comment by samreid** [comment] 2021-02-15 17:43
I spot checked a few sims on iPad 7 and saw that there was no fullscreen button.  I also tested master and saw it was OK too, closing.

**Closed by samreid** 2021-02-15 17:43 UTC
Labels: type:bug, type:question
