### ISSUE TITLE
Quick info alerts interrupted with Chrome 109

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/joist#898] opened 2023-01-12 20:34 UTC
**Test device**
MacBook Air (m1 chip)

**Operating System**
13.1

**Browser**
Chrome Version 109.0.5414.87

**Problem description**
For https://github.com/phetsims/qa/issues/879, on the newest version of chrome (109....) Quick Info alerts will not play when interrupted. 

**Steps to reproduce**
1. Turn on Voicing
2. Press Overview
3. Before Voicing is done, press Details --> Nothing is read. You have to press Details 2 more times for Voicing to start again. 

I didn't see this issue on published GFLB and JT. When I tried GFLB on master, it happened there as well. 

**Visuals**

https://user-images.githubusercontent.com/87318828/212174873-95fb45f7-446c-4094-9e48-a3c92ec9b88f.mov

<details>
Troubleshooting information:
!!!!! DO NOT EDIT !!!!!
Name: ‪Quadrilateral‬
URL: https://phet-dev.colorado.edu/html/quadrilateral/1.0.0-dev.73/phet/quadrilateral_all_phet.html
Version: 1.0.0-dev.73 2023-01-08 23:48:12 UTC
Features missing: applicationcache, applicationcache, touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36
Language: en-US
Window: 1480x781
Pixel Ratio: 1.7999999523162842/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 31 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {}
</details>

**Comment by jessegreenberg** [comment] 2023-01-12 22:53
It is caused by this line: 

https://github.com/phetsims/joist/blob/7b833a663f0c735e5e4a254ace9a1a693a5835ef/js/toolbar/VoicingToolbarItem.ts#L226-L228

**Comment by jessegreenberg** [comment] 2023-01-12 23:11
I should note this is happening in master and published RaP but NOT in older sims. That made me suspect https://github.com/phetsims/utterance-queue/issues/97, but commenting out those changes did nothing.

**Comment by jessegreenberg** [comment] 2023-01-12 23:36
When I comment out this line, the problem goes away:

https://github.com/phetsims/utterance-queue/blob/1c2007a9c3b1123ebba1ca2014ac0a72b76ba314/js/SpeechSynthesisAnnouncer.ts#L605-L607

And that matches this bug showing up in a platform update, I could see Chrome starting to fire BOTH the `error` and `cancel` event for some reason.

**Comment by jessegreenberg** [comment] 2023-01-13 16:58
Here is some logging output from the buggy case demonstrating why not removing the error event listener is a problem. Logging starts after pressing the second button:
![image](https://user-images.githubusercontent.com/6396244/212375479-926acb87-818f-4bf7-97e4-19c4dae25fb0.png)

This shows that the `error` event for the first `SpeechSynthesisUtterance` happened asynchronously and after the second `Utterance` had been added to the `UtteranceQueue`.

**Comment by jessegreenberg** [comment] 2023-01-13 17:11
@Nancy-Salpepi can you please confirm that this is fixed in master?

**Comment by Nancy-Salpepi** [comment] 2023-01-13 18:22
it is indeed fixed @jessegreenberg

**Comment by jessegreenberg** [comment] 2023-01-13 18:39
Great, thanks! Closing.

**Closed by jessegreenberg** 2023-01-13 18:39 UTC
Labels: type:bug, status:blocks-publication, dev:voicing

**Comment by zepumph** [comment] 2023-01-25 18:44
For https://github.com/phetsims/friction/issues/327 we just need to cherry pick https://github.com/phetsims/utterance-queue/commit/2f64e9580771087750bdc3f1c5ac778abb089f1f
