### ISSUE TITLE
CCKDC is slowing down in LoL

### ISSUE THREAD

**Issue by phet-steele** [phetsims/joist#447] opened 2017-10-18 20:55 UTC
Slack conversation:

**Steele Dalton**

Looks like setting up a complex circuit and pausing/resuming in LoL about 150 times really slows the sim down…..what do you think?

**Sam Reid**

that’s interesting, let me clarify
if you set up a complex circuit, performance is good
then you pause/resume once in LOL and performance is still good
then you pause and resume 30 times in LOL and performance is somewhat degraded
then you pauses and resume 150 times in LOL and performance is significantly degraded.  Like that?

**Steele Dalton**

I haven’t graphed this or anything, nor have I checked intermediate values between 0-150, but yes, something like that is happening.

**Sam Reid**

We need to look into it, can you please create a Joist issue?  Maybe see if something similar happens in other sims?

**Steele Dalton**

I tried, didn’t see anything immediately similar
lol
replace “150” with “10"

**Sam Reid**

Oh that will be much easier to test and isolate!
_end_

Complex circuit in question:
<img width="1005" alt="screen shot 2017-10-18 at 2 40 24 pm" src="https://user-images.githubusercontent.com/5863899/31742102-d58010f2-b413-11e7-929f-104dcd0e54a9.png">

Interacting becomes incredibly difficult at 150 pauses, but of course you can start to see results at 10 (I hope).

Seen on macOS 10.12.6 Chrome. For phetsims/QA/issues/55.
URL: https://www.colorado.edu/physics/phet/dev/html/circuit-construction-kit-dc/1.0.0-rc.1/circuit-construction-kit-dc_en.html?legendsOfLearning
Version: 1.0.0-rc.1 2017-10-17 18:05:58 UTC
Features missing: touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36
Language: en-US
Window: 1920x1014
Pixel Ratio: 2/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 32 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 80)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {"assert":{"sha":"928741cf","branch":"HEAD"},"axon":{"sha":"8a8ff7d2","branch":"HEAD"},"babel":{"sha":"0b5a4452","branch":"master"},"brand":{"sha":"cfca902d","branch":"HEAD"},"chipper":{"sha":"b8a3c09a","branch":"HEAD"},"circuit-construction-kit-common":{"sha":"11736e99","branch":"HEAD"},"circuit-construction-kit-dc":{"sha":"5cbdc391","branch":"HEAD"},"dot":{"sha":"84bc5146","branch":"HEAD"},"joist":{"sha":"92b186e2","branch":"HEAD"},"kite":{"sha":"067109a8","branch":"HEAD"},"phet-core":{"sha":"054b2d6d","branch":"HEAD"},"phetcommon":{"sha":"b13138d2","branch":"HEAD"},"query-string-machine":{"sha":"c74e454e","branch":"HEAD"},"scenery":{"sha":"c9c3052a","branch":"HEAD"},"scenery-phet":{"sha":"124c1c25","branch":"HEAD"},"sherpa":{"sha":"0d590744","branch":"HEAD"},"sun":{"sha":"082fee37","branch":"HEAD"},"tandem":{"sha":"98e9917c","branch":"HEAD"},"twixt":{"sha":"a2eaa10a","branch":"HEAD"}}

**Comment by samreid** [comment] 2017-10-19 02:15
I added this code to LegendsOfLearningSupport.js and was easily able to reproduce the problem on Mac/Chrome:

```js
    setTimeout( function() {
      console.log( 'hello' );

      for ( var i = 0; i < 100; i++ ) {

        //pause
        sim.boundRunAnimationLoop();
        sim.activeProperty.value = false;

        //resume
        sim.activeProperty.value = true;
      }
    }, 5000 );
```

**Comment by samreid** [comment] 2017-10-19 02:15
Using the above code I replicated the problem in Function Builder.

**Comment by samreid** [comment] 2017-10-19 02:19
The profiler shows an unusual amount of time spent in Display.updateSubtreeDisposed:

![image](https://user-images.githubusercontent.com/679486/31751232-8c9c3b4e-b441-11e7-99ad-84776b8bc920.png)

**Comment by samreid** [comment] 2017-10-19 02:21
The problem is that requestAnimationFrame is being called again on each pause.  So if you pause 5 times, there will be 5 simulation steps per animation frame.

**Comment by samreid** [comment] 2017-10-19 02:29
One solution would be to move the bottom half of Sim.runAnimationLoop to a new function, and call that from LegendsOfLearningSupport.  @pixelzoom I'd like to run this past you before working on it.  You can reproduce the problem by adding https://github.com/phetsims/joist/issues/447#issuecomment-337779804 to LegendsOfLearningSupport.js then launching function-builder with ?legendsOfLearning.  Then drag an object and after 5 seconds you will see it slow down.

**Comment by samreid** [comment] 2017-10-19 02:32
We may need to make maintenance releases to fix affected simulations.

**Comment by jonathanolson** [comment] 2017-10-19 16:00
When the sim gets paused, should we use `cancelAnimationFrame` to stop the loop (so we can restart it easily with a new `requestAnimationFrame` later?)

**Comment by samreid** [comment] 2017-10-19 16:51
@jonathanolson suggestion sounds like the right solution to me, but I would want to confirm that nothing is relying on the sim updating the display while paused.

**Comment by pixelzoom** [comment] 2017-10-19 16:58
I'm not at all familiar with the LoL project, and not totally sure what "the bottom half on Sim.runAnimationLoop" is - do you mean the second `if` statement?

Does @jonathanolson's suggestion (https://github.com/phetsims/joist/issues/447#issuecomment-337954681) make it unnecessary to "move the bottom half of Sim.runAnimationLoop to a new function"?

**Comment by pixelzoom** [comment] 2017-10-19 17:02
I really don't understand this problem at all - why the frame rate is so high, why a lot of time is spent in Display.updateSubtreeDisposed.

**Comment by samreid** [comment] 2017-10-19 20:48
LegendsOfLearningSupport.js calls this code on pause: `sim.boundRunAnimationLoop();` . That schedules another animationFrame callback, but there is already another animation frame callback.  So the same callback would get called twice on the next animation frame.  This is because runAnimationLoop has this code:

```js
      if ( !this.destroyed ) {
        window.requestAnimationFrame( this.boundRunAnimationLoop );
      }
```

So if you pause it 100 times, then on the next animation frame, the `boundRunAnimationLoop` will get called 101 times.  This probably accounts for all the extra scenery time.

**Comment by samreid** [comment] 2017-10-22 00:57
Unassigning myself until I hear back from @pixelzoom

**Comment by pixelzoom** [comment] 2017-10-23 16:27
I have no familiarity with LoL, and now have only a vague understanding of the problem.  Since @jonathanolson recommended a solution that @samreid thinks is "the right solution", I suggest that they collaborate on resolving this.

**Comment by jonathanolson** [comment] 2017-10-27 01:53
I don't think the sim.boundRunAnimationLoop should be there on further inspection. I removed it (things work normally now).

@samreid can you review?

**Comment by samreid** [comment] 2017-10-27 03:36
@jonathanolson thanks, you got to the heart of the matter.  I tested your change in http://harness.legendsoflearning.com/ with CCK-DC from master and after many pause/resumes it is still behaving correctly.  We should discuss with @ariel-phet if we are going to perform maintenance releases of any existing LOL sims, and I'll roll this fix into RC.2 for CCK.

**Comment by samreid** [comment] 2017-10-27 04:08
Will be ready for RC testing in https://github.com/phetsims/QA/issues/59

**Comment by phet-steele** [comment] 2017-10-27 16:29
Looks kosher in https://github.com/phetsims/QA/issues/59. It's easy to test with `&profiler` to verify we aren't getting too high an fps (the root problem) rather than just testing performance. CCKDC stayed at 60 fps through multiple pauses and resumes and didn't climb to 60000 fps.

**Comment by ariel-phet** [comment] 2017-10-27 18:26
In discussion with @samreid it sounds like this might be a good candidate for maintence releases on LoL sims (since it is a one line change, and not having the fix could affect sims that have a strong tie to the temporal model like PM and FAMB). However, there appears to be some confusion as to what sims are actually LoL sims...what sims LoL have been delivered, published, etc.

**Comment by ariel-phet** [comment] 2017-10-27 19:07
Ah, it appears there is a google doc with this info:

https://docs.google.com/spreadsheets/d/1umIAmhn89WN1nzcHKhYJcv-n3Oj6ps1wITc-CjWYytE/edit#gid=0

Looks like Projectile Motion, Pendulum Lab, FAMB, BAM, ESPB should all receive this update.

**Comment by samreid** [comment] 2017-10-27 19:39
I'll move to #450 and close this one.

**Closed by samreid** 2017-10-27 19:39 UTC
Labels: type:bug
