### ISSUE TITLE
standardize aspect ratio of custom layoutBounds

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/joist#542] opened 2018-12-04 00:04 UTC
From https://github.com/phetsims/graphing-quadratics/issues/121#issuecomment-443910148...

`ScreenView` (the top-level view component in joist) has an option for setting a custom `layoutBounds`.  When doing a direct port from Java, it's convenient (and less expensive) to use the layoutBounds from the Java sim, so that the sizes and positions of things (in the view, and possibly in the model) don't need to be adjusted.

If the custom layoutBounds don't have the same aspect ratio as the default ScreenView layoutBounds, then this can make the `?dev` query parameters less useful for other team members.  For example, in https://github.com/phetsims/graphing-quadratics/issues/121#issuecomment-443857113, @arouinfar said:

> I often use ?dev to make sure I'm taking screenshots for things like teacher tips and sim primers at the appropriate aspect ratio. I had no idea that some Java ports retained their original aspect ratio.

So the proposal is to consider requiring custom layoutBounds to have the same aspect ratio as ScreenView's default layoutBounds (within some tolerance).

**Comment by pixelzoom** [comment] 2018-12-04 00:04
ScreenView's default layoutBounds is:

`var DEFAULT_LAYOUT_BOUNDS = new Bounds2( 0, 0, 1024, 618 );`

Sims that currently have custom layoutBounds include:

acid-base-solutions: new Bounds2( 0, 0, 768, 504 )
area-builder: new Bounds2( 0, 0, 768, 464 )
arithmetic: new Bounds2( 0, 0, 768, 504 )
balancing-act: new Bounds2( 0, 0, 768, 504 )
balancing-chemical-equations: new Bounds2( 0, 0, 768, 504 )
balloons-and-static-electricity: new Bounds2( 0, 0, 768, 504 )
beers-law-lab, concentration: new Bounds2( 0, 0, 1100, 700 )
bending-light: new Bounds2( 0, 0, 834, 504 )
build-a-molecule: new Rectangle( 0, 0 1100, 679 )
build-an-atom: new Bounds2( 0, 0, 768, 464 )
color-vision: new Bounds2( 0, 0, 768, 464 )
coulombs-law: new Bounds2( 0, 0, 768, 464 )
curve-fitting:  new Bounds2( 0, 0, 768, 464 )
energy-skate-park-basics: new Bounds2( 0, 0, 834, 504 )
estimation: new Bounds2( 0, 0, 768, 464 )
example-sim: new Bounds2( 0, 0, 768, 464 )
faradays-law: new Bounds2( 0, 0, 834, 504 )
fluid-pressure-and-flow: new Bounds2( 0, 0, 768, 504 )
forces-and-motion-basics: new Bounds2( 0, 0, 981, 604 )
fraction-comparison: new Bounds2( 0, 0, 768, 504 )
friction: new Bounds2( 0, 0, 768, 504 )
graphing-lines, graphing-slope-intercept: new Bounds2( 0, 0, 1100, 700 )
graphing-quadratics: new Bounds2( 0, 0, 1160, 700 )
gravity-force-lab: new Bounds2( 0, 0, 768, 464 )
gravity-force-lab-basics: new Bounds2( 0, 0, 768, 464 )
isotopes-and-atomic-mass: new Bounds2( 0, 0, 768, 464 )
john-travoltage: new Bounds2( 0, 0, 768, 464 )
molarity: new Bounds2( 0, 0, 1100, 700 )
molecule-polarity: new Bounds2( 0, 0, 1100, 700 )
molecules-and-light: new Bounds2( 0, 0, 768, 504 )
neuron: new Bounds2( 0, 0, 834, 504 )
optics-lab: new Bounds2( 0, 0, 768, 504 )
ph-scale: new Bounds2( 0, 0, 1100, 700 )
protein-synthesis: new Bounds2( 0, 0, 834, 504 )
reactants-products-and-leftovers: new Bounds2( 0, 0, 835, 504 )
states-of-matter: new Bounds2( 0, 0, 834, 504 )
tambo-demo:  new Bounds2( 0, 0, 768, 504 )
wave-on-a-string: new Bounds2( 0, 0, 768, 504 )

**Comment by pixelzoom** [comment] 2018-12-04 00:14
ScreenView's default layoutBounds is:

`var DEFAULT_LAYOUT_BOUNDS = new Bounds2( 0, 0, 1024, 618 );`

.. which is aspect ratio = 1024/618 = 1.66

Here are all of the sims that use a non-default layoutBounds, grouped by bounds values.

**new Bounds2( 0, 0, 768, 504 ), aspect ration = 1.52**
acid-base-solutions 
arithmetic
balancing-act
balancing-chemical-equations
balloons-and-static-electricity
fluid-pressure-and-flow
fraction-comparison
friction
molecules-and-light
optics-lab
tambo-demo
wave-on-a-string

**new Bounds2( 0, 0, 768, 464 ), aspect ratio = 1.67**
area-builder
build-an-atom
color-vision
coulombs-law
curve-fitting
estimation
example-sim
gravity-force-lab
gravity-force-lab-basics
isotopes-and-atomic-mass
john-travoltage

**new Bounds2( 0, 0, 834, 504 ), aspect ratio = 1.65**
bending-light: 
energy-skate-park-basics: new Bounds2( 0, 0, 834, 504 )
faradays-law: new Bounds2( 0, 0, 834, 504 )
neuron: new Bounds2( 0, 0, 834, 504 )
protein-synthesis: new Bounds2( 0, 0, 834, 504 )
reactants-products-and-leftovers: new Bounds2( 0, 0, 835, 504 )
states-of-matter: new Bounds2( 0, 0, 834, 504 )
forces-and-motion-basics: new Bounds2( 0, 0, 981, 604 )

**new Bounds2( 0, 0, 1100, 700 ), aspect ratio = 1.57**
beers-law-lab, concentration
build-a-molecule
graphing-lines
graphing-slope-intercept
molarity
molecule-polarity
ph-scale

**new Bounds2( 0, 0, 1160, 700 ), aspect ratio = 1.66**
graphing-quadratics

**Comment by pixelzoom** [comment] 2018-12-04 17:04
So there are a large number of sims (see above) that have custom layoutBounds with aspect ratio that is different than the default.   The ones with aspect ratio ~1.65 and ~1.67 are presumably fine; the difference won't be visually significant.    The ones with aspect ratio ~1.52 and ~1.57 would need attention.  Graphing Quadratic was formerly in the ~1.57 category (see phetsims/graphing-quadratics#121) and the difference was significant enough that I addressed it.

**Comment by arouinfar** [comment] 2018-12-06 18:37
Thanks for opening this  issue @pixelzoom!

> ScreenView's default layoutBounds is:
`var DEFAULT_LAYOUT_BOUNDS = new Bounds2( 0, 0, 1024, 618 );`
.. with aspect ratio = 1024/618 = ~1.66

1024x618 is the resolution of a sim with the navbar on an iPad2, which is the standard we've been designing for in HTML5. On sim screens, layoutBounds does not include the navbar, so this is the appropriate aspect ratio. (If we included the navbar, the appropriate aspect ratio would be ~1.52, corresponding to the standard sim screenshot size of 1536x1008.)

During the design process, I also use layoutBounds to determine the layout of UI components. I think it's critical that layoutBounds are representative of our sim design standard, ~1.66 (sans navbar). If a sim has non-standard layoutBounds, UI layout will not be optimal.

**Comment by samreid** [comment] 2018-12-12 21:01
> When doing a direct port from Java, it's convenient (and less expensive) to use the layoutBounds from the Java sim, so that the sizes and positions of things (in the view, and possibly in the model) don't need to be adjusted.

Many of our sims have significant or nontrivial design changes--I would be surprised to see layout numbers from Java translating directly to HTML5.

All sims should be using exactly the same aspect ratio.

I'd like to take this one step further and argue that:

a) All new sim development should use the default ScreenView layoutBounds.

This will ensure consistency across our HTML5 codebase.  When a designer says, "move that over 10 pixels" it will mean the same thing in any simulation.

If we had the time, I'd even go one step further and argue that:

b) Legacy HTML5 sims should be altered so that they use the ScreenView.layoutBounds

We have never tried this and therefore don't know exactly how long it would take.  But it would make our codebase more consistent and issues like https://github.com/phetsims/friction/issues/65 nontrivial.

**Comment by pixelzoom** [comment] 2018-12-12 22:59
> Many of our sims have significant or nontrivial design changes--I would be surprised to see layout numbers from Java translating directly to HTML5.

I said "direct port from Java", which we have previously used to describe a sim that was ported with little or no design changes.  I've done many direct port -- Beer's Law Lab, Concentration, pH Scale, Acid-Base Solutions, RPAL, BCE, Graphing Lines, Molarity, Molecule Polarity... -- and they were all relatively inexpensive to move over because I didn't have to diddle with layout changes.   So while I agree that it would be nice to have uniformity of layoutBounds across all HTML5 sims, I'm not convinced that it's cost effective. 

> All sims should be using exactly the same aspect ratio.

Agreed.  I did this recently for Graphing Quadratics, and it's relatively easy.  I could probably do it for the rest of my sims in < 20 hours.

> a) All new sim development should use the default ScreenView layoutBounds.

Happy to do this for ports, if PhET is willing to incur the additional cost. 

> b) Legacy HTML5 sims should be altered so that they use the ScreenView.layoutBounds

The benefit/cost ratio for this would be very low.  Happy to do it if PhET desires, but I doubt that it will ever be a priority.

**Comment by samreid** [comment] 2018-12-12 23:33
> The benefit/cost ratio for this would be very low. Happy to do it if PhET desires, but I doubt that it will ever be a priority.

Can you speculate how long it would take to update one of your legacy simulations?

**Comment by pixelzoom** [comment] 2018-12-12 23:55
WAG 5-15 hours.

**Comment by pixelzoom** [comment] 2018-12-13 00:01
If a sim's layoutBounds were changed and you wanted everything to look the same, here are the obvious things that you'd need to change:

* model view transform
* initial position of all model elements
* initial position of all view components
* font sizes
* values for all "dimensional" options: lineWidth, lineDash, cornerRadius, margins, spacing,...

**Comment by pixelzoom** [comment] 2018-12-13 17:52
The main disadvantage to using custom layoutBounds seems to be with common-code UI components (like ResetAllButton), where we have a standard size, pointer areas, etc. that we want to use across all sims.   Imo, adjusting a handful of these components is significantly easier than changing layoutBounds for exists sims, or future ports. 

Standardizing aspect ratio, on the other hand, is relatively easy, and (I think) worth doing. See for example https://github.com/phetsims/graphing-quadratics/issues/121#issuecomment-443906407.

**Comment by samreid** [comment] 2018-12-13 18:05
Can we also require that new sims use the default layout bounds?

**Comment by pixelzoom** [comment] 2018-12-13 18:10
Sims that are not legacy ports should definitely use the default layoutBounds.   For ports, I think that PhET management needs to make that call, based on whether the benefits outweigh the costs (see https://github.com/phetsims/joist/issues/542#issuecomment-446790667).

**Comment by pixelzoom** [comment] 2018-12-30 03:11
If we're OK with standardizing existing sims on aspect ratio only, then...

* Sims with `Bounds2( 0, 0, 1100, 700 )` should be converted to `Bounds2( 0, 0, 1160, 700 )`.
* Sims with `Bounds2( 0, 0, 768, 504 )` should be converted to `Bounds2( 0, 0, 835, 504 )`.

**Comment by pixelzoom** [comment] 2019-01-16 21:11
This has been on the dev meeting agenda for way too long (12/6), so...

Proposal:

(1) For all new sims, use ScreenView's default `layoutBounds` unless there's a really good reason to use custom `layoutBounds`.   For direct ports a "really good reason" might include a large increase in the cost to adjust model & view to different coordinate frames.

(2) For any new sims that use non-default `layoutBounds`, the aspect ratio must match the default.

(3) For all existing sims with custom `layoutBounds` that have a non-default aspect ratio, adjust those `layoutBounds` to match the default aspect ratio.  Designers have indicated that this will make their job easier when preparing supplemental materials.  This includes 18 sims identified in https://github.com/phetsims/joist/issues/542#issuecomment-443920171 (those with aspect ratios 1.52 and 1.57).

(4) Add an assertion to `ScreenView` to verify that the aspect ratio of `options.layoutBounds` matches the aspect ratio of `DEFAULT_LAYOUT_BOUNDS` within some tolerance.  This will prevent future sims from reintroducing this problem.

For 1/17/19 dev meeting, please vote with thumbs up/down.  If thumbs down, please add a comment explaining what you don't like about this proposal.

**Comment by jonathanolson** [comment] 2019-01-17 16:49
I'm not quite clear on the advantage to adjusting sims with different aspect ratios. Is it just so ?dev will always be the same? (It is better to have the dev-tools open in Chrome so that it shows the actual pixel dimensions when resizing, and would be much more reproducible).

So... what is the downside of leaving things as-is?

**Comment by samreid** [comment] 2019-01-17 16:51
> So... what is the downside of leaving things as-is?

For example, new `ResetAllButton()` would have a different size in different sims.  Layout dimensions have different meaning in different sims.

**Comment by jonathanolson** [comment] 2019-01-17 17:04
> For example, new ResetAllButton() would have a different size in different sims. Layout dimensions have different meaning in different sims.

That would be an argument for making all of the layout bounds the same (instead of just making them have the same aspect ratio). I understand advantages of everything having identical layout bounds.

**Comment by oliver-phet** [comment] 2019-01-17 19:34
@arouinfar See the QA process for taking screenshots: https://github.com/phetsims/QA/wiki/QA-Book#screenshots
We've been using 1536x1008 for screenshots that adhere to the ipad bounds. You probably don't need this high of resolution for teacher tips, so any smaller aspect ratio would work too? 384 x 252?

**Comment by arouinfar** [comment] 2019-01-17 19:43
Thanks @oliver-phet. I've gone over this process with @KatieWoe awhile back, so a bigger motivator for standardizing the aspect ratio of the layoutBounds was that it would make it easier to optimize the sim layouts for an iPad. Designers assume that `?dev` is at an iPad aspect ratio, so it was problematic to discover that many sims were not following this expectation.

Glad to know that the default layoutBounds will be used going forward.

> You probably don't need this high of resolution for teacher tips, so any smaller dimensions at the same aspect ratio would work too? 384 x 252?

384x252 would almost assuredly be too small and would end up looking grainy. For Teacher Tips, I've always used the appropriate aspect ratio, without giving any particular care to the resolution. We can simply drag and drop screenshots into the Teacher Tips template, and they'll automatically get resized. 

Since the decision was to use the default layoutBounds, it doesn't seem like any further work needs to be done, so closing.

**Closed by arouinfar** 2019-01-17 19:43 UTC
Labels: design:general

**Comment by samreid** [comment] 2019-01-22 15:57
As far I recall, we also decided not to go back through old sims and update their layout bounds.
