### ISSUE TITLE
HomeScreen text is not dynamically centered for PhET-iO

### ISSUE THREAD

**Issue by zepumph** [phetsims/joist#600] opened 2020-02-01 02:44 UTC
The title and small/large screen button text is not centered when updated with PhET-iO (like in studio).

Discovered while working on https://github.com/phetsims/projectile-motion/issues/201

This also relates to the general proliferation of dynamic text updates discussed in 
https://github.com/phetsims/phet-io/issues/1551 and 
https://github.com/phetsims/phet-io/issues/1565

I think we probably want to do this, but it may be worth discussion?

![image](https://user-images.githubusercontent.com/6856943/73585784-14c95500-4451-11ea-93df-f6caef447023.png)

![image](https://user-images.githubusercontent.com/6856943/73585786-172baf00-4451-11ea-91d0-7f7589a9aafd.png)

![image](https://user-images.githubusercontent.com/6856943/73585797-362a4100-4451-11ea-80b3-3d1fb86f4bf9.png)

**Comment by zepumph** [comment] 2020-02-01 02:56
I tried to add:

```js

    text.on( 'bounds', () => {
      text.centerX = this.centerX;
    } );

```

To ScreenButton.js and it worked great for the large button, but not good for the small, and I'm unsure why.

**Comment by zepumph** [comment] 2020-02-01 03:02
I had more luck with the title node though. @samreid can you please review this half, and recommend how to proceed with ScreenButton?

**Comment by samreid** [comment] 2020-02-04 02:31
We may have more of a rewrite of ScreenButton as part of #601

**Comment by zepumph** [comment] 2020-02-13 22:11
Alright then, for the GFL branch I'm only going to update the title.

**Comment by zepumph** [comment] 2020-02-13 22:47
>Alright then, for the GFL branch I'm only going to update the title.

I didn't need to do this because there is no home screen for GFL... oops.

**Comment by zepumph** [comment] 2020-03-04 02:20
This may be much easier now that https://github.com/phetsims/joist/issues/601 has been done.

**Comment by samreid** [comment] 2020-06-16 21:53
I used Natural Selection to test changing the title in studio, and changing the large and small homescreen icon text.  All worked as expected.  The only thing I noticed is that the simulation name is under general.model but the screen name is just under screen (not under screen.model).  @chrisklus @zepumph is this by design?

**Comment by zepumph** [comment] 2020-06-19 01:07
That is a question for @chrisklus, who was much more involved in this round of joist design.

**Comment by chrisklus** [comment] 2020-06-22 22:34
The screen name was converted to a Property before the sim name. If I remember correctly, we put the screen name outside of model or view because it seemed most natural there, and the precedent was already set with activeProperty. When we converted the sim name to a Property, everything in general was nested under into model, view, or controller, so we picked model.

I'd be fine with moving screen.nameProperty to screen.model. Perhaps we should do the same for screen.activeProperty, or is that where it is for a specific reason?

**Comment by samreid** [comment] 2020-06-23 14:48
Both moves sounds like a good idea to me, but will need to be reviewed and confirmed at a PhET-iO meeting with designers.  Let's schedule for Thursday.

**Comment by zepumph** [comment] 2020-06-25 17:28
After discussing the placement of Screen.nameProperty and Screen.activeProperty in the studio tree, we think it should stay in the same place. It is clearer that the `nameProperty` is nested directly under the screen, if it HAD to be under the `model`, then it would likely be needing a rename to something like `screenNameProperty`, but that feels like a unhelpful step. We also noted that Screen.js composes the model, so the nesting makes sense as the code structure is concerned. @kathy-phet also said that from an instructional designer perspective, it is better where it is now.

**Comment by pixelzoom** [comment] 2020-07-09 16:52
Reopening.  

This was added to HomeScreenView.js by @zepumph in https://github.com/phetsims/joist/commit/41826bec1881d460551e4062da2b3a025f43799a:

```js
    // Have this before adding the child to support the startup layout.
  // Have this before adding the child to support the startup layout.
  titleText.boundsProperty.link( () => {
    titleText.centerX = this.layoutBounds.centerX;
  } );
```

This is a potential infinite loop -- when `centerX` changes, it causes `bounds` to change.  The solution is to observer `titleText.localBoundsProperty`.

This block sim publication, because it affects all sims.

**Comment by zepumph** [comment] 2020-07-09 18:18
Thanks for the heads up. The nuance of bounds vs localBounds is often lost on me. Please review and feel free to close.

**Comment by pixelzoom** [comment] 2020-07-09 18:25
👍 Closing.

**Closed by pixelzoom** 2020-07-09 18:25 UTC
Labels: dev:phet-io, priority:2-high, status:blocks-publication, status:ready-for-review
